### ISSUE TITLE
Wallet initialization, taskInit.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#100]
See that under Windows 7 x64.
I hope it is common problem for all windows. Logs are not helpful because this operation contain sensitive data and it is censored

**Comment by cgilliard** [comment]
Confirmed this does not happen to me on windows 10 64 bit or windows 10 32 bit. So looks like a windows7 specific issue.

**Comment by bayk** [comment]
Under Windows 7 it works for me now, I can't reproduce. I don't know, may
everything was slow I an I tough that it is wrong.
I any case I will retry it on fresh OS.

**Comment by bayk** [comment]
Everything work fine now. Probably a glitch, or it is already fixed.
