### ISSUE TITLE
wallet resize was too big. Was not able to easily get it smaller because I couldn't scroll.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#101]

**Comment by bayk** [comment]
I saw that on Windows with resolution 800x600.  There is not much what we can do.
Our design expected that resolution is large enough. I will check if there will be scrolling for internal window.

**Comment by bayk** [comment]
Will try something like this:
https://forum.qt.io/topic/25109/scrollbar-main-window/6

**Comment by bayk** [comment]
Out minimal window size 640x480.  In such small window scroller will be activated
