### ISSUE TITLE
Windows 7 report app crash when we close it.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#103]
Need to check how WIndows know if app was crashed or exited.  It reacts the  same for 'close' or for internal restart.

**Comment by bayk** [comment]
Update.
Windows 7 with build tools and latest updates is fine, no issues.

**Comment by cgilliard** [comment]
Do people generally have build tools installed though?

**Comment by bayk** [comment]
Found the real issue. Because of slowness gui killed child mwc713 process and windows 7 detected that. By some reasons update fixed that.
Waiting time is increased and everything fine now.
