### ISSUE TITLE
passwords with special characters return "password invalid" for claims.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#107]
Confirmed the password works, but must be urlencoded. I suspect url encoding is not done on the password passed in.

**Comment by bayk** [comment]
Yes, url need to be escaped. Will fix that. Please email me how I can test it.

**Comment by cgilliard** [comment]
Will get that to you soon. Working on a bug with this. Looks like there are
some other problems.
