### ISSUE TITLE
latest build of qt wallet crashes on start 

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#109]
On startup see screenshot.
![Screenshot (4)](https://user-images.githubusercontent.com/7232183/65211834-eaa06900-da54-11e9-9815-f97de6205653.png)

**Comment by cgilliard** [comment]
The issue was that I had installed a 32 bit version then tried 64 and lmdb crashed.

**Comment by bayk** [comment]
It is expected. Imdb is not covered yet, imdb issue is open

**Comment by cgilliard** [comment]
Duplicate https://github.com/mwcproject/mwc-qt-wallet/issues/58
