### ISSUE TITLE
Update Privacy related setting before release

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#11]
Before go to release we need to disable logs to increase privacy. Normally we don't want to have any trace of what was done with the wallet.

Also we might disable mwc713 history as well

**Comment by cgilliard** [comment]
Are you sure? I'm kind of concerned that if we do that and we have any
problems it will be almost impossible to debug. Maybe instead we document
what logging occurs so users will understand what's there.

**Comment by bayk** [comment]
Mimble Wimble all about privacy, right?   What is the reason to lock wallet if from the logs you can see everything except passwords. I think it make sense try to keep it. 
I think if wallet will be stable, we can do that. For troubleshooting logs might be activated.
Also it is easy to detect if app was failed on prev run, we might ask user if he want to activate the logs if we detect that wallet is unstable.
So far mwc713 is pretty stable, I think we should be fine.

**Comment by cgilliard** [comment]
Ok, that probably works. Is it easy for the user to enable logs?

--Chris

**Comment by bayk** [comment]
For this release will add settings for the logs. Default will be enabled.

**Comment by bayk** [comment]
Hi @cgilliard,  please check the tooltip and messages that are printed when we turn on/off the logs.
Logs can be enabled/disabled at  Wallet Config page. I will trigger the nightly builds, so they will be ready in an hour
