### ISSUE TITLE
Handle cases when mwc713 trying to reconnect for listeners

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#113]
mwc713 has reconnect logic inside but it makes a lot of confusion. 
For example, if wallet lost connection, status will be "Offline" and for user it is no difference from never started.
As a result, when user press button 'Start', he gets an error "Listener is already started".
Problem gets worse when Wallet process complicated queries, like Resync.

To feel the pain, start wallet with keybase listener.  Then stop Keybase. 
Now good luck to do anything that expecting to stop listeners, like resync. 

@cgilliard, I am going to track event when start for listener was requested.  In this case I will do stop, even if it is offline.  I think it is the best what we can do.

**Comment by cgilliard** [comment]
Yes I think this is the right approach.
