### ISSUE TITLE
mwc-node:  api_secret_path doesn't work

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#115]
Hi Chris,

If I start mwc-node at custom directory, or if I start as
mwc --floonet  server --config_file <path>/mwc-server.toml run

It doesn't use api_secret_path value and doesn't use basic authentification.

Expected that it will read setting from mwc-server.toml
api_secret_path = "api_secret"
Then init file 'api_secret' at current dir with secret and will start using it.

In both cases (toml in current dir, start with server --config) it apply setting differently. But in both cases authentification doesn't work.

**Comment by cgilliard** [comment]
Basic authentication is working for me, but they did make it off by default in Grin 2.0.0 which we rebased from. From what you said though you turned it on and it didn't work. It should work.

**Comment by cgilliard** [comment]
We are using basic authentication in production. Here's what the
configuration looks like:


Can you try that and let me know if it works? I think you need the fully
qualified path.

**Comment by cgilliard** [comment]
api_secret_path = "/home/ubuntu/seed_floo4/.api_secret"

**Comment by bayk** [comment]
Hi Chris,

Yes, your example works fine with default settings.
I found the problem for my case.

1. mwc-node on start create secret if it doesn't exist  at
~/.mwc/floo/.api_secret
    It is done before ever config is readed. The path for this step is
hardcoded.
   /mw/mwc-node/config/src/config.rs    Lines: 75-134
  See method  initial_setup_server

2. mwc-node read  mwc-server.toml => api_secret_path.  If this file exist,
it activates authentification.

It didn't work for me because I was expected to mwc-node to create that
file, but it is not a case, step one doesn't init file from toml config.
Also it explains why there is allways a ~/.mwc/floo/.api_secret  file.
Doesn't matter what you have in your config.
If I am creating a secret file that I specify, it start working for me.

Do we want to keep that logic? Seems like idea is if user wants to change
secret file location - it is his problem how to init it.
For me the issue that mwc-node doesn't panic in a case the expected secret
is not found at expected file. Instead it disable authentification.

Thanks,
Konstantin

**Comment by cgilliard** [comment]
The only problem is the more changes we make from grin, the harder the
rebases are. I think what we should do in cases like this is open a
bug/feature enhancement against grin's full node. That way it will get into
the upstream next time we rebase.

**Comment by bayk** [comment]
ok, sounds good. In any case we have workaround, so we are good.

**Comment by bayk** [comment]
Close, we don't want to change logic.
