### ISSUE TITLE
Linux splash screen not re-sizable to fit the screen.

### ISSUE THREAD

**Issue by pocketLNio** [mwcproject/mwc-qt-wallet#117]
The initial screen where we can create a password is too large (running 1360x768) to fit into the screen.  Tried to adjust the window but is not responsive.  Running Linux Mint 19.2 XCFE.

**Comment by cgilliard** [comment]
Spoke with user, he switched to the LR version and things looked fine. We might need auto-detect or some other way to determine which version to use.

**Comment by bayk** [comment]
Password windows are not scrollable, they expected to be 'small'. Seems like it is not a case for that user. In such case let's detect resolution and update the scale.

**Comment by bayk** [comment]
Fixed. I tried at 800x600 and it worked good enough for me. Please node, scale silently downgraded at the start. So I user setup the large scale, it will be accepted, but then will be changed to low scale at the start.

**Comment by cgilliard** [comment]
Great, so pocketLnio can see this in tomorrows nightly build right?

**Comment by bayk** [comment]
I already trigger the build. In one hour nightly should updated.
