### ISSUE TITLE
got "Not found expected output from mwc713"

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#121]
I sent on windows and I saw this message. The transaction seemed to be finalized and confirmed correctly so I'm not sure what the message meant.

**Comment by cgilliard** [comment]
See screenshot. It can be reproduced seem every time.

![Screenshot (5)](https://user-images.githubusercontent.com/7232183/67255673-1b026b00-f438-11e9-9d8a-7f6f78650d70.png)

**Comment by bayk** [comment]
Can you send me the logs

**Comment by cgilliard** [comment]
[mwcwallet.log](https://github.com/mwcproject/mwc-qt-wallet/files/3753638/mwcwallet.log)

**Comment by bayk** [comment]
I think I understand the problem.  Editor prompt "wallet713>"  printed
sometimes. I should really filter it out. I am using different prompt that
I specify in command line that is printed with command execution is
finished.
