### ISSUE TITLE
icons cut off on linux

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#122]
The "send", "receive", etc icons are cut off a bit on linux. I'm using the high resolution. Low res too small. See screenshot.
![Screenshot from 2019-10-22 02-55-25](https://user-images.githubusercontent.com/7232183/67256619-a6e7b780-f477-11e9-97f4-4b1d23221cd5.png)

**Comment by bayk** [comment]
That effect comes from QT scaled method. Small increase of icon size helped
