### ISSUE TITLE
win-64 wallet v1.0.6 crashes when I change data folder name

### ISSUE THREAD

**Issue by BitcoinAscent** [mwcproject/mwc-qt-wallet#125]
I click [Wallet Configuration]
click [Select] next to "Wallet folder name"
pick the folder (on a different drive) I want to store the wallet data
click [Select Folder]
and the wallet crashes

**Comment by cgilliard** [comment]
I can reproduce this issue on windows if you select a different drive, it crashes.

**Comment by cgilliard** [comment]
only works if it's in the same drive as the install at the moment.

**Comment by BitcoinAscent** [comment]
OK. For now... I guess I could un-install it, then re-install it to the drive I want the data on.

**Comment by bayk** [comment]
Just created another issue:  #126 
https://github.com/mwcproject/mwc-qt-wallet/issues/126

**Comment by bayk** [comment]
Next build will have those changes
