### ISSUE TITLE
Suggestions about passwords

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#127]
@cpgilliard I tried the wallet, but already see some issues at the password screen, where it is requiring an upper case letter, and complaining about low entropy for diceware type passwords generated using a password manager.
Short summary: https://xkcd.com/936/
Current best practices: https://pages.nist.gov/800-63-3/sp800-63b.html
Sophos summary of the NIST guidelines: https://nakedsecurity.sophos.com/2016/08/18/nists-new-password-rules-what-you-need-to-know/

**Comment by bayk** [comment]
Thank you for the links. We will check them and probably adopt what is relevant to our case.

**Comment by bayk** [comment]
Current changes are follow  https://nakedsecurity.sophos.com/2016/08/18/nists-new-password-rules-what-you-need-to-know/
