### ISSUE TITLE
Got critical wallet error

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#131]
![mwc](https://user-images.githubusercontent.com/7232183/68912457-0babd000-070d-11ea-9193-89309fa54cdd.png)

User got this error on windows. Asked for logs, but unfortunately they have sensitive data and we might not be able to get them. Will upload logs if I get them.

**Comment by cgilliard** [comment]
Note: user was able to continue by exiting and restarting the wallet with no problem so it's wasn't a show stopper, but if we can address we should.

**Comment by bayk** [comment]
Will be cover with  https://github.com/mwcproject/mwc-qt-wallet/issues/132

**Comment by bayk** [comment]
Better message that helps troubleshooting is printed
