### ISSUE TITLE
User not able to start mwc-qt-wallet

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#132]
User reporting error when starting mwc-qt-wallet. User appears to be on Windows. 
![photo_2019-11-15 12 45 34](https://user-images.githubusercontent.com/7232183/68974536-d99a7c80-07a5-11ea-8057-3d968652af74.jpeg)
See screenshot and logs.
[mwcwallet.log](https://github.com/mwcproject/mwc-qt-wallet/files/3853086/mwcwallet.log)

**Comment by cgilliard** [comment]
User noted that his anti-virus was turned on. Turning it off, deleting the mwc-qt-wallet, and restarting the wallet resolved this issue. Keeping this issue open as we may be able to improve messaging to users when this type of issue happens.

**Comment by bayk** [comment]
The changes:
- That dialog will be updated with a suggestion about the disk space, and antivirus.
- I will print a command line.
- Message Box dialog text need to be copyable

The same will be for the embedded node as well.
