### ISSUE TITLE
spendable: 0, total: 319, awaiting confirmation: 0

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#134]
See screenshot. This should not be possible right?
![photo_2019-11-18 23 55 37](https://user-images.githubusercontent.com/7232183/69127523-3d030380-0a5f-11ea-869b-e68562759879.jpeg)

**Comment by bayk** [comment]
Yes, they should check what is  mwc713  info said

**Comment by bayk** [comment]
To recover - they can resync

**Comment by cgilliard** [comment]
Yes, haven't heard from them. Hopefully just a fluke.

**Comment by bayk** [comment]
Let's close, we can't reproduce it in any case
