### ISSUE TITLE
HTML seen in confirmation message

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#135]
See screenshot (mac)
<img width="645" alt="Screen Shot 2019-11-21 at 1 07 57 PM" src="https://user-images.githubusercontent.com/7232183/69376895-05af7500-0c60-11ea-9476-7061d4ab344c.png">

**Comment by cgilliard** [comment]
I'm seeing a bunch of issues like this which look like graphics glitches.

I think it might be related to: https://github.com/mwcproject/mwc-qt-wallet/issues/129

Can we make the scale factor configurable?

**Comment by bayk** [comment]
I will review the massages. Seems like we need to separate html and plain text
