### ISSUE TITLE
Need context help for a new Page: Select Running Mode

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#137]
Hi Chris,

Please send me what to put into the help page for that page:

![image](https://user-images.githubusercontent.com/42393608/69504540-8e384a80-0ed8-11ea-9cc6-86d382395dec.png)

**Comment by cgilliard** [comment]
"This page allows you to select whether you are running the MWC Qt Wallet as a standard online hot wallet (the default choice and what most users will use), An "Online Node" which is used to submit transactions from cold storage, or a "Cold Wallet" which is used in conjunction with the "Online Node" and installed on a computer that never connects to the internet. Transactions are sent/received/finalized on the "Cold Wallet" but submitted with the "Online Node".

If we have a wiki page with more details, we can link to it from this help page.

**Comment by bayk** [comment]
Thank you.
I will try to adopt your cold wallet documentation for that.

**Comment by bayk** [comment]
Note, push in the branch 2019_09_cold_wallet.  Also will update and add a link to document
