### ISSUE TITLE
comments on password/seed phrase

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#139]
im not sure if its just the mac wallet, but my first impression is that setting up a new wallet is terrible
i should have used less aggressive terminology.  my goal is not to attack, just venting some frustration.
1. password must be 10 characters, but also restrictions based on dictionary. 
  1a. for most people the biggest chance of loss is due to losing or forgetting a password.  this is increasing that risk. 
2. the seed word check is fairly aggrevating.  It asks for the words all in random order, but the seed words are not give in a way to make this easy.  I find my self having to start each and every one by counting from the front or back and going forward or backwards.  "enter word 11.  1, 2, 3, 4 ,5 ,6, 7, 8, 9, 10, 11.... January.
If you're going to require users to randomly type this back in, you should provide the seed words already organized by number visually as opposed to a list in string format.
ie: instead of "seven samurai sporting standard swords ...."
do:
1. seven
2. samurai
3. sporting
4. standard
5. swords
6.   ....
further, if doing it in this manner, is it really required to make the user then check all 24 in this manner?  i kept expecting to be done after 3 or 4. then i was like, ok maybe 7 or 8.   10?  half at 12?
then, i mistyped an answer
oh boy
starting.  all.  over.
end rant
ty

**Comment by grasponcrypto** [comment]
my suggestion would be 2 fold:
1. visually place the seed words into a numbered list in 4 columns of 6 words each
2. seed word verification should either be all 24 words in proper order for ease, or a subset of the words in random order.  this may become a non-issue as the ui is improved.
3.  modify the ui to provide more information to the end-user in case of wrong word or typo so they are aware they are not starting over.  something like, "word entered incorrectly, please try again starting where we left off".

**Comment by bayk** [comment]
Password length limit is 8, but with all characters usage.  10 will be if characters are all low case or capitals. Assumption is brute force attack.
I will check if we can ease that. We don't want password for stolen seed be cracked faster than in a year on the cluster. We assume that cracker is smart enough to use character subsets like low case only, dictionaries and combinations of them.

Seed let's do in order and total 3 possible mistakes will be applicable to all words. After 3 mistakes, all phrase will be re requested.
Mistaken word will not be re requested in order.  For example,  1,2,3,4...24 . You make mistake at 5.  Next word will be 5.

**Comment by bayk** [comment]
Only fixed differently "seed words into a numbered list in 4 columns of 6 words each".   I make 6 columns of 4 words each.  Actually it is 4 rows with 6 words each. 
Reason because of the look. Our font is not monospace as a result columns are not aligned. 4 columns look ugly.  6 - acceptable.
