### ISSUE TITLE
UI enhancement - "Apply button"

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#140]
Had a call with a user who wasn't seeing changes show up in the UI. Found out he needed to click the "Apply Button" after selecting a new Wallet folder.

Potential solution: if you navigate away from the "Wallet Configuration" without clicking apply, the user is notified and asked if they want to save changes.

**Comment by bayk** [comment]
Yes, make sense.

**Comment by bayk** [comment]
Implemented:   if you navigate away from the "Wallet Configuration" without clicking apply, the user is notified and asked if they want to save changes.

Now states through widows can block state switching.
