### ISSUE TITLE
UX Enhancement - Send MWC Page

### ISSUE THREAD

**Issue by pocketLNio** [mwcproject/mwc-qt-wallet#141]
Maybe it is possible to place highly visible notice to the "Send MWC" page:

"IMPORTANT - ONLINE SEND: Make sure the destination wallet is online before sending."

**Comment by bayk** [comment]
Will update confirmation message with that.

**Comment by airdropmario** [comment]
@bayk It would also be good to inform the user that the online wallet needs to be listening for the specific address being sent to. Perhaps this text:

"IMPORTANT - ONLINE SEND: Before sending make sure the destination wallet is online and listening for the destination address."

**Comment by bayk** [comment]
@airdropmario , @pocketLNio , @cgilliard 
If transaction failed, it is not a big deal, it can be cancelled. Warning should say:
1.  transaction will not be  finalized if the destination wallet is offline and and not listening for the destination address.
2. Until it is finalized your fund at that output will be blocked.
3. You can cancel your non finalized transaction  and unblock your funds at "Transactions" page.

Number 2 and 3 applicable to file transactions as well.

How can we say that nicely?

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/70380157-b74ed700-18eb-11ea-8524-76d69fbb947a.png)

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/70380221-7f945f00-18ec-11ea-9b28-a783d41e976e.png)


I think it is enough to Update the main send page with that. I am not updating the message boxes. It is better not overload them with too much info.
Also  Send Confirm dialogs will be enriched soon with a password, so there are not much to put there.

@condensed-io ,  here is how send page looks now.
