### ISSUE TITLE
Password encoding issue when requesting airdrop

### ISSUE THREAD

**Issue by petegraves** [mwcproject/mwc-qt-wallet#143]
I get a "Network error" when requesting airdrop for one address (query parameter values removed):

> Unable to communicate with https://wallet.mwc.mw.
> Get communication error: Error transferring https://wallet.mwc.mw/v1/getAmount?password=#&btcaddress=# - server replied: Unable to parse URI query

I suspect it's related to how the password for this address has been encoded in the URL, as other addresses have worked fine, and it contains more symbols than my other passwords.

**Comment by cgilliard** [comment]
Thanks for reporting. We'll look into it. For now, please set your password to something without the symbols.

**Comment by petegraves** [comment]
Thanks, changing the password to one without symbols fixed it.

**Comment by bayk** [comment]
Hi Chris. Wallet is encoded URL.  It looks good on my side. Can you find what was exactly wrong with URL?

**Comment by cgilliard** [comment]
Maybe @petegraves can give us an idea of what symbols were in the password?

**Comment by cgilliard** [comment]
The servlet is using HttpServletRequest.getParameter: https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html#getParameter-java.lang.String-

It's supposed to decode the URL I think, unless it's a bug in the library.

**Comment by bayk** [comment]
I tested with special symbols and spaces. It worked for me and server
processed it well.

**Comment by petegraves** [comment]
My password was similar to: m3nDDh@YC^$%CbCZM

The encoded URL in the error message was:
 
https://wallet.mwc.mw/v1/getAmount?password=m3nDDh@YC%5E$%CBCZM&btcaddress=...

**Comment by bayk** [comment]
Thank you. QT encoded not all symbols. Probably it is reason.   Correct encoding should be like that m3nDDh%40YC%5E%24%25CbCZM
Seems like that functionality need to be implement it by ourselves.

**Comment by kccheung** [comment]
@cgilliard, I got similar problem with my password containing some special characters. May I know how to change the claiming address password?

**Comment by cgilliard** [comment]
You can change it here: https://wallet.mwc.mw/registration.html

**Comment by bayk** [comment]
Fixed, with that example server is able to process the request and return expected respond
