### ISSUE TITLE
mwc713 crashes on windows 7 causing "crtical error" 

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#144]
User reported that it's not working on windows 7. Here's his log:

Complete Log from C:\Users\<user>\mwc-qt-wallet\logs\mwcwallet.log

03.12.2019 04:02:53.783  mwc-qt-wallet is started...
03.12.2019 04:03:19.349 MWC713 Wallet initialization checking status: Initialized
03.12.2019 04:03:19.377 Mwc713EventManager Task Mwc713Task(name=Starting)  Starting...
03.12.2019 04:03:19.428 mwc713>> ERROR OCCURRED. Error = 1
03.12.2019 04:03:23.501 mwc713>> Exit with exit code -1073741701, Exit status:1
03.12.2019 04:03:23.531 mwc713>> ERROR OCCURRED. Error = 1
03.12.2019 04:04:54.208  mwc-qt-wallet is started...
03.12.2019 04:05:08.811 MWC713 Wallet initialization checking status: Initialized
03.12.2019 04:05:09.027 Mwc713EventManager Task Mwc713Task(name=Starting)  Starting...
03.12.2019 04:05:09.069 mwc713>> ERROR OCCURRED. Error = 1
03.12.2019 04:05:12.154 mwc713>> Exit with exit code -1073741701, Exit status:1
03.12.2019 04:05:12.184 mwc713>> ERROR OCCURRED. Error = 1
03.12.2019 04:05:53.618  mwc-qt-wallet is started...
03.12.2019 04:06:00.161 MWC713 Wallet initialization checking status: Initialized
03.12.2019 04:06:00.182 Mwc713EventManager Task Mwc713Task(name=Starting)  Starting...
03.12.2019 04:06:00.231 mwc713>> ERROR OCCURRED. Error = 1
03.12.2019 04:06:01.660 mwc713>> Exit with exit code -1073741701, Exit status:1
03.12.2019 04:06:01.724 mwc713>> ERROR OCCURRED. Error = 1
03.12.2019 04:10:39.270  mwc-qt-wallet is started...
03.12.2019 04:12:53.511 mwc713>> ERROR OCCURRED. Error = 1
03.12.2019 04:22:18.558  mwc-qt-wallet is started...
03.12.2019 04:22:24.336 MWC713 Wallet initialization checking status: Initialized
03.12.2019 04:22:24.361 Mwc713EventManager Task Mwc713Task(name=Starting)  Starting...
03.12.2019 04:22:24.649 mwc713>> ERROR OCCURRED. Error = 1
03.12.2019 04:22:26.545 mwc713>> Exit with exit code -1073741701, Exit status:1
03.12.2019 04:22:26.575 mwc713>> ERROR OCCURRED. Error = 1
03.12.2019 04:35:33.253  mwc-qt-wallet is started...
03.12.2019 04:35:43.923 MWC713 Wallet initialization checking status: Initialized
03.12.2019 04:35:43.980 Mwc713EventManager Task Mwc713Task(name=Starting)  Starting...
03.12.2019 04:35:44.123 mwc713>> ERROR OCCURRED. Error = 1
03.12.2019 04:35:47.765 mwc713>> Exit with exit code -1073741701, Exit status:1
03.12.2019 04:35:47.841 mwc713>> ERROR OCCURRED. Error = 1
03.12.2019 04:37:08.377  mwc-qt-wallet is started...
03.12.2019 04:39:30.837 mwc713>> ERROR OCCURRED. Error = 1

**Comment by bayk** [comment]
"ERROR OCCURRED" mean that mwc713 crashed almost immediately after the start. Will try to reproduce

**Comment by bayk** [comment]
I can't reproduce. It works now. 
Current nightly already address logging issues for such cases. So let's wait until the same issue will be reproduces with a new version.
