### ISSUE TITLE
better error on finalizing a slate that is intended to be received.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#145]
A common user error is for a user to try to finalize a slate that they are supposed to receive. If possible to detect that the slate file should be received instead of finalize, we should give a more descriptive warning. Currently the error will always say "ERROR: failed to finalize slate". If it's a receive slate maybe say something like "ERROR: this slate should be received, not finalized".  One way to tell the difference is that a slate that should be received will only have one participant data element and a slate that should be finalized will have two participant data elements.

**Comment by bayk** [comment]
qt wallet can check if slate for 'receive'/signing of finalization and print appropriate message about that

**Comment by bayk** [comment]
Add a validation by slate content. Before there was a validation by file extension. I guess users changed file extensions.
