### ISSUE TITLE
user reports error when trying to claim.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#147]
See screenshot and logs.

![duhsga](https://user-images.githubusercontent.com/7232183/70075486-c2cf9480-15b1-11ea-9992-1ccd327c1df4.png)

**Comment by cgilliard** [comment]
[mwcwallet (3).log](https://github.com/mwcproject/mwc-qt-wallet/files/3918254/mwcwallet.3.log)

**Comment by bayk** [comment]
Fixed at https://github.com/mwcproject/mwc-qt-wallet/issues/148
