### ISSUE TITLE
claim request failed Unable to process the slate with mwc713 to complete the claim.

### ISSUE THREAD

**Issue by ClaimyMcClaim** [mwcproject/mwc-qt-wallet#149]
claim request failed 
Unable to process the slate with mwc713 to complete the claim.

**Comment by cgilliard** [comment]
Please upload your logs. They should be in
C:\Users\username\mwc-qt-wallet\logs

**Comment by bayk** [comment]
@ClaimyMcClaim , does your home directory has non English symbols?

**Comment by ClaimyMcClaim** [comment]
im using windows10, my username is a single ascii character
after getting the claim error i also get "Awaiting response file. Claim accepted."
so which one is it? did it fail or was it accepted?
[mwcwallet.log](https://github.com/mwcproject/mwc-qt-wallet/files/3921315/mwcwallet.log)

**Comment by cgilliard** [comment]
@claimymcclaim is your username "~" ? I think that might be the problem.
Can you retry with a username like "abc"?

**Comment by ClaimyMcClaim** [comment]
creating a new username worked, thanks
