### ISSUE TITLE
wallet closes, right after login

### ISSUE THREAD

**Issue by joejeronimo** [mwcproject/mwc-qt-wallet#152]
using win10 64bit

added logfile

[mwcwallet.log](https://github.com/mwcproject/mwc-qt-wallet/files/3924355/mwcwallet.log)

**Comment by cgilliard** [comment]
Logs show that the password started with a "-" and that's what caused a problem. After asking the user to change to a different password it worked. Should either prevent users from setting a password that starts with a "-" or ensure it works.

**Comment by bayk** [comment]
Will try to fix it. Also probably '--' will not work too because of the same reason.

**Comment by bayk** [comment]
Add validation for first '-' symbol.  We have to deal with mwc713  config parser.
