### ISSUE TITLE
how to sign message after airdrop screen

### ISSUE THREAD

**Issue by Alphen123** [mwcproject/mwc-qt-wallet#155]
I followed the instructions as described on the MWC. I created a new MWC wallet etc. In the Airdrop screen, when i fill in one the BTC adresses (which where registred during phase 1) and the MWC password I see a challange and I've the possibility to enter the signed message.  How can I sign the message?  This is not clear to me.

**Comment by cgilliard** [comment]
You have to sign the new message which looks like "CLAIM_XXXXXX.." the same way you signed the message to register. The signature will look like this: Gx3DjXYuTur2sTzi3bkmHNbVcPhbnIv9kVfEqwcW393Sf0afwpPT1s69x9WCSdZTgJ/PyjaSPyOZfqy5GB8LqMA=

**Comment by Alphen123** [comment]
Thank you for the quick reply. I see the Claim button, but I guess I need to sign the message with my Ledger? Unless the ledger is connected, It looks like there is no interaction between the MWC wallet and the ledger.

**Comment by cgilliard** [comment]
Correct you need to sign on the ledger.

**Comment by Alphen123** [comment]
Maybe we ask something stupid, but we don't get passed trough te sign process. This is the procedure we've followed. 1) Connect the Ledger live to the pc and unlock it. 2) Open MWC app with password, select Airdrop button and enter a registered BTC adress and our MWC password and click on 'Request airdrop' 3. Now we've to enter the Signed message I.e. sign the message with the ledger. Unfortunateley we didn't get a reaction from the legder. What (stupid little) thing we do wrong?

**Comment by cgilliard** [comment]
This video may help: https://www.youtube.com/watch?v=Y5H-_cPhcew (you can
use electrum)
