### ISSUE TITLE
users logged out and mqs not listening

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#157]
See screenshot.
![image0](https://user-images.githubusercontent.com/7232183/70376457-33cac100-18be-11ea-8841-24448108cbb7.jpg)

Think we should do two things, look into why it's logging users out, but also make the auto-logout optional. Some users are trying to withdraw from exchanges and it takes a long time they have to keep refreshing and monitoring.

**Comment by bayk** [comment]
Auto logout currently is 30 minutes and changeable at config file only. Probably we should have a settings for that.
For settings seems like we will need another page, what we have is crowded.  
@condensed-io ,  I will add a button 'More' that will open next setting page. 
What do you think about that?  Do you have better alternative?

**Comment by bayk** [comment]
@cgilliard , about the mwc mqs.  wmc713 should reconnect even if it lost connection. Since keybase is listening,  MQS should be trying to reconnect.  Another possibility that user turn off MQS.

**Comment by bayk** [comment]
@cgilliard , I just accidentally hit listener issue.

mwc713 returns the error on start and never try to reconnect.

07.12.2019 14:09:13.916 mwc713>> ERROR: Failed to start mwcmqs subscriber. Error connecting to mqs.mwc.mw:443

I think we should fix 'never try to reconnect' problem.  I will take a look into it
Occasional connection failures are expected, so I don't think it is a problem.

**Comment by bayk** [comment]
The  mqs listener  not started and never try again is fixed.
Now it is not stated and try forever every 5 seconds until 'Stop' will be pressed at "Listening"

**Comment by bayk** [comment]
For settings issue created:   https://github.com/mwcproject/mwc-qt-wallet/issues/158

This one is closing because listening is fixed.
