### ISSUE TITLE
Add more Settings:

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#158]
1.  auto-logout  options:   3 minutes, 5 minutes, 10 minutes, 20 minutes, 30 minutes, never (disabled)
2. Use MWC MQS  listener
2. Use  Keybase listener.

Also, for settings seems like we will need another page, what we have is crowded.
@condensed-io , I will add a button 'More' that will open next setting page.
What do you think about that? Do you have better alternative?

Note:  ticket can be started after Cold Wallet code will be in the master.  We don't want merge conflicts, especially at the resources level.

**Comment by bayk** [comment]
Solution with Tab and multiple pages is available at the branch   feature/expand-settings

**Comment by vinayaga07** [comment]
@sarawut11 
Could you please confirm, whether the above fix has been merged  to the Master branch?
If yes, I'll verify the same.

Thanks,
Vinayaga.

**Comment by bayk** [comment]
Yes, it was merged into the master. I did that. Nightly build should have it

**Comment by vinayaga07** [comment]
Verified with the latest build and observed the following settings,
1. auto-logout options: 3 minutes, 5 minutes, 10 minutes, 20 minutes, 30 minutes, never (disabled)
2. mwc MQS listener
3. keybase

Hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/79781409-0f4a1f80-835b-11ea-8e6c-4ad6c99a566b.png)
