### ISSUE TITLE
tried to start in node mode but got critical error

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#159]
![Screen Shot 2019-12-17 at 12 54 00 PM](https://user-images.githubusercontent.com/7232183/71033579-6e0d3d00-20cc-11ea-8f10-dd5543bf95cc.png)
[mwcwallet.log](https://github.com/mwcproject/mwc-qt-wallet/files/3975441/mwcwallet.log)
[Uploading prev_mwcwallet.log…]()

**Comment by bayk** [comment]
@cgilliard , looks like the mwc713 point to the account without a password. I have that for Online Node.
There is a chance that  it is not switched can you check if 
~/mwc-qt-wallet/wallet713v2.toml  
has a record   
wallet713_data_path = "tmp/online_node_wallet/Floonet"

**Comment by cgilliard** [comment]
Here's my wallet713v2.toml:

chain = "Mainnet"

wallet713_data_path = "tmp/online_node_wallet/Mainnet"

keybase_binary =
"/Applications/Keybase.app/Contents/SharedSupport/bin/keybase"

mwc_node_uri = "http://127.0.0.1:13413"

mwc_node_secret = "ALcKnTFLXGxqTvqLzWqs"

grinbox_listener_auto_start = false

keybase_listener_auto_start = false

default_keybase_ttl = "24h"


When I restarted it worked though.

**Comment by bayk** [comment]
That config is "Online Node" config and it should be changed at the start.
I can't reproduce it. For me it is updated on start well.

Can you specify how to reproduce it?

**Comment by cgilliard** [comment]
I'm not exactly sure what I did, but I was using this as a regular wallet before I changed the mode to "Online Node".

**Comment by bayk** [comment]
Not able to reproduce an issue. Code is updated with logs. Next time we should have more info to troubleshoot.
