### ISSUE TITLE
Listening on multiple addresses at the same time

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#170]
There have been a few requests for this. Requires changes to mwcmqs and mwc713. I think the best option is to listen to all addresses that have received transactions. Opening this as a placeholder for later implementation.

**Comment by bayk** [comment]
Here is a related issue 
https://github.com/mwcproject/mwc-qt-wallet/issues/151

**Comment by bayk** [comment]
Closed because long term plans is retire MQS. TOR doesn't support that. It doesn't worth it to implement.
