### ISSUE TITLE
Add 'add'/'remove' contact at the contact dialog

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#172]
when you go to send coins to someone, typically they will give you the address to send to, you'd copy it to your clipboard, then go into the wallet and go to send.

When you are in there you'd see the send to box and the contacts button.  Lots of times you'd think that this is someone you want to send to on a regular basis, so you'd click contacts, thinking you could add them to your contacts:

![image](https://user-images.githubusercontent.com/42393608/71316889-e5c0cc00-242c-11ea-8bcc-e0c18d87963d.png)

unfortunately when contacts comes up you can't add them, you can only pick from existing contacts:

![image](https://user-images.githubusercontent.com/42393608/71316891-efe2ca80-242c-11ea-83c7-7fc54329be0c.png)

the fix is easy, we just need an 'add contact' or + button to add a new one while you are in here.  Once added you should be able to select it.

**Comment by condensed-io** [comment]
thanks K !

**Comment by bayk** [comment]
Add  3 buttons to add/delete/edit contacts like 'Contact' Panel has.
'Contact' Panel now is kind of obsolete, the functionality implemented in this dialog.
