### ISSUE TITLE
user reporting duplicate accounts in certain scenario

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#173]
Ran into a weird bug in the QT wallet. I think it results from it not checking whether an Account is duplicate.
I sent from MWC from Account 1 to Account 3 in the derivation path. The listening address was on a different laptop for Account 3 (which had been renamed to the same thing on both laptops). On laptop 2 (receive) it showed up in Account 3 and a resync also showed it. However, on laptop 1 (send) it showed up in Account 3 and Account 4. Even after a resync it still showed to two Accounts with the MWC in them (the renamed Account and 'account 1'). Make sense?
It seems that I cannot create MWC out of nothing with the bug. Although I do get a bunch of extra MWC showing up in the wallets and even resyncing do not keep the two with equal balances. And when I transfer between accounts it keeps increasing balances, etc.
And it would be nice if I could backup a wallet and restore it. That way I could sync the two laptops up. Because the way it is handling the Accounts I cannot seem to be able to delete the accounts because it thinks they have MWC in them when they do not. And the network will not accept Transfers (because there are no MWC in there).

And even when I get the coins out of it and down to zero and delete the Account if I add another Account then it resurrects the deleted account as the new account. Probably choosing from the derivation path.
And gets things back in the loop of doubling the MWC.

I finally got it all sorted out but it required deleting the wallet on laptop 2 and creating a new wallet from scratch then transferring the coins from laptop 1 to the new wallet.

**Comment by bayk** [comment]
@cgilliard. As I understand there are two issues:
- sync doesn't work properly for derivation path accounts. Wallet can apply the same output for different accounts.
- We want to be able export/import the wallet data the same way as we do for the node data in cold wallet.
Am I understand correctly the problem?

**Comment by cgilliard** [comment]
On sync, correct. On the export/import, that wasn't part of this issue, but that would be a good feature at some point.

**Comment by bayk** [comment]
v3.1  should address that issue. Import/export for the all wallet data is too complicated, user can do a backup. 
Export for Transactions - is different task.
