### ISSUE TITLE
HODL, QT wallet,  Outputs page

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#175]
At output page at make sense to show what outputs enrolled at the HODL program

**Comment by cgilliard** [comment]
I think we should keep the output page generic and show all the details
about the HODL program in the HODL tab. The HODL program will
eventually end.

**Comment by bayk** [comment]
It is just additional column with a flag.  We need somewhere should outputs that are in the HODL.

**Comment by cgilliard** [comment]
Won't all outputs be registered? Are you just showing outputs were there at
the begining of the period?

**Comment by bayk** [comment]
Yes, there will be outputs that was at the beginning of the period as HODL
server found them. Wallet might have orphans or whatever similar. That will
cover all cases because flags will be form checkAddresses respond.
