### ISSUE TITLE
Add coin / network identity for the slates generated by mwc713

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#176]
The slate a jsons so we can two fields:  "coin": "mwc"   and "network" : "Mainnet".  Those fields can be optional and can be done on mwc713 level.   In this case the whole end to end chain validation will be covered.

**Comment by yyangli** [comment]
@bayk do you want to add two optional variables like ttl_cutoff_height in slate.rs?

**Comment by bayk** [comment]
@yyangli   I think ttl_cutoff_height  is already in the slate v3

**Comment by yyangli** [comment]
@bayk no, I mean to add two new variable, like coin, network, in a way similar to ttl_cutoff_height

**Comment by bayk** [comment]
@yyangli ,  yes, add similar way, but don't bump the Slate version. Let's make them optional. If they exist wallet will check them and print nice error message is they don't match.
The primary reason is file slates, so QT wallet will be able to catch wrong network or blockchain issues.

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
