### ISSUE TITLE
Using accounts displays confirmation dialog

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#18]
When on the account transfer tab, if you click the "wheel icon", a dialog pops up asking to set the confirmations and outputs. See screenshot.
<img width="1052" alt="Screen Shot 2019-08-11 at 9 16 01 PM" src="https://user-images.githubusercontent.com/7232183/62842104-7ae0d680-bc7d-11e9-996b-a512ff3f8c6b.png">

**Comment by cgilliard** [comment]
Confirmed not happening anymore in latest build.

**Comment by bayk** [comment]
Yes, currently looks good
