### ISSUE TITLE
all log files should be kept

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#180]
Looks like log files are being deleted. For auditing purposes we need to keep logs for all instances for ever. Looks like on recovery they are deleted as well.

**Comment by bayk** [comment]
https://stackoverflow.com/questions/2598117/zipping-a-folder-file-using-qt    - how to zip them

**Comment by bayk** [comment]
Update. Unit tests are passed, but need to test installer and builds.

**Comment by jbyrer** [comment]
confirmed by sending with and w/o fluff, and watching logs

**Comment by cgilliard** [comment]
Confirmed fixed.
