### ISSUE TITLE
Transactions that are not confirmed due to reorg showing as Received and confirmed

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#181]
There were two cases like this. What happened is, funds sent then when received they showed up as Received and confirmed in the transaction tab. After running "resync with node", the funds were correctly not there, but the transaction still showed as "Received and confirmed." See screenshot. This account had exactly that amount less. There have been a few other cases like this as well.
![orphan](https://user-images.githubusercontent.com/7232183/72395783-6baffa00-36ef-11ea-8b33-9fabc9feb99f.png)

**Comment by bayk** [comment]
will be fixed at v3.0

**Comment by bayk** [comment]
Fixed by now
