### ISSUE TITLE
test impact of  wallet_updater_frequency_sec setting for mwc713

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#184]
Rebase to 3.0.0 will introduce a new option at config :  wallet_updater_frequency_sec
This value specify how often wallet can update it's state against node.  
Default is None:   Never update.
Expected value: 5 seconds.

Update likely check if last 100 blocks still has expected outputs. 

This feature is needed by the customer. The possible issue that wallet might introduce too much load to the node that is sharable between all wallets.  
We need to estimate the impact and than decide what to do.

**Comment by cgilliard** [comment]
Why is default to never update? It seems like a good feature. I think we talked about this. Users will not know that they need to sync. 5 seconds seems too often though. I think even hourly would be ok if I'm understanding this. Is there somewhere I can see the code for this?

**Comment by bayk** [comment]
Let's do that later. Currently it is a placeholder until mwc713 rebase
will be finished

**Comment by bayk** [comment]
Closed since we don't use wallet_updater_frequency_sec
Instead we do sync with balance retresh that we already have.  Also wallet_updater is adaptive, so it doesn't take much time.
This ticket is absolete
