### ISSUE TITLE
add mwcmqs feature to mwc-wallet

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#185]
Request from pool to allow for send to mwcmqs.

**Comment by bayk** [comment]
It is require upgrade to tokio and all dependency. As a result we will need to switch to async/await model.
https://blog.rust-lang.org/2019/11/07/Async-await-stable.html

**Comment by yyangli** [comment]
1. start mic-wallet in owner_api mode
./mwc-wallet owner_api --run_mqs
2. use curl command to send from this wallet to the other wallet
curl -u mwc:$password --request POST --data-raw '{"jsonrpc":"2.0","method":"init_send_tx","params": { "args": {"src_acct_name":null,"amount":"600","minimum_confirmations":2,"max_outputs":500,"num_change_outputs":1,"selection_strategy_is_use_all":true,"message":"my message","target_slate_vesion":null, "payment_proof_recipient_address":null,"ttl_blocks":null,"send_args":{"method":"mwcmqs","dest":"xmiLnRqS3MoQ1ApHqJue6gsrNDJDtVEu5JWyhcfMEFD2XGse28w3","apisecret":null,"finalize":true,"post_tx":false,"fluff":false},”address":null,"estimate_only":false }}, "id":"curltext"}' http://127.0.0.1:3420/v2/owner -v

$password should be the token in .owner_api_secret which is in you data folder $data_dir/floo/.owner_api_secret or $data_dir/main/.owner_api_secret

**Comment by jbyrer** [comment]
Scenario one passed with this command:

curl -u mwc:FQJjeSSZAOAPs1G2WRM5 --request POST --data-raw '{"jsonrpc":"2.0","method":"init_send_tx","params":{"args":{"src_acct_name":null,"amount":100000000000, "minimum_confirmations":1,"max_outputs":20000,"num_change_outputs":1,"selection_strategy_is_use_all":false,"message":"Take money!","target_slate_version":null,"estimate_only":null,"send_args":{"method":"mwcmqs","dest":"xmiLYNvAYpBJwrCvf3u7Wu7Nvt2ZVrytL2ZaqkPNPyWHyUk7Yo7Z","finalize":true,"post_tx":true,"fluff":false},"exclude_change_outputs":false, "minimum_confirmations_change_outputs": 1,"payment_proof_recipient_address":null,"ttl_blocks":1000}},"id":1}' http://127.0.0.1:3420/v2/owner

and was able to send

**Comment by jbyrer** [comment]
scenario 2 passed using the command:
./mwc-wallet --floonet send 1 -m mwcmqs -d xmiLYNvAYpBJwrCvf3u7Wu7Nvt2ZVrytL2ZaqkPNPyWHyUk7Yo7Z

**Comment by jbyrer** [comment]
For scenario 3 I was able to start the listener and send from a remote qt wallet to this one. The transaction did succeed and was verified.
