### ISSUE TITLE
transaction appears as "not confirmed" but in mwc713 it shows as confirmed

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#186]
See screenshot.
<img width="818" alt="Screen Shot 2020-02-03 at 10 29 59 AM" src="https://user-images.githubusercontent.com/7232183/73661463-7ddae380-4670-11ea-84f2-ac3ffbb978a6.png">

And mwc713 output command:
<img width="1135" alt="Screen Shot 2020-02-03 at 10 33 13 AM" src="https://user-images.githubusercontent.com/7232183/73661515-94813a80-4670-11ea-9255-2004ba52dd3f.png">

**Comment by cgilliard** [comment]
Second transaction doesn't confirm:

<img width="807" alt="Screen Shot 2020-02-03 at 10 54 57 AM" src="https://user-images.githubusercontent.com/7232183/73663327-b9c37800-4673-11ea-90ff-36fc4c502380.png">

**Comment by cgilliard** [comment]
Looks like from the mwc713 instance that's in the qt instance they are showing as "not confirmed" or false. Not sure why that's the case because when I do
<img width="1392" alt="Screen Shot 2020-02-03 at 11 21 38 AM" src="https://user-images.githubusercontent.com/7232183/73665365-5a676700-4677-11ea-8b84-f340392dd00e.png">

**Comment by cgilliard** [comment]
So, looks like an issue with "txs". Those transactions are never showing as confirmed. confirmed is always = false.

**Comment by cgilliard** [comment]
Looks like they eventually confirm, but it takes longer. Even longer than 10 confirmations in some cases. I think the logic changed because before 1 confirmation was enough.

**Comment by bayk** [comment]
Will check. I tested with 1-2 confirmations. If they change the rule for number of confirmations, I will change it back.

**Comment by bayk** [comment]
Should be fixed at mwc-wallet now.
