### ISSUE TITLE
Add/edit notes to a transaction

### ISSUE THREAD

**Issue by Jonbros01** [mwcproject/mwc-qt-wallet#187]
It would be useful to be able to select a transaction and add/notes a note to it.

**Comment by scasaletto** [comment]
Issue is in progress. Implementing adding notes for transactions using the same pattern as was done for adding notes for outputs.

**Comment by scasaletto** [comment]
Since the code for handling notes for outputs and transactions was very similar, I've created a new class WalletNotes so the majority of code between the two types of notes can be shared. So a sanity check on the output notes might be in order while testing transaction notes.

**Comment by jbyrer** [comment]
When testing on a windows cold wallet, most functionality worked well (button disabling etc.) but the text was not saved.  

Steps to reproduce:
1) Get a qt wallet with at least one transaction and output (somehow)
2) Change the running mode to cold wallet
3) Try to save notes for transactions and outputs.

**Comment by scasaletto** [comment]
Same fix as for #214. Check in one place was only allowing online wallets. Now allows online and cold wallets.

**Comment by jbyrer** [comment]
Confirmed that this works in cold wallet
