### ISSUE TITLE
Persistence of "message" in mwc-wallet,mwc713 and qt wallet

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#189]
This is a feature request: Currently if you have a message in a mwc713/qt "Send" (i.e. Description in Qt), it is only displayed on the popup window when received. It would be good to persist this data so that you can view it at a later date. This would be useful both in mwc713 and Qt.

**Comment by bayk** [comment]
@cgilliard ,  messages are already persistent in v3.X,  you can see them in transaction details in both mwc713 and mwc-wallet.
qt wallet show messages with all tx at details dialog. You can call it by double click on transaction.
Is it good enough?

**Comment by cgilliard** [comment]
Yes good enough. Will close issue.
