### ISSUE TITLE
Top of page should display "mnemonic" instead of "seed"

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#19]
See screenshot.
<img width="998" alt="Screen Shot 2019-08-11 at 9 22 18 PM" src="https://user-images.githubusercontent.com/7232183/62842170-2ee26180-bc7e-11e9-80f5-a34366ca4e07.png">

**Comment by bayk** [comment]
Chris, I guess the menu need to be updated to.
![image](https://user-images.githubusercontent.com/42393608/62913055-7f6dc380-bd3f-11e9-91c2-43075deb0f04.png)

Will "Show mnemonic" work?

**Comment by cgilliard** [comment]
Yes, that works.

**Comment by bayk** [comment]
Will be pushed soon
