### ISSUE TITLE
Using system Menu for the commands

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#197]
qt wallet doesn't use system menu. Normally all options should be duplicated there.
QT likely has controls for the system menu that will work at MacOS, Windows and Linux

**Comment by vinayaga07** [comment]
Have successfully verified all the system commands in Mac OS.
![image](https://user-images.githubusercontent.com/63310656/80512381-0977be00-899b-11ea-8e44-6e4a40166a1f.png)

**Comment by vinayaga07** [comment]
Need to verify in Windows & Linux OS versions.

**Comment by cgilliard** [comment]
Confirmed with Jim. Menus look better on Windows and Ubuntu.
