### ISSUE TITLE
View transaction commits and kernel at the explorer

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#199]
Currently mwc713 storing transaction kernel and commits for input/outputs.
So we can add API to print them and view in the tx detail dialog and view in the explorer.

That will allow users to see how kernel and commits looks at the blockchain. Nice method of verification.

**Comment by bayk** [comment]
@cgilliard , do we need that? What do you think?

**Comment by cgilliard** [comment]
I think a link to each would be nice. Kind of like with proofs.

**Comment by bayk** [comment]
@mwc-design  it is how it looks
 ![image](https://user-images.githubusercontent.com/42393608/75730630-4fb5e700-5ca2-11ea-89a7-1f44a62c0177.png)
