### ISSUE TITLE
Account transfer not working

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#20]
Account transfer button does not work. Clicking on it doesn't take me to the dialog.
<img width="137" alt="Screen Shot 2019-08-11 at 10 41 48 PM" src="https://user-images.githubusercontent.com/7232183/62843628-46731780-bc89-11e9-82ad-7b2777ca740a.png">

**Comment by cgilliard** [comment]
Confirmed in the latest build that this works now.

**Comment by bayk** [comment]
There is still an issue. I see buttons work unstable. Trying to find what is the problem.

**Comment by bayk** [comment]
Will be pushed soon
