### ISSUE TITLE
qt wallet transaction tab popups should show whole numbers first. alignment should be the opposite of what it is now.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#202]
The alignment seems to be the opposite. if a transaction has a large decimal it will show but the whole number will be cut off. we should align the opposite direction. The whole number is more important that the decimal.

**Comment by cgilliard** [comment]
Also, expand the size of the box if possible. The more of the decimal that's visible the better.

**Comment by cgilliard** [comment]
![11formatting](https://user-images.githubusercontent.com/7232183/76136622-cc7df380-6009-11ea-9c6d-809762184309.png)

See image. There is probably space to reduce the tx id a bit and some other formating.

**Comment by bayk** [comment]
fixed in release

**Comment by bayk** [comment]
New Layout
![image](https://user-images.githubusercontent.com/42393608/76147817-ebee3e00-6054-11ea-8746-53f7a4b06285.png)
