### ISSUE TITLE
Send tab should have a loading progress indicator

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#203]

**Comment by bayk** [comment]
At the start it takes time to update the balances

**Comment by cgilliard** [comment]
Yeah, it takes time. Just need a progress indicator like the transaction tab has.
<img width="206" alt="Screen Shot 2020-03-11 at 11 42 05 AM" src="https://user-images.githubusercontent.com/7232183/76451871-5a9d0580-638d-11ea-8390-9b6464f79eb5.png">
