### ISSUE TITLE
export-proof validate-proof for all send types

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#205]
We need to allow for exporting and validating proofs for all types of sends.

**Comment by cgilliard** [comment]
This is required in mwc-wallet and mwc-qt-wallet/mwc713.

**Comment by bayk** [comment]
Done

**Comment by bayk** [comment]
testing can be done in QT wallet.
Currently all sends with "Generate Proof" flag  should allow to export. This features was covered by other tickets and should work by now.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
