### ISSUE TITLE
mwc-wallet API documentation should be updated, default values should be properly set

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#207]
Users asking:
Same for the all API calls.

Hi, I am trying to send coins via wallet owner API, but get an error. Anyone knows what's an issue?

Request:
{
   "jsonrpc":"2.0",
   "method":"init_send_tx",
   "params":{
      "args":{
         "src_acct_name":null,
         "amount":1000000000,
         "minimum_confirmations":10,
         "max_outputs":500,
         "num_change_outputs":1,
         "selection_strategy_is_use_all":true,
         "message":"Take money!",
         "target_slate_version":null,
         "estimate_only":null,
         "send_args":{
            "method":"http",
            "dest":"http://127.0.0.1:3415/",
            "finalize":true,
            "post_tx":true,
            "fluff":false
         }
      }
   },
   "id":1
}

Response:
{
  "error": {
    "code": -32602,
    "message": "InvalidArgStructure "args" at position 0."
  },
  "id": 1,
  "jsonrpc": "2.0"
}

**Comment by yyangli** [comment]
it is because they are missing these two parameters in the args:
"payment_proof_recipient_address"
"ttl_blocks"

**Comment by cgilliard** [comment]
Tried that and still getting an error:

$ curl -u mwc:11ne3EAUtOXVKwhxm84U --request POST --data-raw
'{"jsonrpc":"2.0","method":"init_send_tx","params":{"args":{"src_acct_name":null,"amount":1000000000,"minimum_confirmations":10,"max_outputs":500,"num_change_outputs":1,"selection_strategy_is_use_all":true,"message":"Take
money!","target_slate_version":null,"estimate_only":null,"send_args":{"method":"http","dest":"
http://127.0.0.1:3415/","finalize":true,"post_tx":true,"fluff":false,"payment_proof_recipient_address":null,"ttl_blocks":1000}}},"id":1}'
http://127.0.0.1:3429/v2/owner

{

  "error": {

    "code": -32602,

    "message": "InvalidArgStructure \"args\" at position 0."

  },

  "id": 1,

  "jsonrpc": "2.0"

}$

**Comment by cgilliard** [comment]
Actually this worked:

curl -u mwc:11ne3EAUtOXVKwhxm84U --request POST --data-raw
'{"jsonrpc":"2.0","method":"init_send_tx","params":{"args":{"src_acct_name":null,"amount":1000000000,"minimum_confirmations":10,"max_outputs":500,"num_change_outputs":1,"selection_strategy_is_use_all":true,"message":"Take
money!","target_slate_version":null,"estimate_only":null,"send_args":{"method":"http","dest":"
http://127.0.0.1:3415/","finalize":true,"post_tx":true,"fluff":false},"payment_proof_recipient_address":null,"ttl_blocks":1000}},"id":1}'
http://127.0.0.1:3429/v2/owner


Those params need to be outside of "send_args".

**Comment by yyangli** [comment]
yes they are outside of send_args, and in args.

**Comment by bayk** [comment]
Yang, this issues and about making parameters optional if possible. All Option instead of mandatory null can be optional parameters.  Non optional, that can have defaults, can be done the same way.
There are macros that allow specify default values for fields that are not in Jsons.
It will require going through the all APIs and update that.
We don't want users specify extra parameters. Also, what will make migration easier for them.
Grin design is not user-friendly, we should do better.

Are you going to take all of that?  I will be able to take in a few days, when I finish with my current task.

**Comment by yyangli** [comment]
Kontantin, 

Yes you can work on this. I will wrap up the mqs feature.

**Comment by bayk** [comment]
https://github.com/mwcproject/mwc-wallet/commit/37af2824d6ca935b4f6e634232602de932c3a3c4
