### ISSUE TITLE
Cannot change wallet instance from the "wallet configuration" menu

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#212]
Steps to reproduce:

1.) Click the menu button and select "wallet configuration"
2.) Enter a different wallet instance in "Wallet folder name"
3.) Click "Apply"

Nothing will happen and you will still be in the same wallet instance.

**Comment by bayk** [comment]
Will take a look

**Comment by bayk** [comment]
Will be part of HODL branch and merge transaction.
