### ISSUE TITLE
Add/edit notes to a outputs

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#214]
Similar functionality as  here: https://github.com/mwcproject/mwc-qt-wallet/issues/187

**Comment by scasaletto** [comment]
Notes can now be added to outputs by double clicking on an output in the Outputs screen. Once you start to enter text in the Note field, the OK button for the Outputs screen is deactivated until you press the Save button. The notes are saved in the app context and are only visible in Qt-wallet.
I tested creating new accounts and wallet instances and switching between them. Didn't test with cold wallet but workflow should be the same. Originally I was using the wallet data directory to identify the wallet instance but I changed to using a hash of the wallet's root public key to identify the wallet instance. So if the user changes the name of their wallet instance's data directory, it should not affect the notes that are stored.
Notes are saved in the Qt Wallet app context by wallet ID, account, and output commitment.

**Comment by vinayaga07** [comment]
Have successfully verified the following scenarios with the latest build - https://ftp.mwc.mw/nightly_builds/04-20-2020/

1. OK button is enabled once we start entering text in the Note Field.
2. Able to Add Notes.
3. Able to Edit/Delete Notes.
4. Notes are getting saved.

Note:
- Need to verify the above scenarios in Cold wallet.

**Comment by jbyrer** [comment]
When testing on a windows cold wallet, most functionality worked well (button disabling etc.) but the text was not saved.  

Steps to reproduce:
1) Get a qt wallet with at least one transaction and output (somehow)
2) Change the running mode to cold wallet
3) Try to save notes for transactions and outputs.

**Comment by scasaletto** [comment]
Fixed issue where I was only allowing retrieval of the root public key, used as the wallet id, when using an online wallet. I know allow both online wallet and cold wallet.

**Comment by jbyrer** [comment]
confirmed in cold wallet.
