### ISSUE TITLE
qt wallet 'lock output' feature

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#215]
QT wallet need feature to lock outputs. On output page there will be a column "LOCK" with value yes/no.
If  user lock output, wallet will show it's balance as 'locked'.  Send will not be able to spend it.

mwc713 already allow to specify outputs for transaction, qt wallet can manage outputs for send.

Also  this need to be implemented as well to cover possible use cases:  https://github.com/mwcproject/mwc-qt-wallet/issues/214

**Comment by bayk** [comment]
Status:  Waiting for HODL weights fix to continue testing. So far this ticket is good, not issue. But still want to do end-to-end before move to QA

**Comment by bayk** [comment]
Here is a workflow document for that

https://drive.google.com/open?id=1AsG2j_KVRisE8txfdLIlxXWjrfb9KX2MC1oinnORTx4

**Comment by vinayaga07** [comment]
Tested with the qt-wallet build#mwc-qt-wallet_1.0-16.beta.20200428.2-macosx.dmg.
Able to lock the output and if we lock output, wallet show it's balance as '0'. Send is not able to spend it. Hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/80519177-33ce7900-89a5-11ea-938b-be0339403f39.png)
