### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#216]
https://docs.google.com/document/d/1p12FnhtsjQpOuHcYnmDVWwOceT5K-j1nre68hZz8tjU/edit?usp=sharing

**Comment by bayk** [comment]
@mwc-design , all except the last one are fixed, tomorrow nightly build will have it.
About the last one waiting for clarification, see Discord for details

**Comment by bayk** [comment]
Last one currently can't reproduce. I hope it is fixed

**Comment by mwc-design** [comment]
just for the record here, the last issue was me being confused about instances vs accounts.  will bring that up as a separate issue.

**Comment by bayk** [comment]
Need to review changes, seems like for some buttons handler wasn't changed. Example Sync
