### ISSUE TITLE
mwc-wallet, mwc713, and mwc-qt-wallet don't handle 502 errors

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#219]
If you send:
mwc-wallet send -d http://<address> <amount>

And the http server returns a 502 error, the wallet freezes.
Probably other errors (i.e. 404) are the same. Should test various server errors.

Expected behavior: print error message that indicates recipient server is down. (502 error or appropriate).

**Comment by bayk** [comment]
Here are test for mwc713:

wallet713> send 0.2 --to http://
Error: could not parse `http://` to a mwcmq address!
wallet713> send 0.2 --to http://0.0.0.0
Error: Request error: Cannot make request: error trying to connect: Connection refused (os error 61)
wallet713> send 0.2 --to http://12.67.56.78
Error: Request error: Cannot make request: error trying to connect: deadline has elapsed
wallet713> send 0.2 --to http://someaddressthat.not.exist.com
Error: Request error: Cannot make request: error trying to connect: failed to lookup address information: nodename nor servname provided, or not known

**Comment by bayk** [comment]
target/release/mwc-wallet --floonet send -d http:// 1
Password:
20200416 19:40:17.825 ERROR grin_wallet_impls::adapters::http - Performing version check (is recipient listening?): Request error: Cannot make request: error trying to connect: failed to lookup address information: nodename nor servname provided, or not known
Wallet command failed: LibWallet Error: Client Callback Error, Performing version check (is recipient listening?): Request error: Cannot make request: error trying to connect: failed to lookup address information: nodename nor servname provided, or not known

**Comment by bayk** [comment]
Update,

mwc-wallet has a problem because of tokio runtime.

pub fn send_request(&self, req: Request<Body>) -> Result<String, Error> {
		let task = self.send_request_async(req);
		let mut rt = Builder::new()
			.core_threads(1)
			.build()
			.map_err(|e| ErrorKind::Internal(format!("can't create Tokio runtime, {}", e)))?;
		let res = rt.block_on(task);
		let _ = rt.shutdown_now().wait();
		res
	}

That will work and it is used by mwc713 and by the node.
		let mut rt =
			Runtime::new().map_err(|e| ErrorKind::Internal(format!("can't create Tokio runtime, {}", e)))?;

Need to upderstand why we switched to a single thread.

**Comment by vinayaga07** [comment]
Verified the scenarios and it looks good.


wallet713> 
wallet713> send 0.2 --to http://
Error: could not parse `http://` to a mwcmq address!
wallet713> send 0.2 --to http://0.0.0.0
Starting UTXO scan, 0% complete
Checking 1000 outputs, up to index 795122. (Highest index: 776073), 9% complete
Checking 1000 outputs, up to index 795122. (Highest index: 778076), 19% complete
Checking 1000 outputs, up to index 795122. (Highest index: 780077), 28% complete
Checking 1000 outputs, up to index 795122. (Highest index: 782078), 38% complete
Checking 1000 outputs, up to index 795122. (Highest index: 784085), 47% complete
Checking 1000 outputs, up to index 795122. (Highest index: 786084), 57% complete
Checking 1000 outputs, up to index 795122. (Highest index: 788093), 66% complete
Checking 1000 outputs, up to index 795122. (Highest index: 790094), 76% complete
Checking 1000 outputs, up to index 795122. (Highest index: 792106), 85% complete
Checking 1000 outputs, up to index 795122. (Highest index: 794118), 95% complete
Checking 502 outputs, up to index 795122. (Highest index: 795122), 99% complete
For height: 357354 - 367814 PMMRs: 774070 - 795122 Identified 0 wallet_outputs as belonging to this wallet [], 99% complete
Scanning Complete
Error: Request error: Error code: 404 Not Found; Description: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

wallet713> send 0.2 --to http://12.67.56.78
Error: Request error: Cannot make request: error trying to connect: deadline has elapsed
wallet713> send 0.2 --to http://someaddressthat.not.exist.com
Error: Request error: Cannot make request: error trying to connect: failed to lookup address information: Name or service not known
wallet713>
