### ISSUE TITLE
account to account transfer. Tx confirmation issue 

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#220]
Transfer from account to account  seems like change tx kernel. As a result scan can't validate the transaction, it will be unconfirmed forever.

Here are two possibility to solve:
1. mwc-wallet v3 has self transaction. We might adopt them.
2. kernel might be updated from tx data.  It should have the correct value.

**Comment by cgilliard** [comment]
Have reproduced locally. Let me know if you want any data from my wallet.

**Comment by bayk** [comment]
fix at mwc-wallet only. mwc713 need to be updated. Will do that later
