### ISSUE TITLE
Add 'Use dandelion protocol' for send online and Finalize

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#221]
Both send and finalize  has a confirmation message box. There we can add a checkbox if we want to do fluff instead of dandelion.
Tooltip will say "Dandelion protocol add additional level of anonymization but increase transaction processing time."

QT wallet should keep the last check state. Default is Off

**Comment by bayk** [comment]
Hi @scasaletto , Chris said you want to take it

**Comment by bayk** [comment]
@vinayaga07  @jbyrer   - please check below how you can validate if fluff will work.

About Validation of fluff feature:

1. Setup the mwc-node with Debug level logs.

2. Send or finalize transaction with 'fluff' flag.

3. Check that mwc-node logs have: 

20200427 13:12:31.319 INFO grin_api::handlers::pool_api - Pushing transaction c127e5dd36ab to pool (inputs: 1, outputs: 2, kernels: 1)
20200427 13:12:31.330 DEBUG grin_pool::pool - add_to_pool [txpool]: c127e5dd36ab (PushApi) [in/out/kern: 1/2/1] pool: 0 (at block 06dc054af674)
20200427 13:12:31.332 DEBUG grin_p2p::peer - Send tx kernel hash 63338771b96d to 18.234.103.244:13414
20200427 13:12:31.332 DEBUG grin_p2p::peer - Send tx kernel hash 63338771b96d to 52.41.7.33:13414
20200427 13:12:31.332 DEBUG grin_p2p::peer - Send tx kernel hash 63338771b96d to 188.239.199.52:13414
20200427 13:12:31.332 DEBUG grin_p2p::peer - Send tx kernel hash 63338771b96d to 188.239.199.51:13414

4. Send/finalize without fluff.

5. Check mwc-node logs that transaction went to step pool, not in tx pool
20200427 13:16:07.082 INFO grin_api::handlers::pool_api - Pushing transaction a3e655fbb459 to pool (inputs: 1, outputs: 2, kernels: 1)
20200427 13:16:07.093 DEBUG grin_pool::pool - add_to_pool [stempool]: a3e655fbb459 (PushApi) [in/out/kern: 1/2/1] pool: 0 (at block 0dfb012d87d6)
20200427 13:16:07.093 INFO grin_servers::common::types - DandelionEpoch: relay_peer: new peer chosen: Some(PeerAddr(V4(54.166.67.123:13414)))
20200427 13:16:07.093 DEBUG grin_p2p::peer - Send (stem) tx a3e655fbb459 to 54.166.67.123:13414

**Comment by bayk** [comment]
Hi @scasaletto ,  mwc713 is pushed, now it should support  --fluff flag
Examples:

> send --fluff 0.5 --to xmgEvZ4MCCGMJnRnNXKHBbHmSGWQchNr9uZpY5J1XXnsCFS45fsU
> finalize --fluff --file /tmp/tttt.tx.response

**Comment by jbyrer** [comment]
verified by sending with and w/o fluff, and watching logs
