### ISSUE TITLE
Accounts including amounts from cancelled transactions in balance in some cases

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#227]
These two images are of a qt wallet opened on two different systems. In one there is a cancelled transaction that shows as unconfirmed that is being deposited into the wallet. In the other that transaction is not there. The balance is exactly 893 higher than the other which is the amount of this cancelled transaction. It seems like this amount is being counted even though it doesn't exist. This transaction cannot be cancelled resync with full node does not fix the issue. It might be related to the other account issue #220.

![image](https://user-images.githubusercontent.com/7232183/78049158-8e859e00-732f-11ea-8f64-0279a70648bf.png)

![image](https://user-images.githubusercontent.com/7232183/78049074-7150cf80-732f-11ea-851b-f8f00860634d.png)

**Comment by bayk** [comment]
Yes, it is related to #220
