### ISSUE TITLE
mwc-wallet need to handle Coinbase transactions as Coinbase Outputs

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#230]
We don't want to see Coinbase transactions that are not confirmed.
Such transactions need to be deleted similar to what we do for the orphans CoinBase outputs.
In case of Reorg and reversion back, new transactions will be created every time. 

Reason: Nobody likes current behavior, it is confusing and don't have much benefits.

**Comment by bayk** [comment]
Reopen because we have potential problem with different branch jittering.  Or returning orphan case. As a result coinbase will get duplicate transactions.  
Chances for that is pretty low, but fix still needed.

**Comment by bayk** [comment]
For testing need to simulate the reorg scenario for mining wallet. switch with main branch to attacker and back need to be done at least twice (total 4 switched form branch to branch).
I did such testing by tweaking the code. Tweak just skip outputs, so it looks like a switch to attacker branch for the wallet.
Note, that issue and fix are for mining wallet only. Regular wallet is not affected

**Comment by cgilliard** [comment]
Testing will take more time, but should not block release.
