### ISSUE TITLE
Confusing notice about re-scan - resynced wallet - transactions dissappeared

### ISSUE THREAD

**Issue by mwc-design** [mwcproject/mwc-qt-wallet#231]
STEPS TO RECREATE:
"re-scan" notice showed in wallet
I took that to mean I had to re-sync my node
after re-sync my transactions were gone (or at least I thought they were)
I switched accounts and the came back

* I now realize that the transactions probably never went away, probably the wallet switched me to another account automatically

**Comment by bayk** [comment]
That was a bug similar to that https://github.com/mwcproject/mwc-qt-wallet/issues/240
Fixed now

**Comment by bayk** [comment]
@mwc-design ,  I don't see   "re-scan" notice showed in wallet. As I understand it should be Re-sync.
I did search in qt and mwc wallets. Non if them has scan in meaning of sync
