### ISSUE TITLE
Error message when recovering from seed if bad node saved in config is not the best

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#235]
Steps to reproduce:
Have a working qt wallet and connect it to a custom node (maybe a local node).  Kill the node, and then try to create a NEW wallet from seed.  Error looks like:

![image](https://user-images.githubusercontent.com/10661009/78462482-49db6900-7687-11ea-875e-fd385a8209e8.png)

**Comment by cgilliard** [comment]
Saw similar case with embedded node. To reproduce make embedded node fail. You will get an option to switch to the dev node, but clicking on dev node did not change setting for me.

**Comment by bayk** [comment]
Error will be more descriptive
![image](https://user-images.githubusercontent.com/42393608/78845553-b6bf6d80-79bd-11ea-86a2-21103b1cda52.png)
