### ISSUE TITLE
When creating new wallet (or recovering from seed) previous wallets name is displayed in title

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#239]
OS Versions affected: OSX, Windows, Ubuntu

Steps to reproduce:

1. Create a wallet (let's say we name it W_A).  
2. Exit the wallet
3. Re-start the wallet
4. Create a new wallet (or recover from seed)  and name it something else.
5. The old Name will be displayed.

Expected Behavior: 
The new wallet name should be visible at the top of the wallet

Actual behavior:
The old wallet name is displayed.

**Comment by bayk** [comment]
Hi @scasaletto , seems like it is yours

**Comment by vinayaga07** [comment]
Successfully verified with the latest build -https://ftp.mwc.mw/nightly_builds/04-20-2020/

1. Created a new wallet and not observed the old wallet names, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/79779888-bbd6d200-8358-11ea-8637-0ed07a27df23.png)
