### ISSUE TITLE
Initially only one transaction displayed on transaction tab, but after switching to new account all are shown

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#240]
OS affected: OSX, Windows and linux are unknown

Unfortunately I only see this issue from time to time.  When I open a wallet and click on the transactions tab, only one of the transactions that should be there is (in this case the oldest). If I switch  to another account, then switch back, all transactions show.  I will update this wallet if it happens again, and attempt to save some state.

**Comment by bayk** [comment]
Jim, when it happen, please save qt logs and specify the account name

**Comment by jbyrer** [comment]
[logs.zip](https://github.com/mwcproject/mwc-qt-wallet/files/4441817/logs.zip)
[gui_wallet_32.zip](https://github.com/mwcproject/mwc-qt-wallet/files/4441819/gui_wallet_32.zip)


The account was 'default'  the wallet instance was gui_wallet_32 (wallet folder attached as zip)

**Comment by bayk** [comment]
Update: mwc713 works good.  Seems like we have problems because of wrong transaction count. 
There are two issues on the qt wallet side.
1. Account switch probably was optimized wrongly.
2. Tx are in the cache. Tx count is not needed

**Comment by bayk** [comment]
@scasaletto ,  I cleaned tx  count.  Because of that Transaction Windows manage page position and Page.  Transaction State doesn't manage that, so code is cleaned up. Now tx cache code is smaller because of that.
