### ISSUE TITLE
UX: When clicking "show passphrase" we are brought to login screen for password rather than a pop up dialoge

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#241]
OS affected: All

Steps to reproduce:
1) select "show passphrase" from the accounts drop down (upper right corner)

Behavior: Immediately returned to login screen, with no explanation as to why

Expected behavior: Dialogue similar to what you see when you send coins should be used.

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/78841544-79a1ae00-79b2-11ea-90ad-7e513aaebeac.png)
