### ISSUE TITLE
[mwc-node] Error text when dealing with unexpectedly long waits

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#244]
Summary:
Vinayaga and I noticed that when starting a node for the first time (especially on Floonet I would think) it can take a long time to upload the chain (expected); however, the error message is a bit confusing, and poorly worded.

OS affected: Only Seen on Ubuntu so far, but probably common to OSX as well

Steps to reproduce:
1) Create a new node and start it up.
2) View the logs after some time.

Expected Behavior: Should print an easily readable error, or perhaps no error at all if this is due to the original start up.

Actual behavior:  Below message:

![image](https://user-images.githubusercontent.com/10661009/78808557-712d8100-797a-11ea-9b44-ad87b5e791bf.png)

**Comment by jbyrer** [comment]
The phrasing in question is 

'...has slow CPU or unreasonable long blockchain? Is it a first run and you just get txhashset archive?

One suggestions would be something like:
This error may be caused by:
1)  Running the debug version of this node
2) Having a slow CPU
3) Having an unusually large blockchain.
4) Downloading the entire blockchain (which is expected if this is the first time the node is being run)

**Comment by bayk** [comment]
@jbyrer ,  in logs that must be a single line message. We can't have bullet points.
