### ISSUE TITLE
Pages need to restore the caption(title) after construction

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#245]
QT can change window titles after page construction. Example, usage of tab control. In the past we had that issues because of some different reasons.

Title state need to be restored back with call to  changeTitleBarColor().  
As a result all Pages need to have same parent class that will do something like one shot timer and there make a call to changeTitleBarColor. 

All panels are located at   mwc-qt-wallet/windows .  Parents are QWidget and core::NavWnd=>QWidget.

So they need a new parent that can cover issues like this one.

**Comment by bayk** [comment]
Needed as a first step for logout activity tracking ticket

**Comment by bayk** [comment]
Note: Fix related to MacOS only. We are covering QT bug with this.

Testing:  Check if App title has a normal purple color.  Switch to Settings, check the color. Switch other pages. Title color should be normal with every page.
Sometimes title can blink for a short time. It is expected, nothing what we can do with that.

**Comment by jbyrer** [comment]
went through all pages on osx box, title remained purple throughout.
