### ISSUE TITLE
--min_conf_exclude_change_outputs

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#247]
mwc-wallet has --min_conf which requires a minimum number of confirmations before allowing outputs to be selected by a send. This creates a problem with exchanges that use this to prevent double spend attacks because any withdrawal can then lock up the change output for a long and unnecessary period of time. For instance, if there is an output of 10,000 MWC in the wallet and someone withdraws 10 MWC, the other 9,990 MWC will not be available for other withdrawals for --min_conf confirmations. Some exchanges are setting this value to 5,000+ so it takes a very long time. The solution is to introduce a new parameter --min_conf_exclude_change_outputs. This is a boolean flag. If set, the --min_conf parameter will not apply to change outputs. It will only apply to outputs which were received from another wallet. This feature will also introduce a new parameter called --min_conf_change_outputs. This value specifies the required number of confirmations for change outputs (which is different from --min_conf in the case where --min_conf_exclude_change_outputs is specified). An error is returned if --min_conf_change_outputs is specified and --min_conf_exclude_change_outputs is not. The default value for --min_conf_change_outputs is 1.

**Comment by bayk** [comment]
This issue cover all commands that are using   --min_conf argument. Similar modification need to be done for the waller Rest API. 
Also 'outputs'  need to have a feature to mark change outputs, so it will be possible to validate the wallet results.

**Comment by bayk** [comment]
min_conf_exclude_change_outputs is redundant.   If minimum_confirmations_change_outputs is set, then for change outputs will be used different confirmation number. If not set, there will be used min_conf parameter
