### ISSUE TITLE
Embedded node sync block by block issue

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#249]
Use case:
qt wallet with embedded node started after about 1 day delay.
embedded node will be 1400 blocks away and it will start syncing block by block.  
QT wallet doesn't recognize that as a good effort form the node and shout it down after 5 minutes of waiting time.

Here are the logs from the wallet that show node activity and next the restart.
16.04.2020 22:51:26.586 MwcNode mwc node status: connections=5 height=224926
16.04.2020 22:51:27.006 mwc-node>> 20200416 22:51:27.006 INFO grin_servers::common::hooks - Received block header 000131750990 at 224927 from 3.229.174.169:3414, going to process.
16.04.2020 22:51:27.006 mwc-node-Event> RECEIVE_BLOCK_LISTEN [header 000131750990 at 224927 from 3.229.174.169:3414, going to process.]
16.04.2020 22:51:27.171 mwc-node>> 20200416 22:51:27.171 INFO grin_servers::common::hooks - Received block 000131750990 at 224927 from 3.229.174.169:3414 [in/out/kern: 0/1/1] going to process.
16.04.2020 22:51:27.172 mwc-node-Event> RECEIVE_BLOCK_LISTEN [000131750990 at 224927 from 3.229.174.169:3414 [in/out/kern: 0/1/1] going to process.]

P.S.  Issue   RECEIVE_BLOCK_LISTEN  is generated for the header. Need to check if it is expected

**Comment by bayk** [comment]
I can't reproduce the original issue. Log messages are correct and that accounted as node activity. 
So everything looks good, but it doesn't explain why originally node was restarted every 5 minutes. Please double check if it works as expected.

**Comment by cgilliard** [comment]
Closing as this is not reproducible right now.
