### ISSUE TITLE
if you set max_outputs to 2 on init_send_tx you get a panic

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#253]
thread 'RunHandlerInThread' panicked at 'assertion failed: size != 0': /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/macros/mod.rs:10   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: grin_util::logger::send_panic_to_log::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic
   7: grin_wallet_libwallet::internal::selection::select_coins
   8: grin_wallet_libwallet::internal::selection::select_coins_and_fee
   9: grin_wallet_libwallet::internal::selection::build_send_tx
  10: grin_wallet_libwallet::internal::tx::add_inputs_to_slate
  11: grin_wallet_api::owner::Owner<L,C,K>::init_send_tx
  12: <grin_wallet_api::owner::Owner<L,C,K> as grin_wallet_api::owner_rpc::OwnerRpc>::init_send_tx
  13: <dyn grin_wallet_api::owner_rpc::OwnerRpc as easy_jsonrpc_mw::Handler>::handle
  14: easy_jsonrpc_mw::handle_call
  15: easy_jsonrpc_mw::handle_parsed_request
  16: easy_jsonrpc_mw::Handler::handle_request
  17: std::sys_common::backtrace::__rust_begin_short_backtrace
  18: std::panicking::try::do_call
  19: __rust_maybe_catch_panic
  20: core::ops::function::FnOnce::call_once{{vtable.shim}}
  21: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  22: std::sys::unix::thread::Thread::new::thread_start
  23: AssociationsManager::_map
  24: AssociationsManager::_map

Should return error message instead.

**Comment by bayk** [comment]
Currently slate limit mwc-wallet handle correctly.  If transaction too large you should see an error "Unable to create send slate , Slate inputs and outputs number is more then 500. Please reduce number of outputs or reduce sending amount"
send --selection all  works correctly as well. It will select maximum number of inputs

**Comment by bayk** [comment]
Fixed, test case is added
