### ISSUE TITLE
[mwc-qt-wallet] App is getting logout, after changing Settings.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#254]
OS Versions Tested: OSX
Build - https://ftp.mwc.mw/nightly_builds/04-20-2020/

Steps to reproduce:

1. Create a mwc-qt-wallet 
2. Login the wallet
3. Goto Setting--> Wallet Configuration --> Wallet
4. Change the settings example auto-logout options to 3 minutes, 
5. Click Reset Button
6. Click Apply Button

Expected Behavior:
The new wallet settings to be saved successfully.

Actual behavior:
The App is getting logged out and new Settings are not getting saved.

**Comment by vinayaga07** [comment]
Please refer the attached screenshot for your references.

![image](https://user-images.githubusercontent.com/63310656/79782711-2427b280-835d-11ea-8cb6-7141dccbdf0f.png)

**Comment by bayk** [comment]
@sarawut11 , please take a look

**Comment by sarawut11** [comment]
got it, let me check

**Comment by sarawut11** [comment]
good catch 👍 , it only happens from the newly created wallet and first time.
Let me investigate it. Btw, new settings are saved, just it is logged out.

**Comment by vinayaga07** [comment]
Able to re-produce the issue with the latest build. Hence re-opening the ticket.

**Steps to be followed**

1. Login the wallet
2. Goto Setting--> Wallet Configuration --> Wallet
3. Change the settings example auto-logout options to 3 minutes,
4. Click Reset Button
5. Click Apply Button

**Expected Behavior:**
The new wallet settings to be saved successfully.

**Actual behavior:**
The App is getting logged out and new Settings are not getting saved.

![image](https://user-images.githubusercontent.com/63310656/82235247-165f5000-9950-11ea-995a-02de68e2123f.png)

**Comment by bayk** [comment]
The root problem is:  https://github.com/mwcproject/mwc-qt-wallet/issues/333
Currently this ticket is duplicate of that

**Comment by bayk** [comment]
#333 is fixed. Now app should meed Vinayaga expectations

**Comment by vinayaga07** [comment]
@bayk , Able to reproduce the issue with the latest build, hence reopening this ticket.

![image](https://user-images.githubusercontent.com/63310656/82683606-eb863c00-9c6e-11ea-988c-885abc6ecb3e.png)

**Comment by bayk** [comment]
Hi @vinayaga07 , Reset change ALL settings, not only that on the current page.
And probably because fo that wallet want to relogin. 

Here is a valid test case

Login the wallet
Goto Setting--> Wallet Configuration --> Wallet
Click Reset Button
Click Apply Button
Here it is fine if wallet will relogin
Goto Setting--> Wallet Configuration --> Wallet
Change the settings example auto-logout options to 3 minutes,
Click Reset Button
Click Apply Button

**Comment by vinayaga07** [comment]
Here tried two scenarios and observed re-login in both the cases
Scenario -1
-------------
Login the wallet
Goto Setting--> Wallet Configuration --> Wallet
Click Reset Button
Click Apply Button

Result: Wallet logout and User need to Re-login

Scenario -2
-------------
Goto Setting--> Wallet Configuration --> Wallet
Change the settings example auto-logout options to 3 minutes,
Click Reset Button
Click Apply Button

Result: Wallet logout and User need to Re-login

For example, if I login to wallet "Test_2"  and clicked Reset & Apply buttons, log out happened and re-login page appears for the default wallet "gui_wallet713_data".  Atleast re-login page should appear for the same wallet "Test_2".

**Comment by bayk** [comment]
The issue that "reset" changing wallet folder. 
We are going to changes that. Currently it is not needed

**Comment by vinayaga07** [comment]
Tested with the latest build - https://ftp.mwc.mw/nightly_builds/05-26-2020/

 I login to wallet "Test_3" and clicked Reset & Apply buttons, log out happened and re-login page appears for the wallet "Test_3". Hence closing this ticket.
