### ISSUE TITLE
Display notes for transactions and outputs on their respective screens.

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#255]
Now that support for notes has been added for outputs and transactions, the one last thing to do is see if it would be possible to display the notes in a nice way on the Transactions or Outputs screens.

See https://github.com/mwcproject/mwc-qt-wallet/issues/214
and https://github.com/mwcproject/mwc-qt-wallet/issues/187

**Comment by bayk** [comment]
Fixed with different ticket
