### ISSUE TITLE
mwc-wallet, mwcmqs,  printing messages for the user

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#256]
Currently mwcmqs code printing  on the console  bunch of messages. That was fine for mwc713.
For mwc-wallet  they need to go into the logs.
Problem that the same code should work with mwc713 and in mwc-wallet.  

Normally we shouldn't have println calls.

Example of how this problem is solved is StatusMessage  at 
mwc-wallet/libwallet/src/api_impl/owner_updater.rs

Search for 'status_send_channel: &Option<Sender<StatusMessage>>,'
To see the usage.

There are 
start_updater_log_thread   - will write those message into the logs (mwc-wallet case)
start_updater_console_thread - will write those message to the console (mwc713 case)

You can extend it for mqs messages.

**Comment by yyangli** [comment]
commit 1551bd8f6c875bc09ba960dcb2756fbb43a800f0 (HEAD -> master, origin/master, origin/HEAD)
Author: Yang Li <liya@vmware.com>
Date:   Sun Apr 26 21:56:27 2020 -0700

    github issue #256 mwc-wallet, mwcmqs, printing messages for the user

**Comment by yyangli** [comment]
To verify, just check  messages are printed to log file mwc-wallet.log, not write to console directly. But console still shows some important message(warn messages).

**Comment by bayk** [comment]
Great, console is expecting to print logs as well. mwc-wallet toml has
settings about that.

**Comment by vinayaga07** [comment]
Verified in MWC wallet, log messages are printed in the mwc-wallet.log file, hence closing this ticket.


![image](https://user-images.githubusercontent.com/63310656/80516207-c15b9a00-89a0-11ea-9ebd-d27ccf55e8b5.png)
