### ISSUE TITLE
mwc713, mwcmqs cleaning the code, switch to mwc-wallet varsion

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#257]
Since TxProof  and mwcmqs code is moved to the mwc-wallet,  we can delete it from mwc713 and switch to the new version.

**Comment by jbyrer** [comment]
We have done a good deal of regression testing for this, and will continue to test until the next release, but for now I am closing this issue as no new bugs related to this change have been found.
