### ISSUE TITLE
Add  MWC  MQS config

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#258]
For mwc mqs configuration we need to add config, like it is done for TorConfig. With all default values, e.t.c.
Config should have   mwc_domain  and mwc server port

Note, Index for address doesn't belong to MQS, that will be separate ticket for that.

Currently all configs are located at:
mwc-wallet/config/src/types.rs

Currently those settings are hardcoded at 
File: /ntroller/src/controller.rs
Method: start_mwcmqs_listener

**Comment by yyangli** [comment]
commit 742f4a8ed523d1fdbee4135c05c3f5899f559feb (HEAD -> master, origin/master, origin/HEAD)
Author: Yang Li <liya@vmware.com>
Date:   Wed Apr 22 17:58:37 2020 -0700

    https://github.com/mwcproject/mwc-qt-wallet/issues/258
    create MQSConfig silimar to TorConfig and update test file accordingly

**Comment by cgilliard** [comment]
Jim confirmed this as part of the other mqs testing.
