### ISSUE TITLE
Apply TxProof to all protocols at mwc-wallet, embed it into the slates proof

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#259]
Currently mwc-wallet has proofs into the slates. 
We want to have TxProof functionality for all communication protocols and slate.  
In this case proof file will be generated for all send methods, not for  mqs only.

Also mwc-wallet  using 'address' for that purpose. We need to switch the the same one.  
See   mwc-wallet/libwallet/src/proof/proofaddress.rs,  ProvableAddress

**Comment by bayk** [comment]
mwc-wallet  rebase, v3.2.0  has commands for 'export_proof', 'verify_proof' and they are disabled.
Reason:  we need TxProof functionality to be there.

**Comment by bayk** [comment]
Tests for  'export_proof', 'verify_proof' are disabled at 
mwc-wallet/api/src/owner_rpc_s.rs
Search for no_run
Currently test framework for proofs is broken, it can't even to generate transaction with proof.
Issue happens when I apply address related changes. I guess it is expected until we switch add addresses to the same engine.

**Comment by yyangli** [comment]
for testing tor proof:
start two mwc713 wallets , use "listen -t" to start tor for them and do sending.
proof file will be generated in wallet_data folder
proof file can be verified by verify-proof command in mwc713

**Comment by vinayaga07** [comment]
Tried sending from MWC wallet and given below the observations,

1. Proofs are not getting generated.
2. Transactions are not getting completed.



<----------Error Snip--------->
20200731 22:28:27.134 WARN grin_wallet_impls::adapters::http - Starting TOR Process for send at Some(V4(127.0.0.1:9051))
Wallet command failed: LibWallet Error, Payment Proof generation error: Invalid proof signature, signature error

**Comment by vinayaga07** [comment]
In MWC713 wallet, got the below error message,

wallet713> send 0.002 --to http://pmeovjkr4s6vgrajwyn7n7ycrtubb656rm3imzetoye5i36fwer6caad.onion/ --proof
Error: Adapter Callback Error, Performing version check (is recipient listening?): Request error: Cannot make request: error trying to connect: tcp connect error: Connection refused (os error 61)
wallet713>

**Comment by vinayaga07** [comment]
Tried from **MWC wallet** and able to send MWC with proofs.

mwc-wallet  send -c 1 -d http://pmeovjkr4s6vgrajwyn7n7ycrtubb656rm3imzetoye5i36fwer6caad.onion  .0002 --proof
Password: 
20200805 22:46:07.978 WARN grin_wallet_impls::adapters::http - Starting TOR Process for send at Some(V4(127.0.0.1:9051))
slate [85a7f707-04fe-4f42-bfd0-ba4329de04df] finalized successfully
Command 'send' completed successfully

**Comment by vinayaga07** [comment]
Able send from MWC713 wallet, hence closing this ticket.

wallet713> send 0.002 --to http://pmeovjkr4s6vgrajwyn7n7ycrtubb656rm3imzetoye5i36fwer6caad.onion --proof
Starting UTXO scan, 0% complete
Checking 65 outputs, up to index 1083502. (Highest index: 1083502), 99% complete
For height: 510099 - 510163 PMMRs: 1083371 - 1083502 Identified 0 wallet_outputs as belonging to this wallet [], 99% complete
Scanning Complete
Transaction [2a7efa76-6545-48e5-8040-570f2a0cb584] for [0.002000000] MWCs sent successfully to [http://pmeovjkr4s6vgrajwyn7n7ycrtubb656rm3imzetoye5i36fwer6caad.onion]
wallet713> txid=2
