### ISSUE TITLE
[UX] [mwc-qt-wallet] The warning displayed when Foreign API is enabled in an insecure fashion should be worded more clearly.

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#261]
OS found on: OSX
Below is an image of the warning:

![image](https://user-images.githubusercontent.com/10661009/79915836-91c6f380-83dc-11ea-9f57-ee150405dd81.png)

This is another similar wording issue we can fix (caused by the same issues)

![image](https://user-images.githubusercontent.com/10661009/79916159-1a459400-83dd-11ea-972b-9bd7c5f4c13f.png)

I will add more on to this bug as I investigate further.

**Comment by cgilliard** [comment]
Actually thinking we should remove this. I think http is a variable option
in some cases, like possibly private networks or if you are not that
concerned about privacy.

**Comment by jbyrer** [comment]
After discussion, it has been recommended that we remove the first warning (see the first image) completely.  In addition, for the warning in the second image, instead of "WARNING: ...." we should say either "HTTP enabled" or "HTTPS enabled".  And the second WArning about "Authorization with api secret is disabled" can just be removed

**Comment by bayk** [comment]
With additional discussion we decided to keep 
![image](https://user-images.githubusercontent.com/42393608/80004421-241bd580-8477-11ea-8209-49a0ecea7230.png)
The dialog will be moved to the settings and shown once when user pressing OK button.

**Comment by jbyrer** [comment]
assigned to K, feel free to reassign.  I set this as a low priority.

**Comment by cgilliard** [comment]
Confirmed fixed.
