### ISSUE TITLE
Windows LMDB out of disk space error

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#265]
On mwc-wallet Azure build, after updating some libraries, LMDB frequently runs out of space on the Azure tests. need to investigate why this is happening. When running locally the tests appear to pass on Windows.

**Comment by yyangli** [comment]
@bayk We haven't run into this for a while. Maybe we should close this now?

**Comment by bayk** [comment]
@yyangli   Windows tests are disabled.  We should fix it and enable the tests. Let's keep it.

**Comment by bayk** [comment]
The rood problem is how rust tests are implemented and Windows FS works.  Because of rust tests a lot of resources are leaking and Windows just can't handle that. It doesn't make sense to change bunch of code because of that. I disable tests that spaws bunch of processes and never end them
