### ISSUE TITLE
Cleanup Transactions and Outputs Dialogs

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#268]
Brent has made several suggestions for improvements which can be made to the Transactions and Outputs Dialogs. See the first item in his google doc at: https://docs.google.com/document/d/1p12FnhtsjQpOuHcYnmDVWwOceT5K-j1nre68hZz8tjU/edit#heading=h.1tefyviwglrn

The main issue is that fields which are read-only should not have outlines around them or change when the mouse hovers, or clicks on them.

I have also noticed a couple of other issues in these dialogs.
1. All fields can be tabbed through.
2. Transaction Kernel View button has a copy and paste error and refers to outputs instead of kernel.
3. In the Transactions Dialog, the Type field cuts off types which have been cancelled because the field isn't large enough.
4. In the Transactions Dialog, the tool tip for the Inputs/Outputs combo box refers to accounts. (Copy and paste error.)

**Comment by jbyrer** [comment]
Fixed:
I have verified the padding (although it is hard to tell), and the transactions screen.

Problems?: 
The "All" button functionality on the send tab has not been updated according to the document, is that on purpose?

The air drop button has not been moved to the bottom of the tabs as suggested.

Not sure:
I can't tell if the small buttons have been updated according to the documents, but it doesn't look like it has.

I'm not sure what the explorer bar looked like before, it seems to match the picture from the design doc now.
