### ISSUE TITLE
Typo on initial screen

### ISSUE THREAD

**Issue by SpectacularVernacular** [mwcproject/mwc-qt-wallet#269]
The hover tooltip states "Rin as online MWC Node". It should state "Run as ...".
![mimblewimble-tooltip-typo](https://user-images.githubusercontent.com/64418634/80377742-4770c700-8861-11ea-85d7-4540c7e8b343.png)

Edit: This is on line 486 of file /mwc-qt-wallet/windows/a_initaccount.ui link: https://github.com/mwcproject/mwc-qt-wallet/blob/c94480012320970b70465c7c284ea367a30950c0/windows/a_initaccount.ui#L486

**Comment by bayk** [comment]
It is already fixed in master branch.
