### ISSUE TITLE
Radio buttons don't work under the Linux and Windows

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#27]

**Comment by bayk** [comment]
Linux. Provision new wallet. No radio buttons are shown

**Comment by cgilliard** [comment]
This seems true on windows as well.

**Comment by bayk** [comment]
For Linux, not high definition we still need to declare the scale factor not equal to 1.
export QT_SCALE_FACTOR = 1.0001  
will fix this issue.
Another alternative is using different approach with styles

QRadioButton::indicator {
    width:                  15px;
    height:                 15px;
    border-radius:          ??px;
}

QRadioButton::indicator:checked {
    background-color:       XXXXX
    border:                 1px solid white;
}

QRadioButton::indicator:unchecked {
    background-color:       XXXX
    border:                 1px solid white;
}

But result will be different form what we have now. 
Also the same is applicable for dialogs.

**Comment by bayk** [comment]
Chris, please update non high res Linux package with QT_SCALE_FACTOR = 1.0001

**Comment by bayk** [comment]
Should be fixed for Linux. Windows is to go, it has the same issue

**Comment by bayk** [comment]
Let's keep "Platform testing" for that
