### ISSUE TITLE
HODL API getHODLStatus should be able to block all HODL activity

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#270]
Needed for maintains. If getHODLStatus doesn't success, all other API call results must be ignored.

**Comment by bayk** [comment]
Test scenario:
0. Work with QT wallet normally. Check if HODL account works well, there are output in HODL, send shows warnings, e.t.c.

1. Ask Chris to switch HODL server into maintenance mode.
2. Clean up qt wallet logs
3. Start QT wallet. Check UI, HODL pages should show that HODL under maintenance. No claims info should be shown.
4. Check Output page. Verify that you HAVE outputs in the HODL (info should come form cache). Send should show the warnings about that.
5. Validate logs. Check that for HODL we call only 'getHODLStatus'

cat  mwcwallet.log | grep seed2.mwc.mw
airdropUrlTestNetUrl=https://seed2.mwc.mw:8443
29.04.2020 12:44:32.182 Airdrop Requesting: https://seed2.mwc.mw:8443/v1/claimsAvailable
29.04.2020 12:44:32.183 HODL Requesting: https://seed2.mwc.mw:8443/v1/getHODLStatus
29.04.2020 12:44:32.547 Airdrop Fail respond for Tag: airdrop_claimsAvailable  requestErrorMessage: Error transferring https://seed2.mwc.mw:8443/v1/claimsAvailable - server replied: Not Found
29.04.2020 12:44:36.102 HODL Requesting: https://seed2.mwc.mw:8443/v1/getHODLStatus
29.04.2020 12:44:46.927 HODL Requesting: https://seed2.mwc.mw:8443/v1/getHODLStatus
29.04.2020 12:44:47.898 HODL Requesting: https://seed2.mwc.mw:8443/v1/getHODLStatus

Note claimsAvailable - it is Airdrop API and it is expected to call.

6. Ask Chris  switch HODL server into normal mode.
7. Revisit HODL page and see that everything is back to normal

**Comment by cgilliard** [comment]
Worked with Jim on this and confirmed everything worked for maintenance mode.
