### ISSUE TITLE
Wallet unable to work reliable on non reliable network

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#272]
Example: today floonet is slow and wallet restore doesn't work because one of calls to the node failed. 
mwc-wallet http client should have retry logic to handle such cases.

**Comment by bayk** [comment]
Use case (the goal):  run scan, turn off network for a short time. Turn on the network. Wallet should be fine and be able to continue

**Comment by bayk** [comment]
Testing:
1.  Just run any operation and play with a network.  wallet should withstand 10 seconds network interruption. Note, fix is related for wallet to node connection. If you found that another components doesn't handle that well - create separate ticket for them.


2. Original issue was about Full resync with a node.  Please try:
a. Run 1 wallet and do full resync. During that time play with a network. It will slowdown the process but it shouldn't fail.
b. Run few instances of the wallets on floonet (qt of mwc713 are fine). All wallets connected to the cloud node. Now start full resync for all of them.  Find what is the max number of the wallets can do that. Before 5 was guarantee to fail.

**Comment by jbyrer** [comment]
Tested as per Konstantin's instructions, all steps passed.
