### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#274]
User reported that when running full node on Ubuntu 20.04 that there was a libncurses error:

./Downloads/mwc/node/mwc/mwc: error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory

**Comment by bayk** [comment]
Chris, it is documentation issue.  We can't ship that package. Probably we can try validate if all dependency are installed. Let's keep this ticket for validation.
