### ISSUE TITLE
UX fix the verbiage when viewing a HODL outputs

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#279]
I'm not sure if this applies to other OS and UX paths
Steps to reproduce: 
OS: OSX
On an mwc-qt-wallet in online node, register a cold wallet's rpk and select "view outputs"

![image](https://user-images.githubusercontent.com/10661009/80740971-bd796600-8acd-11ea-8539-39fc4f235c66.png)

Should probably read:
Outputs that **were** discovered by HODL server during last scan:

**Comment by cgilliard** [comment]
Fixed.

**Comment by vinayaga07** [comment]
Currently unable to verify HODL with the latest QT wallet build.

Unable to communicate with https://seed2.mwc.mw:8443.
Get communication error: hodl_getChallenge Error transferring https://seed2.mwc.mw:8443/v1/getHODLChallenge?root_pub_key=03785f7a64d4d6fdae90258fb2390520a3e2f6bf73f7a6546773430e1ec94141f2 - server replied: Bad Gateway

Closing this ticket, as per the cgillard's fix.
