### ISSUE TITLE
Sending to yourself through http results in API error: timeout and transaction fails to confirm

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#283]
wallet713> send --to http://127.0.0.1:13415 0.7
slate [c79527d1-6ab2-4b86-a41d-d39c76eccd98] received from [http(s) listener] for [0.700000000] MWCs.
wallet713> 
Error: API Request error: Cannot make request: connection error: timed out

Steps to reproduce:

1.) Start foreign API.
2.) Send funds to your own foreign API address.

Result:

time out error will occur and the received transaction will never be confirmed. Sent transaction is never entered into the txlog.

Expected behaviour:

no time out error and send is successfully finalized.

**Comment by bayk** [comment]
We can't fix that case. Wallet is locked during send call.  If user need to send to himself, there is method 'self'
