### ISSUE TITLE
Accounts transfer feature parity with Send.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#285]
Here is a recording.

https://cdn.discordapp.com/attachments/576430272514359327/706509113634455612/zoom_0.mp4

Accounts transfer has some minor issues

1. Need to check if node is healthy, like we do for the send. That issue might be because of that.
2. Ask for password during the send.
3. Add fluff option like send has.

**Comment by bayk** [comment]
# 1 still need to be done.
#2 & #3 are ready

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
