### ISSUE TITLE
Cancel button on HODL Claim window takes you to the claims screen (does not cancel)

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#290]
<img width="726" alt="Screen Shot 2020-05-06 at 9 59 43 AM" src="https://user-images.githubusercontent.com/7232183/81206074-69b0c600-8f80-11ea-9645-ca2c14bbbd87.png">

It's not a major issue because it just takes you to the next page, but would expect you to stay on the same page instead.

**Comment by vinayaga07** [comment]
Verified the behavior in the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/84801467-d8238200-b01c-11ea-9236-188612e84054.png)
