### ISSUE TITLE
QT Wallet got locked, while trying Recovery wallet option by providing invalid passphrase

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#291]
**Description:**
Tried to Recover the qt-wallet by providing invalid passphrase and wallet got locked and unable to login to any of the existing wallet.

**Steps to be followed**
1. Open QT-Wallet
2.  Click ""Wallet Instance"" button and then ""Select"" Button, create a new Folder.
3.  Provide Passwords for the wallet and click ""Create"" button.
4.  In the ""Initialize your wallet"" page,  select ""**Recover wallet from passphrase"**" and MWC network as ""Floornet"".
5. click Submit button
6. Provide invalid passphrase and then click submit button"

![image](https://user-images.githubusercontent.com/63310656/81207057-9ac5e080-8fea-11ea-895e-5ad10eb47141.png)

**Testbed Details**
OS: Mac OS
Wallet Type: QT-Wallet
Wallet Build: v1.0.17

**Comment by cgilliard** [comment]
Tried this, but was not able to reproduce. After inputing an invalid passphrase, the wallet will close , but after opening the wallet, I was able to login to all my other instances that already had been created. Maybe I did something differently?

**Comment by bayk** [comment]
Seems like the issue is a lock screen. It shouldn't be here

**Comment by bayk** [comment]
There was locking time "never". And there is a chance that this wallet might not have a password because seed wasn't restored well.

**Comment by scasaletto** [comment]
For me, because the wallet wasn't restored I was brought back to the screen to enter a password and then confirm it and then create a new wallet instance or choose a different wallet instance. Choosing a different wallet instance allowed me to properly use that instance.

**Comment by bayk** [comment]
Yes, wallet should be at input password screen, not at the lock screen.

**Comment by bayk** [comment]
Here is a likely that this issue related to "Never" lock timeout

**Comment by cgilliard** [comment]
deleting this line:
logoutTimeout = -1 in
~/mwc-qt-wallet/mwc-gui-wallet-v3.conf
resolves the issue. User's should not use logout "never" in this release.

**Comment by sarawut11** [comment]
It is fixed by following PRs.
https://github.com/mwcproject/mwc-qt-wallet/pull/293
https://github.com/mwcproject/mwc-qt-wallet/pull/294

**Comment by vinayaga07** [comment]
Tested with the latest build and able to login & logout, even after lock timeout was set as "Never".

![image](https://user-images.githubusercontent.com/63310656/81319587-84348d80-90ad-11ea-81f1-6f58625d1a38.png)
