### ISSUE TITLE
QT wallet doesn't store Node Connection type by Running mode

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#292]
Currently Node connection is part of config file. As a result, when we change wallet running mode, config can point to last valid state. 
Example:   
1. Start as Online wallet with Cloud node connection
2. Switch to Cold Wallet mode
3. Switch to Online wallet mode.
 Now Online wallet has Embedded node connection instead of "Cloud"

Reason:  at #2  Embedded node is the only valid mode, so config was updated. At #3  it wsa never restored because we don't store this data by running mode.

**Comment by bayk** [comment]
Should be fixed with another tickets. Currently connections are stored separately for every running mode.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
