### ISSUE TITLE
Dialog saying mwc713 is taking too long to shutdown

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#295]
When closing qt-wallet, a dialog always pops up saying mwc713 is taking too long to shut down.

**Comment by bayk** [comment]
This problem is related to mwc713.  mwc713 is not able to process 'exit' if run from qt wallet. 
If run mwc713 manually it looks fine

**Comment by vinayaga07** [comment]
@bayk , what is the fix went in ?

**Comment by vinayaga07** [comment]
Logout from QT wallet happened very quickly and unable to find a message that Operation takes too much time.

**Comment by bayk** [comment]
We had problem with exit, not a logout.
You can close qt wallet and see that you don't see any error messages

**Comment by vinayaga07** [comment]
While closing QT-wallet, not observed any error messages, hence closing this ticket.
