### ISSUE TITLE
mwc-wallet should expect Outputs as node send them

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#298]
Here is a logs:

20200507 17:02:38.265 ERROR grin_wallet_impls::node_clients::http - Unexpected error in returned output (missing block height): Commitment(09b148a1fdf7ca51e302ed4a6fce2857c4122db4214c7258faf0b36e493e5155f0). OutputPrintable { output_type: Transaction, commit: Commitment(09b148a1fdf7ca51e302ed4a6fce2857c4122db4214c7258faf0b36e493e5155f0), spent: true, proof: Some("485804eddd99b8a068b82f71889b54ba325fb32d635fd237b66c3c8a6b8f2a712cedc200cc810be2594c36e22248832468f22fd4171b13d3fee637671a8d296303ecd48539fbb39dcffc42d922674f20753df7667166cb8bc145222495fd51ec56481521cd3e1b61bee9085493f21adb934081a46b9a4a270d1ebe572ca3e0acc66fef4f5c4a43e6c0c8cb7aa6fd8f3e2fca5e32b1c9c3f2368aa7a9191843cf7505749852d442cc3597e23d596b6817699ec6cbcbad08b37506544e1c904517faf2f98e3dd1a524303622319a9c43029ae0fa9a6cd68c1fd518317dc948918f293adca45e8ec50c3eac7beffdee9ce085f20bb0ac99306d18be4021bba2335310152a4dfa686e1472ade8f0b44f9814c61434cde70dcef90794b45b57e8941a063f307b169168a2e43b3a5a2a01819fa24f887bc352f5f72c2a5c6318953efb711b791a28cc483ef52f83898224164f234df92e597e95fd4fb12888850ea38e76d602d8f660a83905f557f50ee2dbc3cab505b388bcde011b2c736f46c7999caa5db09fa68c1b9e43b37bddf1869669cb41e41d8ab2a21ff71980ef0798bddd3277ff761e11755d70f7ffef5e6154a2e7df27f5feedb73008e0ac6c49ddd7b0c6855fa41ec00c676d03ee72d291752cf9d22f6e07a18d9ffe8a7b88f910d5e9130f62ae517085bb7ae5649447adb71995940480118b2abeed9baf2f25414b6b2a045e517311fce43e03464c01fd1a090052cb453eb6dd37282a5d91947825f50416ed557a90319fe09148084dc7c4426efc202f527a3da746faf93f1e0dcffcb3fdb73bda7229ab237eb93bac78ef41aed93c567172fc09f00b04f72086c9d182471c54d19b6c451a4bc4d89627aba47476781e07a3d00dd428c186ad1e21d069a314a1f03af7c01ffed0dd4bc7605715f4e6eee8651270b21b85d14461474c4e65b6"), proof_hash: "bcc2308786651f59cc0432e13ac944da33f053aecb55504bbe59a1eb20b379df", block_height: None, merkle_proof: None, mmr_index: 0 }, http://localhost:3413/v1/txhashset/outputs?start_index=844619&max=1000&end_index=851969
Wallet command failed: LibWallet Error, Client Callback Error, Unexpected error in returned output (missing block height): Commitment(09b148a1fdf7ca51e302ed4a6fce2857c4122db4214c7258faf0b36e493e5155f0). OutputPrintable { output_type: Transaction, commit: Commitment(09b148a1fdf7ca51e302ed4a6fce2857c4122db4214c7258faf0b36e493e5155f0), spent: true, proof: Some("485804eddd99b8a068b82f71889b54ba325fb32d635fd237b66c3c8a6b8f2a712cedc200cc810be2594c36e22248832468f22fd4171b13d3fee637671a8d296303ecd48539fbb39dcffc42d922674f20753df7667166cb8bc145222495fd51ec56481521cd3e1b61bee9085493f21adb934081a46b9a4a270d1ebe572ca3e0acc66fef4f5c4a43e6c0c8cb7aa6fd8f3e2fca5e32b1c9c3f2368aa7a9191843cf7505749852d442cc3597e23d596b6817699ec6cbcbad08b37506544e1c904517faf2f98e3dd1a524303622319a9c43029ae0fa9a6cd68c1fd518317dc948918f293adca45e8ec50c3eac7beffdee9ce085f20bb0ac99306d18be4021bba2335310152a4dfa686e1472ade8f0b44f9814c61434cde70dcef90794b45b57e8941a063f307b169168a2e43b3a5a2a01819fa24f887bc352f5f72c2a5c6318953efb711b791a28cc483ef52f83898224164f234df92e597e95fd4fb12888850ea38e76d602d8f660a83905f557f50ee2dbc3cab505b388bcde011b2c736f46c7999caa5db09fa68c1b9e43b37bddf1869669cb41e41d8ab2a21ff71980ef0798bddd3277ff761e11755d70f7ffef5e6154a2e7df27f5feedb73008e0ac6c49ddd7b0c6855fa41ec00c676d03ee72d291752cf9d22f6e07a18d9ffe8a7b88f910d5e9130f62ae517085bb7ae5649447adb71995940480118b2abeed9baf2f25414b6b2a045e517311fce43e03464c01fd1a090052cb453eb6dd37282a5d91947825f50416ed557a90319fe09148084dc7c4426efc202f527a3da746faf93f1e0dcffcb3fdb73bda7229ab237eb93bac78ef41aed93c567172fc09f00b04f72086c9d182471c54d19b6c451a4bc4d89627aba47476781e07a3d00dd428c186ad1e21d069a314a1f03af7c01ffed0dd4bc7605715f4e6eee8651270b21b85d14461474c4e65b6"), proof_hash: "bcc2308786651f59cc0432e13ac944da33f053aecb55504bbe59a1eb20b379df", block_height: None, merkle_proof: None, mmr_index: 0 }, http://localhost:3413/v1/txhashset/outputs?start_index=844619&max=1000&end_index=85196

**Comment by bayk** [comment]
Reproduce steps:
Wallet1:  mwc-wallet 
Wallet2: mwc713 or QT wallet wallet with the same seed (cloned wallet)

1. Make sure that Unspend transactions near the tip. You can create a new wallet and send few transactions to it. So all outputs will have height near the tip.
2. Send coins with Wallet2, so all those outputs will be spent.
3. Wait for confirmation, one block if enough.
4. Check balance with mwc-wallet. mwc-wallet should rediscover spent outputs, change. No 'Unexpected error in returned output' errors are expected.

**Comment by jbyrer** [comment]
1) Created a new qt wallet
2) Sent coins to new QT. 
3) made a clone wallet using mwc-wallet.  
4) Confirmed outputs the same.  
5) Sent back coins and confirmed all old outputs removed and new outputs 
6) Waited until just after confirmation
7) confirmed outputs changed in cloned mwc-wallet.
8) Scanned logs for errors or exceptions an  found none, also saw no errors in console.
