### ISSUE TITLE
Improvements to smaller buttons in Transactions screen

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#299]
From Brent:
OLD buttons have 2px border which looks good for big buttons but too thick for small buttons, change to half that (1px) I’m assuming you set them up in pixels.
Make the font size slightly smaller as well, it’s the same text size as the big buttons, should be a bit smaller, maybe send me a screenshot after you fix so I can confirm the size is good.
![Buttons](https://user-images.githubusercontent.com/7772099/81412531-9e03be00-9109-11ea-9c8f-c8190a307944.png)

**Comment by scasaletto** [comment]
Updated MwcPushButtonSmall to use a 1px border. Then updated the Validate Proof File and Export .CSV buttons in the Transactions screen to use MwcPushButtonSmall instead of MwcPushButtonNormal.

**Comment by vinayaga07** [comment]
@Brent: Here is the screenshot from the latest build, Please confirm the expected result.

![image](https://user-images.githubusercontent.com/63310656/83660273-3f374480-a5e2-11ea-8e06-5dce9d627249.png)

**Comment by scasaletto** [comment]
Not yet in nightly build.

**Comment by scasaletto** [comment]
This is in the nightly build as of 20200604.
In the Transactions screen, select a  send transaction so that the Generate Proof is no longer greyed out. You should be able to compare this button against the Validate Proof File and Export .CSV buttons at the top of the page. The Generate Proof button has a 2 pixel border while the other buttons now have a 1 pixel border. Also the font of the Generate Proof button is larger and more pronounced than the other buttons. These are the changes that were made.

**Comment by vinayaga07** [comment]
Verified in the latest build and observed "Generate Proof" is always greyed out.
Please refer the screenshot.
![image](https://user-images.githubusercontent.com/63310656/83790608-15e7e880-a6b6-11ea-8433-14f84402f50a.png)

**Comment by scasaletto** [comment]
The Generate Proof button was not changed for this issue. I just mention to select it so that you can compare how the smaller buttons on the screen have changed from what they originally were. In your case, I think the Generate Proof button is greyed out because you have multiple transactions selected. The Generate Proof button will only be ungreyed when you have a Send transaction selected.

**Comment by vinayaga07** [comment]
Here is the latest screenshot.

![image](https://user-images.githubusercontent.com/63310656/84689594-d5faee00-af5e-11ea-9e82-d4dc3e4e170c.png)
