### ISSUE TITLE
Resize Message Box smarter

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#303]
We should try to find the way adjust message box to content size better 

![image](https://user-images.githubusercontent.com/42393608/81504733-cf15f700-929f-11ea-9b78-07ac22d37cf9.png)

**Comment by bayk** [comment]
It works great for me now, probably user had old version. Closing

**Comment by electrum17** [comment]
I think I saw some things like this on Linux so it's possible that's what they were using. Did you try Linux?

**Comment by bayk** [comment]
Will try

**Comment by bayk** [comment]
There was issue under the windows, now works for me.

Also I think I fixed that problem with 200% scale under the Windows, one of qt flag add additional scale.

**Comment by bayk** [comment]
Testing:
Please test MacOS, Linux, Windows
Linux with high definition monitor (retina or 4k) and different scales
Windows with  high definition monitor (retina or 4k) and different scales

**Comment by vinayaga07** [comment]
Verified with Windows QT-Wallet and alignment looks good to me.

![image](https://user-images.githubusercontent.com/63310656/84688259-ac40c780-af5c-11ea-8c4e-bb38a7f9e10f.png)

**Comment by vinayaga07** [comment]
Successfully verified the message box in MAC platform also, hence closing this ticket.
