### ISSUE TITLE
[QT-Wallet] Tool Tip is not clearly visible in "default Available " Send option.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#305]
**Description:**
[QT-Wallet] Tool Tip is not clearly visible in "default Available " Send option.
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/81589816-6fbb0280-93d7-11ea-927b-821b21c19210.png)

**Comment by bayk** [comment]
Tooltips with styles doesn't work for combo box, we can't use them there. 
It is QT bug and we are not going to fix that.
All tooltips from combo boxes are cleaned out.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
