### ISSUE TITLE
[QT-Wallet] Tool tip is missing in "show passphrase" page for the buttons - "Cancel", "Confirm".

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#308]
Description:
Tool tip is missing in "show passphrase" page for the buttons - "Cancel", "Confirm".
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/81592450-9d09af80-93db-11ea-875b-3f882c886ddf.png)

**Comment by bayk** [comment]
@vinayaga07 , just FYI. Just ticket is about ALL question dialogs. I will add tooltips to all similar ones. I think it is good idea, tooltips can give more details about what will happen.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
