### ISSUE TITLE
[QT-Wallet] In Contact Page, UI is not well aligned. 

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#310]
**Description:**
In Contact Page, UI is not well aligned. 
Able to see, lot of unwanted spaces.
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/81593434-11911e00-93dd-11ea-8b12-c06890e4a49a.png)

**Comment by bayk** [comment]
It is not an issue, you can align headers as you need. Column width will be saved in the settings.
Default values are fit default wallet size well for me.
Moving to fix.

**Comment by vinayaga07** [comment]
@bayk 
I'm using QT wallet on the Windows platform and given below the Issues observed,
1. If we manually align the Column width, then also observing lot of empty spaces in the right side.
2.  Row values are aligned with Center, instead it should be left aligned. (please refer the below screenshot)

![image](https://user-images.githubusercontent.com/63310656/84417972-14796b80-ac34-11ea-8800-59a98f516c95.png)

**Comment by bayk** [comment]
Alignment is updated

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/84687796-ea89b700-af5b-11ea-9bb3-9a0e786dd87d.png)
