### ISSUE TITLE
[QT-Wallet] Wallet setting Title need to be renamed

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#314]
**Description:**
In Settings-->"Wallet Configuration" page Title need to be renamed from "mwc713 settings" to "MWC QT wallet Settings".

Please refer screenshot for more details.
![image](https://user-images.githubusercontent.com/63310656/81720012-7448ef00-949b-11ea-8aca-3573161ecc6c.png)

**Comment by bayk** [comment]
Actually "mwc713 setting" need to be deleted. 
In the beginning there was mwc713 settings only. Now it is not relevant.
The page name displayed in the App title.
Also that will make this page less crowded

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
