### ISSUE TITLE
[QT-Wallet] "MWC" should be always in CAPS

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#315]
**Description:**
The word "MWC" should be always in CAPS but observed lot of discrepancies. (In many places it is SMALL case)
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/81720390-f9cc9f00-949b-11ea-8f85-8fed11ebf235.png)

**Comment by bayk** [comment]
Fix is about all 'MWC' words, not only this page.
This page is looks like expected for me

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/84687110-cc6f8700-af5a-11ea-99f6-c0a91538eb25.png)
