### ISSUE TITLE
[QT-Wallet] All the Web links should be clickable

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#317]
**Description:**
All the Web links in the HODL page and HELP, should be clickable.
Currently we are not able to click the link and also not able to copy the link address, so it is difficult for the user to use the same.

Please refer the screenshots for more details.
![image](https://user-images.githubusercontent.com/63310656/81722566-2d5cf880-949f-11ea-8d58-9e2d9b9d66e8.png)

![image](https://user-images.githubusercontent.com/63310656/81722584-364dca00-949f-11ea-9795-81a9024ce0f4.png)

**Comment by bayk** [comment]
@vinayaga07 ,  we can't do that easily because QT doesn't support that.
We don't want implement that manually. 
Best what we can do - make them copyable.

**Comment by bayk** [comment]
It is really too much effort to do that. It doesn't worth do to for HODL page. The problem that copyable controls are not auto resizable. Manual resizing is unstable, so we will need to sacrifice how page looks like and that will be worst. HODL is very specific page, so user will go and type the url manually.
I am closing that.
