### ISSUE TITLE
[QT-Wallet] "MWC NODE CONNECTION" Page needs UI updates

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#318]
**Description:**
In QT wallet, goto "Node Overview" page and click "Change Node" button.
1. Page Title need to be changed from "MWC NODE CONNECTION" to "MWC Node Connection"  and also Font should be same as other Title messages.
2. Tool tips are missing for the buttons.

Please refer screenshot for more details.
![image](https://user-images.githubusercontent.com/63310656/81724610-4b782800-94a2-11ea-9baa-e4d90100a0e5.png)

**Comment by bayk** [comment]
Note. Title font is the same for all dialogs, there is no per window customization. It might be feed different because of visual effects.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/84685872-9af5bc00-af58-11ea-9735-678c182fb34a.png)
