### ISSUE TITLE
[QT-Wallet] In "Accounts" page, UI needs updates.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#322]
**Description:**
In Accounts page, observed the following issues,
1. Needs description about the ACCOUNTS page.
2. Page UI need to be aligned, observing lot of empty spaces in the right side of the Table .

Please refer screenshot for more details .
![image](https://user-images.githubusercontent.com/63310656/81728266-d0197500-94a7-11ea-906d-b143fe14a1ab.png)

**Comment by condensed-io** [comment]
for the width issue, can you evenly space the columns horizontally to take up 100% width always?

**Comment by condensed-io** [comment]
thanks @vinayaga07 for bringing up some design considerations !

**Comment by bayk** [comment]
It is current default values, seems like issue is addressed.

![image](https://user-images.githubusercontent.com/42393608/96514136-11ad0980-1218-11eb-8697-53a9f1769ad8.png)

None default we can't fix
