### ISSUE TITLE
[QT-Wallet ]Contact page needs UI updates.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#323]
**Description:**
In QT-Wallet Contact page, observed the following issues,
1. Page needs a Title.
2. Short description about the page.

Please refer screenshot for more details.
![image](https://user-images.githubusercontent.com/63310656/81728542-4322eb80-94a8-11ea-99d1-e5710f105889.png)

**Comment by bayk** [comment]
Hi  @mwc-design , please review the contacts page design.

**Comment by condensed-io** [comment]
are you saying there should be a title shown for all pages?  not just this one?  We are adding a page title for pages on mobile, I think it's useful we could add it to the design of the desktop wallet too: https://postimg.cc/4mPH23Mb

**Comment by bayk** [comment]
Probably make sense to fix how. New control is ready. Let's have it

**Comment by bayk** [comment]
Title is added for all pages that have a navigation menu.  Title is removed from the window caption.

**Comment by vinayaga07** [comment]
Verified the Title for the Contacts page, hence closing this ticket.
