### ISSUE TITLE
[QT-Wallet] Change wallet instance folder name title need to be changed.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#326]
**Description:**
Change "Wallet instance" page Title need to be changed.

**Steps to reproduce**
1. Open QT wallet
2. Click "Wallet Instance" link 
3. Verify the Title of the page

**Expected Result:**
"Wallet instance" page Title need to be changed from "Select mwc713 folder name" to "Select MWC QT-Wallet folder name".

Please refer screenshot,

![image](https://user-images.githubusercontent.com/63310656/81965851-451ab500-9636-11ea-83bf-5b0c95c1dd66.png)

**Comment by bayk** [comment]
Modal dialogs can't change anything outside themselves. 
Dialog has a title "Select mwc713 folder name".  Title looks simple because it is how UI style is defined.

**Comment by bayk** [comment]
This UI doesn't exist any more and new one handle wallet names fine.
