### ISSUE TITLE
[QT-Wallet] Changing of Auto-Logout Option leading to Logout the wallet instances.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#328]
**Description:**
In QT-Wallet, changing of Auto-Logout Option leading to Logout the wallet instances.

**Steps** followed
1. Login to QT-Wallet
2. Select "Settings" --> "Wallet Configurations" --> "Wallet".
3. Change "Auto Logout" to 10 mins
4. Click "**Apply**" button 
5. Click "**Reset**" button 
6. Change "Auto Logout" to 5 mins
4. Click "**Apply**" button 

Please refer screenshots.
![image](https://user-images.githubusercontent.com/63310656/81970418-24099280-963d-11ea-87fa-7137d608ba7b.png)

![image](https://user-images.githubusercontent.com/63310656/81970299-ec024f80-963c-11ea-80c7-2445558806c2.png)

**Comment by bayk** [comment]
I think it is duplicate and was fixed for a while ago. Or might be more settings was changed that need to restart. 
Current nightly works fine, moving to 'fixed'

**Comment by vinayaga07** [comment]
Duplicate, hence closing this ticket.
