### ISSUE TITLE
[Qt-Wallet] Enabling & Disabling mwc wallet Logs, leading to Logout the wallet instances.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#329]
**Description:**
In QT-Wallet, changing of mwc wallet logs by Enabling & Disabling,  leading to Logout the wallet instances.

**Steps followed**

1. Login to QT-Wallet
2. Select "Settings" --> "Wallet Configurations" --> "Main".
3. Change "mwc wallet logs" to "Disabled"
4. Click "Apply" button
5. Click "Reset" button
6. Change "mwc wallet logs" to "Enabled"
7. Click "Apply" button
8. Change "mwc wallet logs" to "Disabled"

![image](https://user-images.githubusercontent.com/63310656/81974508-51593f00-9643-11ea-8507-cd449f80c70b.png)

**Comment by bayk** [comment]
Current nightly is fine and nothing was changed.
My guess that wallet might be locked by timeout.
Wallet reset auto lock time only when pages are changed. Action inside page is ignored.

I created another ticket about that, I think we might figure out something. https://github.com/mwcproject/mwc-qt-wallet/issues/333

**Comment by vinayaga07** [comment]
Able to reproduce the issue with the latest build - https://ftp.mwc.mw/nightly_builds/05-18-2020/, hence re-opening the ticket.


**Steps followed**

1. Login to QT-Wallet
2. Select "Settings" --> "Wallet Configurations" --> "Main".
3. Change "mwc wallet logs" to "Disabled"
4. Click "Apply" button
5. Click "Reset" button
6. Change "mwc wallet logs" to "Enabled"
7. Click "Apply" button
8. Change "mwc wallet logs" to "Disabled"

![image](https://user-images.githubusercontent.com/63310656/82236240-71de0d80-9951-11ea-9f48-4b966591dcaf.png)

**Comment by bayk** [comment]
The root problem is: #333
Currently this ticket is duplicate of that

**Comment by vinayaga07** [comment]
Successfully verified in the latest build , hence closing this ticket - https://ftp.mwc.mw/nightly_builds/05-26-2020/
