### ISSUE TITLE
mqs for different domains doesn't work

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#330]
Appears to be a problem with send. Can test with test3.mwc.mw domain.

To reproduce:

1.) Setup 2 mwc713 wallets.
2.) Configure both to have the domain test3.mwc.mw (mwcmqs_domain = "test3.mwc.mw")
3.) Send from 1 wallet to another.

Current behavior:
Wallet will not send funds from wallet 1 to wallet 2.

Expected behavior:
Funds should be sent from wallet 1 to wallet 2.

**Comment by yyangli** [comment]
./mwc-wallet --floonet send 0.001 -m mwcmqs -d xmg2tDx6pdFupaL3TnU9NScSzPzqE5Cvb7aMR32TzeN77dWxEnMh@test3.mwc.mw
