### ISSUE TITLE
Receive Account & Fluff need to implemented in mwc-wallet side

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#332]
Currently set-recv  and FLUFFED_SLATES are broken because implementation moved to mwc-wallet side. 
New support need to be done for ALL transport, including future. So it need to be implemeted in the base functions.

**Comment by bayk** [comment]
Testing for set-recv:  Set-receive account need to be tested for all transaports:   MQS, keybase, http and files. It can be done with QT wallet.
Testing for Fluff:  if Fluff feature working, can be tested with Node Debug logs. Flaff flag should work for all transports (MQS, keybase, http and files). For Files - it can be set at finalize step. For online - at send step.

**Comment by jbyrer** [comment]
Confirmed:
Setup:
One mwc-wallet connected to one mwc-node , which would send and receive from another qt wallet.

Testing: 

Confirmed Fluff by sending coins using all 4 types of transactions and watching the mwc-node logs for "fluff" (Chris added some debug for this).

Confirmed set-receive by leaving a QT wallet open to the receive tab, and having an custom account selected.  I then sent from the mwc-wallet using the 4 types of method (http, mwcmqs, http, file) and confirmed the funds went to the correct accounts.
