### ISSUE TITLE
Auto logout time should consider general user activity

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#333]
Currently logout times is reset only in user switch pages.
If there are action on the single page, user can experience automatic logout.

**Comment by bayk** [comment]
This ticket is dependent on another one about the MacOS app title color change. We need a single base class for all windows that allow to intercept event for user action.

**Comment by vinayaga07** [comment]
If there are action on the single page, automatic logout is not happening.
Hence closing this ticket.
