### ISSUE TITLE
Num. outputs -> Change outputs

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#336]
Seeing outputs as 0 can confuse users. This should be labeled "Change outputs" instead of "Num. outputs"

![image](https://user-images.githubusercontent.com/7232183/82154422-a43d1d00-9822-11ea-9ea9-bc8215b1bba6.png)

**Comment by scasaletto** [comment]
Changed Num. Outputs label to Change Outputs

**Comment by vinayaga07** [comment]
@sarawut11 
With the latest build, not observed the UI change of Num. Outputs label to Change Outputs, hence re-opening the ticket.

![image](https://user-images.githubusercontent.com/63310656/83661014-2ed39980-a5e3-11ea-9520-d72db33e4074.png)

**Comment by sarawut11** [comment]
@vinayaga07 I guess, @scasaletto can fix it easily since she already worked on it before.

**Comment by scasaletto** [comment]
This fix is in the nightly build of 20200604.
When you double-click a transaction in the Transaction screen, the transaction dialog that pops up should now have a field named Change Outputs instead of Num. Outputs.

**Comment by vinayaga07** [comment]
Verified in the latest build, hence closing this ticket.
![image](https://user-images.githubusercontent.com/63310656/83790897-85f66e80-a6b6-11ea-8a99-54246e68e87b.png)
