### ISSUE TITLE
mwc-wallet (mwc713) need to reuse connection to the node

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#337]
Initial research shown that our client/server CAN reuse the connection and it improve latency a lot.
Practically wallet does reconnect for every http call.

**Comment by bayk** [comment]
Also add cache on Node Client level

**Comment by bayk** [comment]
Testing:  There are no feature to test. You should be able to see about 2 times less waiting on mwc71 regular commands like 'sync', 'info', 'txs'  e.t.c.
Performance for 'check' or recover form seed will be almost the same.

**Comment by vinayaga07** [comment]
wallet713> outputs

Wallet Outputs - Account 'default' - Block Height: 398162
------------------------------------------------------------------------------------------------------------------------------------------------------------
 Output Commitment                                                   MMR Index  Block Height  Locked Until  Status   Coinbase?  # Confirms  Value        Tx 
============================================================================================================================================================
 092204375b8b7862bb16dd43f07a18f6195de97f33c26c4471182ebf0a87db8cc8  None       351584        0             Unspent  false      46579       3.992000000  1 
------------------------------------------------------------------------------------------------------------------------------------------------------------

wallet713> info
Verified the regular commands like 'sync', 'info', 'txs', hence closing this ticket.

____ Wallet Summary Info - Account 'default' as of height 398163 ____

 Confirmed Total                  | 3.992000000 
 Awaiting Confirmation (< 10)     | 0.000000000 
 Awaiting Finalization            | 0.000000000 
 Locked by previous transaction   | 0.000000000 
 -------------------------------- | ------------- 
 Currently Spendable              | 3.992000000 

wallet713> sync
Your wallet data successfully synchronized with a node
wallet713>

**Comment by vinayaga07** [comment]
Verified the commands in MWC wallet, hence closing this ticket.
