### ISSUE TITLE
Move AirDrop to just above HODL on main screen

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#341]
Since the airdrop is done, we don't want it to take the most prominent spot for activity selection on the main screen. Move it to just above HODL at the bottom of the left panel on the main screen.

See Brent's doc at: https://docs.google.com/document/d/1p12FnhtsjQpOuHcYnmDVWwOceT5K-j1nre68hZz8tjU/edit#

For the improvements in the UI he would like. This issue is only to address the AirDrop issue.

**Comment by scasaletto** [comment]
Moved Airdrop down in left hand tool bar to just above HODL

**Comment by vinayaga07** [comment]
@scasaletto 
In Today's QT Wallet  build, not observed the above mentioned fix.
Hence reopening the ticket.

![image](https://user-images.githubusercontent.com/63310656/83659951-d3ed7280-a5e1-11ea-857a-f0993b24504c.png)

**Comment by vinayaga07** [comment]
Verified in the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/83790160-5e52d680-a6b5-11ea-80bc-b8fa9ee86464.png)
