### ISSUE TITLE
when sending hitting enter results in the send being "declined"

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#342]
When you type in your password fully on send, and hit enter, it will decline the transaction. If your password is correct, and hit enter the transaction should be sent.

Steps to reproduce:
1.) Login to Qt wallet.
2.) Create any send transaction.
3.) Enter full password in confirmation box.
4.) Hit "enter" button on keyboard.

Current behavior: transaction dialog will close.

Expected behavior: transaction will be sent.

**Comment by bayk** [comment]
Yes, we should fix that, we have our custom default button management

**Comment by vinayaga07** [comment]
Verified with the latest build - https://ftp.mwc.mw/nightly_builds/05-26-2020/
Hence closing this ticket.
