### ISSUE TITLE
mwc713 send failing if send account is different from receive

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#343]
mwc713>> LibWallet Error, Unable to finalize slate, Payment Proof generation error: TxLogEntry with original proof info not found (is account correct?)
20.05.2020 21:02:16.055 mwc713-Event> S_ERROR [TxLogEntry with original proof info not found (is account correct?)]
20.05.2020 21:02:16.055 Notification CRITICAL  TxLogEntry with original proof info not found (is account correct?)
20.05.2020 21:02:16.055 MWC713 emit onNewNotificationMessage with NotifMsg(level=Crit, message=TxLogEntry with original proof info not found (is account correct?))

**Comment by bayk** [comment]
testing: 
- create 3 accounts: a1,a2,a3.
- set receive account a1
- send from account a2
- send from a3
- send from a1
- send from default.

Check that all send was fine, no errors in the logs

**Comment by jbyrer** [comment]
went through the steps described above, and saw no errors in the logs.
