### ISSUE TITLE
[QT-Wallet] In  Windows platform, Wallet setting page UI alignments are not proper.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#346]
**Description:**

In QT-Wallet (Windows platform), Wallet setting page UI alignments are not proper.
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/82691031-e29b6780-9c7a-11ea-8aec-a81dddd7bd7d.png)

**Comment by vinayaga07** [comment]
Note:
The same page looks good in MAC OS platform.

**Comment by bayk** [comment]
Hi @sarawut11 , if you have time please check at that white right/bottom border.  It is visible under the Windows (MacOS is fine).

**Comment by sarawut11** [comment]
ok

**Comment by sarawut11** [comment]
@bayk fixed the border issue in this PR(https://github.com/mwcproject/mwc-qt-wallet/pull/359).

**Comment by bayk** [comment]
It was fixed a while back

**Comment by bayk** [comment]
It was fixed a while back
