### ISSUE TITLE
Qt wallet should expose some options in mwc-wallet for sending transactions

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#348]
In addition to the "fluff" transactions, mwc-wallet has the following:
1.) repost
2.) repost as fluff
3.) ttl (time to live)

These should be exposed to Qt wallet. It's important because if a transaction doesn't confirm, it's not clear how long to wait after cancelling to resend a transaction.

**Comment by bayk** [comment]
Repost was done awhile back and now transformed to a new UI. Fluff value is the last used value that is expected.
TTL for files does exist and it can't be updated.
So looks like everything is covered.

**Comment by bayk** [comment]
Closed because duplicated ticket for the testing are exist
