### ISSUE TITLE
qt wallet data dir access error handling

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#350]
Currently qt wallet using exception to signal IO issues with data dir access. 
The rest of app doesn't handle it.
Since QT doesn't use exceptions, as well as the rest of the app. Let's switch error processing model for error flags with error messages.

**Comment by bayk** [comment]
Testing:
This issue is hard to reproduce normally, so far we get the only report. 
But I think it should be possible to produce it with permissions.
You can target at directory ~/mwc-qt-wallet/.   For example logs.  You can delete 'logs' and make 'mwc-qt-wallet' read only. In this case error should be reported during logs initialization.

**Comment by vinayaga07** [comment]
Have deleted the wallet log files and changed the directory ~/mwc-qt-wallet/ permission to READ-Only; afterwards got the below error message.


Wallet got a critical error:
mwc713 process exited due some unexpected error.
mwc713 exit code: 101

thread 'main' panicked at 'could not create address book backend!: LmdbErr(Error::Code(5, 'Input/output error'))', src/main.rs:491:9

You might use command line for troubleshooting:

'C:/Program Files/MWC/mwc713.exe' '--config' 'C:/Users/pavit/mwc-qt-wallet/wallet713v2.toml' '--disable-history'

Press OK to exit the wallet

**Comment by vinayaga07** [comment]
![image](https://user-images.githubusercontent.com/63310656/83048818-d131d100-a067-11ea-9df5-9c1e064b23fc.png)

**Comment by vinayaga07** [comment]
Wallet is not crashing but giving proper error message, hence closing this ticket.
