### ISSUE TITLE
Send doesn't check if listener (mqs & keybase) online

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#351]
At send page we should detect that send will never work and explain that to user. Show message box and ask if he want to go to the Listeners page.

P.S. Marked as minor issue because listeners normally are doing well and error message said that wallet need to start listening first.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/84802680-9398e600-b01e-11ea-89b1-379fb1261191.png)
