### ISSUE TITLE
Verify if REST API and console Send report and process correctly timed out transaction

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#352]
We need to test 4 scenarios the same case:
Alice send MWC to Bob.

1. Alice send with MWS/KeyBase to Bob.  Bob goes offline for a short time, enough report time out on on Alice side. 
2. Bob come online. Because MQS and Keybase has memory, slate will be processed and respond will send back. Bob will get a receive transaction.
3. Alice will get a respond back from Bob. Expected that wallet DONT finalize it because error was reported.

That scenario need to validate for MQS & Keybase.  For console send & Rest API.  Total 2x2 cases. All cases might have different workflow.

**Comment by bayk** [comment]
@jbyrer , there are issues with that, I will take a look first then will test a fix

**Comment by bayk** [comment]
Testing:
1. Need to verify if send work fine with all methods (file,http,mqs, keybase). Command line form mwc713, command line from mwc-wallet and Rest API (just single Send call, no step APIs)
2. Verify that MQS generate proofs, you can download those proofs and validate at the explorer.
3. Check if original scenario with Bob & Alice doesn't fail.
4. Check if QT wallet can send coins with all 4 transport and doesn't report any errors or wrong messages.  And Does report that slate was send, received and finalized.

**Comment by jbyrer** [comment]
verified the above scenarios, proofs are not generated for mwc-wallet atm because that feature is being worked on.
