### ISSUE TITLE
[QT-Wallet] In Windows platform  QT wallet settings page, UI options are missing

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#353]
**Description:**
In Windows platform, QT wallet settings (wallet), options for selecting Auto-logout,Auto-Start are missing. Please refer screenshot for more details. 

![image](https://user-images.githubusercontent.com/63310656/82924400-e6d8c500-9f99-11ea-9c8e-d9ed755bb975.png)

**Comment by bayk** [comment]
The root problem - whose scaling was broken

**Comment by vinayaga07** [comment]
Verified and looks good with the latest build. Hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/83166827-1835ca00-a12d-11ea-89ab-4e639a1e4ad4.png)
