### ISSUE TITLE
[QT-Wallet] Logout failed with the error message.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#354]
OS Versions Tested: Windows
Build -https://ftp.mwc.mw/nightly_builds/05-26-2020/

Steps to reproduce:
1. Login into QT-Wallet
2. Goto Settings and change MQS Domain to  dev1.mwc.mw.
3. Click Logout button

Actual Result:
Logout is not happened and got the below error message.

![image](https://user-images.githubusercontent.com/63310656/82927483-68325680-9f9e-11ea-91d3-565f3476eaab.png)

**Comment by bayk** [comment]
From the work flow it can happen if wallet was recovered. I wasn't be able to reproduce for a normal usage. Fix cover wallet recovered case.
Will mark ticket as ready when start nightly.

**Comment by vinayaga07** [comment]
Not able to reproduce the issue with the latest build, hence closing this ticket.
