### ISSUE TITLE
[QT-Wallet] Stopped the MWC MQS listener, warning message needs corrections.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#355]
Description:
In QT-Wallet, stopped the MWC MQS listener and got the below message which needs UI correction.

Actual Message
mwcmqs listener is closed! consider using `listen` first./n

![image](https://user-images.githubusercontent.com/63310656/82933201-35d92700-9fa7-11ea-9cfa-fa01e8d1e2b7.png)

Expected Result:
mwcmqs listener is closed! consider using MQS listener.

**Comment by bayk** [comment]
Now this message should never appear. The message was a bug. Currently you can play with start/stop buttons and mwc713 handles it.

**Comment by vinayaga07** [comment]
When we start/stop MWC MQS, not getting the above mentioned message, hence closing this ticket.
