### ISSUE TITLE
node info command doesn't need to do retry. node tip need smaller retry 

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#356]
if node is offline, it takes too much time to get a response from the wallet

**Comment by bayk** [comment]
Testing: 
Connect qt wallet to offline node. Then check if it is not unreasonably slow.

**Comment by jbyrer** [comment]
It took just over 2 minutes
![image](https://user-images.githubusercontent.com/10661009/84100972-cfe69980-a9c1-11ea-887f-cd6cd7e0379d.png)
I confirmed with K and that is a good time :).
