### ISSUE TITLE
In Windows platform, QT wallet settings, options for selecting Running Mode are missing. 

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#358]
**Description:**
In Windows platform, QT wallet settings ("Select Running Mode"), options for selecting Running Mode are missing. Please refer screenshot for more details

![image](https://user-images.githubusercontent.com/63310656/83048884-eb6baf00-a067-11ea-8bb3-a95dc587728c.png)

**Comment by bayk** [comment]
The root problem - whose scaling was broken

**Comment by vinayaga07** [comment]
Verified and looks good with the latest build. Hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/83166973-46b3a500-a12d-11ea-94f6-78c2456a13af.png)
