### ISSUE TITLE
Non ascii characters in directory

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#361]
When uploading a file, non-ascii characters result in an error.

**Comment by bayk** [comment]
Testing:
Try to select files, directories with non ascii symbols. That should be prohibited

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/86657269-f38b0880-bf9c-11ea-96eb-6e5a390b9ad7.png)

I believe this is what is expected.
