### ISSUE TITLE
[QT-Wallet] Second transaction failed between accounts within the same wallet.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#362]
**Description:**

During MWC transfers between accounts within the same wallet, first transaction went successfully... but second transaction failed with the below error message.

![image](https://user-images.githubusercontent.com/63310656/83436642-d7ef8800-a45b-11ea-917e-fa3c6e32ebc1.png)

**Comment by bayk** [comment]
Because of recent changes mwc713 now does 'send' in sync mode and handle transactions well. Because of that I cleaned up some code, qt wallet is more simple now.
Testing. 
Please also test is send and receive show all needed messages.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
