### ISSUE TITLE
[QT-Wallet]  Help page needs modifications like - Font, Font Size.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#363]
**Description:**
UI in the Help page needs modifications like - Font, Font Size, ....
Please refer screenshots for more details.

![image](https://user-images.githubusercontent.com/63310656/83437365-46811580-a45d-11ea-9d0a-f4f9412cd3b3.png)

**Comment by bayk** [comment]
Page is in HTML, so fonts can be defined, as well as colors.
All pages are located at 
mwc-qt-wallet/help/

**Comment by bayk** [comment]
We such duplicate for the Windows. Closing this one
