### ISSUE TITLE
[QT-Wallet] Transaction fee details are not getting displayed, while transaction is within the same wallet different account.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#365]
**Description:**
Transaction fee details are not getting displayed, while transaction is within the same wallet different account.

**Expectation:** 
Transaction fee details should be displayed, for all the transactions.

**Comment by scasaletto** [comment]
The transaction fee was not added to this type of transfer because there currently is not a confirmation dialog. Need to add a confirmation dialog and the transaction fee info.

**Comment by scasaletto** [comment]
![image](https://user-images.githubusercontent.com/7772099/83668502-aed31280-a595-11ea-9d3e-c4fa0ce80e66.png)

**Comment by bayk** [comment]
Yes, the real issue is a confirmation dialog. We should add it.

**Comment by bayk** [comment]
It is fixed by now, confirmation dialog has the fees 
![image](https://user-images.githubusercontent.com/42393608/96515071-85034b00-1219-11eb-8f07-11796dd6d9b9.png)

**Comment by vinayaga07** [comment]
Verified with the latest build and not getting confirmation dialog box while transferring within Account in the same wallet.
Hence re-opening this ticket.

![image](https://user-images.githubusercontent.com/63310656/97322140-80800780-1895-11eb-8bed-6ab54e2b8865.png)

**Comment by bayk** [comment]
![Uploading image.png…]()

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/97899779-b888be00-1d5f-11eb-8c6a-a3c0c8411c5b.png)
