### ISSUE TITLE
QT-Wallet is getting crash, while sending coins via keybase when the contact person is offline.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#366]
**Description:**
QT-Wallet is getting crash, while sending coins via keybase when the contact person is offline.
Since the Keybase contact person is offline, Transaction should fails due to Timeout and QT-Wallet should not get closed.

![image](https://user-images.githubusercontent.com/63310656/83555346-c5448400-a52b-11ea-97ea-11642420c8c1.png)

**Note**

- Able to reproduce the issue 2 out of 3, hence for tracking raising this ticket.

**Comment by bayk** [comment]
here is a commit https://github.com/mwcproject/mwc-qt-wallet/commit/418b5fd9057a83c67c64a3a9bfb525404303dc1b

**Comment by jbyrer** [comment]
tested and closed
