### ISSUE TITLE
Resetting Auto-Logout time resets confirmations to 10

### ISSUE THREAD

**Issue by privateidentity** [mwcproject/mwc-qt-wallet#368]
When pressing reset in the 'Wallet' section shown below the confirmations in the 'Main' section are set back to 10.

Is this the desired behaviour? It appears the desired behaviour would be to reset the settings displayed in each section either 'Wallet'  or 'Main'

![resetting autologout time resets confirmations](https://user-images.githubusercontent.com/64110976/83628424-c634ee80-a5db-11ea-9023-4aaa695534b1.png)

**Comment by cgilliard** [comment]
Agree, this setting should not be changed with reset.

**Comment by bayk** [comment]
Reset button is resetting all settings. Point of that to restore wallet to default point.
The primary use case is similar to "Factory Reset" on smartphones. When user mess up with settings and really don't know what to do, he can do "Reset". In this case we really want to reset all, so wallet will start working as after install.
Also, the same usage for support, it is make sense to reset settings before trouble shouting.

We probably can add message box about that.
@cgilliard , @privateidentity , what do you think about that?

**Comment by privateidentity** [comment]
I discovered this behaviour when going through the testing checklist for resetting the auto logout time. 

The tool tip does communicate the outcome of pressing the reset button. 

I think you're right and a message box with the text "confirmations have been set to 10, auto logout to 20 mins" will communicate to the user what settings changed.

Currently the change of back to 10 confirmations is hidden by the tabs of Main and Wallet. So the key issue is only the user doesn't know what settings were reset.

@bayk 
So making this a low priority fix where the solution is adding a message box seems like a good idea.

**Comment by cgilliard** [comment]
One that's hard to recover is the MWCMQ. If you need to get it to default
the only way I know is to reset. The rest seem ok, but yeah a warning would
be good.

**Comment by bayk** [comment]
Current default timeout is 20 minutes. Reset does reset all settings on all pages. It is like "Factory Reset" on smartphones
