### ISSUE TITLE
[QT-WALLET] Change Awaiting Confirmation to Unconfirmed in account info combo box

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#369]
From Brent,

When in ‘transactions’ the account selection dropdown shows the amount of mwc you have in that account.  It’s broken down into total, spendable, locked, and ‘awaiting confirmation’ --- please change ‘awaiting confirmation’ to ‘unconfirmed’

**Comment by scasaletto** [comment]
Updated the text which populates the account info combo box to use Unconfirmed instead of Awaiting Confirmation. This change will affect all account info combo boxes and not just the one on the Transactions screen. Transactions, Outputs, Account Transfer and Receive screens will all reflect the update.

**Comment by vinayaga07** [comment]
@scasaletto  In Today's build, not observing the fix. Please let me know once the build is ready for the verification.

**Comment by scasaletto** [comment]
Not yet in nightly build.

**Comment by scasaletto** [comment]
This is in the nightly build of 20200604.
In any screen where you find an account drop down list, the last field for each account listed should now say "Unconfirmed" instead of "Awaiting Confirmation". You will see the account drop down list in the following screens: Transactions, Outputs, Receive, Account Transfer.

**Comment by vinayaga07** [comment]
Successfully verified in the screens : Transactions, Outputs, Receive, Account Transfer. Hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/83791713-bbe82280-a6b7-11ea-9b54-5815ea61ef84.png)
