### ISSUE TITLE
Claim not possible for bech32 addresses

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#37]
This address is registered, but not possible to click request airdrop button. See screenshot.
<img width="756" alt="Screen Shot 2019-08-18 at 6 54 41 PM" src="https://user-images.githubusercontent.com/7232183/63234371-e41a9980-c1e9-11e9-8fb0-d014862026d0.png">

**Comment by bayk** [comment]
Change validation to address.length() >= 26
