### ISSUE TITLE
[QT-Wallet] Assert hit when changing accounts while transactions are loading

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#370]
When you first enter the Transactions screen, if you change accounts while the transactions are still loading you will hit an assert in the code and the wallet will crash. I've only seen this while running in the debugger as it takes longer to load the transactions, but I'd guess it could also happen if you just happen to have a lot of transactions.

**Comment by scasaletto** [comment]
Removed assert since we now know this situation can occur and it shouldn't cause the wallet to crash.

**Comment by scasaletto** [comment]
Here is some stack info from running on Mac:
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6dc1533a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6dcd1e60 pthread_kill + 430
2   libsystem_c.dylib             	0x00007fff6db9c808 abort + 120
3   org.qt-project.QtCore         	0x00000001034b5869 0x10349f000 + 92265
4   org.qt-project.QtCore         	0x00000001034b71e0 QMessageLogger::fatal(char const*, ...) const + 224
5   org.qt-project.QtCore         	0x00000001034b21d8 qt_assert(char const*, char const*, int) + 72
6   mwc-qt-wallet                 	0x0000000101f3538a state::Transactions::updateTransactions(QString, long long, QVector<wallet::WalletTransaction>) + 90
7   mwc-qt-wallet                 	0x0000000101f3850d QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1, 2>, QtPrivate::List<QString, long long, QVector<wallet::WalletTransaction> >, void, void (state::Transactions::*)(QString, long long, QVector<wallet::WalletTransaction>)>::call(void (state::Transactions::*)(QString, long long, QVector<wallet::WalletTransaction>), state::Transactions*, void**) + 205 (qobjectdefs_impl.h:136)
8   mwc-qt-wallet                 	0x0000000101f38438 void QtPrivate::FunctionPointer<void (state::Transactions::*)(QString, long long, QVector<wallet::WalletTransaction>)>::call<QtPrivate::List<QString, long long, QVector<wallet::WalletTransaction> >, void>(void (state::Transactions::*)(QString, long long, QVector<wallet::WalletTransaction>), state::Transactions*, void**) + 88 (qobjectdefs_impl.h:170)

**Comment by scasaletto** [comment]
This is in the nightly build of 20200604.
In the transactions tab, quickly changing accounts several times while transactions are loading should not cause a crash now.

**Comment by vinayaga07** [comment]
Successfully verified in the latest build, hence closing this ticket.
![image](https://user-images.githubusercontent.com/63310656/83791387-5a27b880-a6b7-11ea-88d6-67af17df7a7c.png)
