### ISSUE TITLE
[QT-Wallet] Accepting negative values for transaction between accounts.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#371]
**Description:**

Tried transferring negative number of mwc coins (Example: -10) between accounts in the same wallet and observed the following issues,
1. If we provide negative number as a input to send, then all the amount available in the account_1 is getting transferred into account_2.
For example, if we send -10 mwc from  account_1 to account_2, then all the available amount from account_1 (200 MWC) is getting transferred into account_2.

2. If we provide negative number as a input to send, even though the account is in Locked state, amount is getting transferred.

**Expected Result:**
Negative input values should not be taken as input for transaction between accounts.
![image](https://user-images.githubusercontent.com/63310656/83665275-d43d3c00-a5e8-11ea-9889-01a9f12df34f.png)

**Comment by bayk** [comment]
Negative in internal protocols mean "ALL".  So UI will need to filter that out. As well as 0 amounts we are not going to support.

**Comment by vinayaga07** [comment]
Verified with the latest build and unable to transfer Negative & Zero valued amount within accounts, hence closing this ticket.
