### ISSUE TITLE
[QT-Wallet] Display amount when ALL is selected for send

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#372]
Brent has made a suggestion for something we can improve on in the wallet. "If someone wants to send the full amount in an account, and they paste or type in the number value manually they get the error (transaction couldn’t process because there wasn’t enough for the fee).  The reason someone might do that instead of clicking the ‘all’ button is because it just puts the word ‘all’ in the field, so you don’t really know if it’s sending ‘all’ from the account, or ‘all’ from ALL accounts.
The fix, which I think is standard on most wallets, would be to have it so when you click ‘all’ it puts in the mwc value, not the word ‘all’. Also, I’m hoping it would take the fee out of the account instead of failing? That part probably already works."
Now that we calculate the transaction fee, we can put in a check to see if someone is trying to spend all of their spendable coin, subtract the fee, and allow this type of send to proceed. What do you think?
chris-devToday at 12:03 PM
I like the idea of putting the value in when you click All instead of putting "ALL".
and since we have fee calculation, we can do that.
scasalettoToday at 12:40 PM
It seems like we should update the Send screen with the amount and also display the fee. Otherwise people might get confused about why the amount is less than their entire spendable coin.

**Comment by scasaletto** [comment]
chris-devToday at 12:54 PM
I don’t think we should change the amount entered.
I just think clicking all should display actual amount.
We want people to affirmatively enter the amount they want to send.
scasalettoToday at 12:59 PM
OK, but then on the confirmation screen, they would see the updated amount and the fee?
chris-devToday at 12:59 PM
Amount should not be updated
If you enter 5 it should remain 5
If you don’t have 5 plus fee it should be an error
I think what we have to today is good but when you click ALL it should show the amount minus fee
So if you have 5, click ALL it should show 4.998 plus fee (or whatever the correct value is)
scasalettoToday at 1:08 PM
Ok I think we are in agreement. We are only talking about if the user selects All. So when you click All, the Amount field should get updated with an amount that is equal to your current spendable coins minus the transaction fee. But we will not display the transaction fee to them on the Send screen. Correct? They will only see why there is a difference from what they see as an "Available" amount and what we have just populated the Amount with, when they hit Next, enter the Sent To address, and then hit Send.
chris-devToday at 1:11 PM
Yes, ideally we would show them the fee sooner too, but that can come later.

**Comment by scasaletto** [comment]
Clicking All on the Send screen will now fill the Amount field with the number of spendable coins minus the transaction fee.
Tested the following scenarios:
   HODL Account:
      All outputs locked except for 1 HODL output (0.492)
      Sent unlocked HODL output (txn fee: 0.004)
      Correct amount displayed (0.488)
      Send goes thru successfully
    Non-HODL Account With Locked Enabled:
      1 output unlocked (1.00)
      Send unlocked output (txn fee: 0.004)
      Correct amount displayed (0.996)
      Send goes thru successfully
    Non-HODL Account With Locking Disabled:
      3 outputs unlocked (total 0.282)
      Sent all unlocked outputs (txn fee: 0.002)
      Correct amount  displayed (0.28)
      Send goes thru successfully

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
