### ISSUE TITLE
Qt tor integration

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#374]
mwc713 now supports TOR.

Listen command: listen -t
Stop command: stop -t
send command: send -d <tor_address> <amount>

Qt should support TOR. The tor address should be displayed on the receive tab and send should work.

**Comment by bayk** [comment]
Currently for TOR we have indicators and we have support on listener side.

Need to do: 
1. At settings add Autostart for TOR.  In this case foreign API will be stared automatically and foreign API secret will be empty. If foreign API is running, it will be reused.

2. Send Page should recognize tor address and verify if Tor is running

**Comment by bayk** [comment]
@cgilliard 
I can do start/stop  pretty quickly and it make mwc713 go out of sync (tor will start even my last command was stop).  mwc713 should  be in sync or produce some errors and not start/stop

**Comment by electrum17** [comment]
Some notes for testing of TOR:

Should be pretty straight forward. It is much like mwcmqs from the user perspective. You have a receive address (added to the receive tab) and you can send from another wallet to that address. There is also a start/stop in the listener tab.

The main thing you might notice is that TOR is sometimes not reliable. It will more frequently go into the disconnected state. We have reconnect logic, but sometimes it takes a while. What I've noticed is that in many cases, when you disconnect, you will actually be connected and sending a transaction to a "disconnected" tor listener will cause it to instantly "recover". We may get better about detecting actual disconnected state, but for now I think this is fine.

**Comment by vinayaga07** [comment]
Have tested MWC Send & Receive using TOR on both Windows and MAC OS platforms successfully.

**Comment by vinayaga07** [comment]
Jim verified on Linux platform, hence closing this ticket.
