### ISSUE TITLE
Adding a new account sometimes flashes an error then succeeds

### ISSUE THREAD

**Issue by privateidentity** [mwcproject/mwc-qt-wallet#375]
When adding a new account named 'ac4' the UI flashed an error.
**Critical: Account switch error: Unknown Account Label 'del_ac4'**

Then after a few seconds the account creation of 'ac4' succeeded.
This only happened once it appears, and when I created another account named 'ac5' that worked fine.

![possible bug when adding accounts](https://user-images.githubusercontent.com/64110976/83710028-1c994000-a663-11ea-9996-dffc58997d5a.png)

**Comment by bayk** [comment]
Testing.
try to create/delete account multiple times. Before fix issue might happen if create/delete account was done during balance scanning. Balance scanning moment easy to catch with logs.

**Comment by jbyrer** [comment]
Confirmed the fix by watching tail and doing a lot of account creation and deletion
