### ISSUE TITLE
UI bug when transferring amounts that are too small between accounts

### ISSUE THREAD

**Issue by privateidentity** [mwcproject/mwc-qt-wallet#376]
When the amount transferred between accounts is too small to be mined the correct UI behaviour occurs, with an error message dialog opening.
**Funds transfer request has failed.
Failed to send the funds. Not enough funds. Required: 0.008050000, Available: 0.000100000**

Then moments later another two dialog boxes open communicating the transfer was successful.
This appears to be a UI bug.
![possible bug when transferring too small amounts between accounts](https://user-images.githubusercontent.com/64110976/83710842-0ab89c80-a665-11ea-8581-4cc33f266549.PNG)

**Comment by bayk** [comment]
Looks like it is fixed. I can transfer small amount. If for small amount I don't have enough funds, I see expected error message and no successful message
