### ISSUE TITLE
[MWC-QT-WALLET] LMDB issue with corrupted (?) wallet data

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#377]
On a wallet which probably had been corrupted somehow I got the following error BEFORE the login screen (so I couldn't switch instances, had to remove the old directory completely to force a new login)

![image](https://user-images.githubusercontent.com/10661009/83794174-76ddd500-a652-11ea-8f00-7ad22bf3c897.png)

**Comment by jbyrer** [comment]
[gui_wallet713_data.bad.zip](https://github.com/mwcproject/mwc-qt-wallet/files/4731921/gui_wallet713_data.bad.zip)

**Comment by bayk** [comment]
Instead of panic will print   
Error: Unable to open contacts DB, storage is corrupted, LMDB error, MDB_INVALID: File is not an LMDB file

Data from the contacts will be lost because data is corrupted. We can't make it better, DB is managed by rust 3rd party

**Comment by bayk** [comment]
Testing:
There is a corrupted data in attachment. It can be used on any OS to reproduce issue and check the fix.
Note, qt wallet will not show that error. Error will be available in the logs only.

**Comment by jbyrer** [comment]
I was able to reproduce the setup using the attached files.  I DID observe the error above in the logs only, as expected.
