### ISSUE TITLE
Request to expose list of outputs to be selected in the mwc-wallet api

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#378]
One of the mining pools requested this to be added to the api.
Basically they want the equiv of mwc713: send -p <list of outputs to use for selection> in the mwc-wallet owner-api.

**Comment by bayk** [comment]
It is easy to add, mwc-wallet has that functionality. Just need to expose it.

**Comment by bayk** [comment]
Testing:
mwc-wallet command line 'send' has new param 'outputs' similar to mwc713
Owner API send has new optional param output that accepts array of strings. Check  https://mwcproject.github.io/grin_wallet_api/trait.OwnerRpc.html
