### ISSUE TITLE
sending the exact amount of the smallest output will fail

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#383]
For example, if you have an output of 0.01 and another for 0.02, and you try to send 0.01, it will fail saying you need 0.018 and have only 0.01. Expected behaviour: you should be able to send because you have 0.03 total.

**Comment by cgilliard** [comment]
Fixed in master.

**Comment by jbyrer** [comment]
tested as suggested by C, having an account with a .01 an .02, then sending .01.  Confirmed the bug and the fix.  Also tried a variety of output locking scenarios
