### ISSUE TITLE
TOR appears as "Online", but you cannot stop it, only "Start" is visible.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#386]
When you click start is says "TOR is already running".

See image:
<img width="664" alt="Screen Shot 2020-06-10 at 4 35 46 PM" src="https://user-images.githubusercontent.com/7232183/84329076-8b313e80-ab38-11ea-9c50-a436b8d7bb1e.png">

Expected Behavior: should show as "Stop" while running and "Start" when not running.

**Comment by electrum17** [comment]
Fixed in latest build.
