### ISSUE TITLE
Wallet always in "Waiting state"

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#387]
<img width="732" alt="Screen Shot 2020-06-10 at 6 03 13 PM" src="https://user-images.githubusercontent.com/7232183/84333481-c0dc2480-ab44-11ea-904e-8a47b4d474aa.png">

**Comment by vinayaga07** [comment]
Verified in the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/84800707-cf7e7c00-b01b-11ea-85bd-1e0021f069c7.png)
