### ISSUE TITLE
Sent with "or" instead of "tor"

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#388]
This notification:
<img width="649" alt="Screen Shot 2020-06-11 at 3 37 41 AM" src="https://user-images.githubusercontent.com/7232183/84375856-00326180-ab95-11ea-837e-7a740f8a9ed5.png">

says sent with "or". It should say "tor".

**Comment by scasaletto** [comment]
Looked at this a little. From what I can see there are certain formats of strings that are expected. If there is a new string for TOR, the current parsing of the string in TaskSendMwc::processTask doesn't handle it.

**Comment by cgilliard** [comment]
Yes, I saw that but didn't want to mess anything else up by changing it so I opened the bug.

**Comment by vinayaga07** [comment]
Verified with the latest build and observed the below message, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/87175456-4b57a580-c2f6-11ea-8ea2-b4dd0f0eea2f.png)
