### ISSUE TITLE
[QT-Wallet] In Contact remove confirmation message, wordings need to be rephrased

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#389]
**Description:**
In QT wallet, while deleting a contact getting the warning message "Remove the selected contact for Test_1? Press 'Yes' to delete." instead it should display "Are you sure, you want to remove the contact Test_1? 

**Expected Result:**
1. In Contact remove confirmation message, wordings need to be rephrased as "Are you sure, you want to remove the contact XXXX? .
2. Confirmation message Title need to be left aligned, currently it is Center aligned.

Please refer the below screenshot.

![image](https://user-images.githubusercontent.com/63310656/84419240-f4e34280-ac35-11ea-8999-25c52661edf4.png)

**Comment by bayk** [comment]
The phrase is fixed.
The title is expected to be centered like in all our message boxes.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
