### ISSUE TITLE
[QT-Wallet] In new Contact addition page, need UI fixes.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#390]
**Description:**
In new Contact addition page, observed the following UI issues,

1. Title need to be changed from "NEW CONTACT" (all caps) into "New Contact".
2. Title need to be left aligned, currently it is center aligned.
3. "name" need to be renamed as "Name".
4.  "address" need to be renamed as "Address".

Please refer the below screenshot.

![image](https://user-images.githubusercontent.com/63310656/84419871-d598e500-ac36-11ea-91ff-897bcaae1996.png)

**Comment by scasaletto** [comment]
When you add or edit a contact, a dialog pops up. All dialogs have their titles centered, so I did not change the title location. I did change the case of the title as you suggest for both adding and editing a contact. Also made the changes you suggested for the fields.

**Comment by vinayaga07** [comment]
Verified and hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/84683318-aba43300-af54-11ea-8311-d7a348933e4e.png)
