### ISSUE TITLE
Sometimes TOR address is not populated on startup

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#392]
Sometimes the TOR field in the Receive UI is empty on startup. You can get it to load by clicking off the receive tab and back onto it.

Expected behaviour: as soon as TOR listener starts, the receive page should be refreshed automatically with the TOR address.

**Comment by bayk** [comment]
Should be fixed by now. 
Testing: Make receive page is current and open the wallet. Tor takes time to start, so you should see that tor address will be printed after the start.

**Comment by vinayaga07** [comment]
verified with the latest build and issue resolved, hence closing this ticket.

**Steps followed.**
Make receive page is current and open the wallet. Tor takes time to start, so you should see that tor address will be printed after the start.
