### ISSUE TITLE
TOR connect/disconnect functionality

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#394]
Need to add functionality to tor to auto-detect when the network is down/connection not working and print out an error message in mwc713.

Qt wallet needs to update status indicator for TOR based on this message. (similar to mwcmqs)

**Comment by cgilliard** [comment]
I will add the mwc713 functionality and re-assign to Konstantin when complete.

**Comment by electrum17** [comment]
This is working now in the latest build. Closing this out.
