### ISSUE TITLE
If there is another system with keybase listening to the same account as an mwc713 which you use to send a keybase transaction

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#396]
We are hopefully getting rid of keybase soon, so consider that when prioritizing.

Steps to reproduce:
have keybase listening to the same account on 2 systems, send a keybase transaction to another wallet.  

Result: the transaction will not confirm (most likely the response slate is going to the other system.

**Comment by cgilliard** [comment]
Keybase is low priority because it will go away in the next release.

**Comment by yyangli** [comment]
keybase has been removed from qt wallet, mwc713 and mwc-wallet
