### ISSUE TITLE
Can't change the auto-logout to anything except 20 minutes

### ISSUE THREAD

**Issue by electrum17** [mwcproject/mwc-qt-wallet#397]
Tried this on the 6-13.1 build and still not able to change the timeout from 20 minutes.

**Comment by vinayaga07** [comment]
Verified with the latest build and able to change the Auto logout Timeout setting.

![image](https://user-images.githubusercontent.com/63310656/84806432-4f5c1480-b023-11ea-8d15-1963dbf28c23.png)

Hence closing this ticket.
