### ISSUE TITLE
Drop changes screen appears when you click on "wallet confiuguration"

### ISSUE THREAD

**Issue by electrum17** [mwcproject/mwc-qt-wallet#398]
The "Drop changes" alert sometimes appears when you click on "Wallet configuration".

Expected Behaviour: "Drop changes" should only appear if you leave the configuration page, not when clicking on it.

<img width="865" alt="Screen Shot 2020-06-13 at 8 52 03 AM" src="https://user-images.githubusercontent.com/66847843/84573093-4df4c880-ad53-11ea-934f-a04f84108860.png">

**Comment by bayk** [comment]
we should block locking for this page. It is really trying to switch

**Comment by cgilliard** [comment]
Still seeing this. You can possibly reproduce by setting logout to "Never", then clicking off another tab, then clicking back to wallet configuration, then click transactions. It will say you are going to drop changes, even though you have not changed anything.

**Comment by vinayaga07** [comment]
With the latest build, have followed the following steps and not observed the issue.

1. -  logout to "Never", 
2. - then clicking off another tab,
3. -  then clicking back to wallet configuration,
4. -  then click transaction
