### ISSUE TITLE
Activate Foreign API if needed on start

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#399]
Needed for migration.
Foreign API will be configured automatically to match tor.  Or, if https is active, tor will be disabled.

**Comment by bayk** [comment]
Testing:
1. Enable TOR with default Foreign API.
2. Check of TOR was active after restart. 
3. Stop qt wallet
4. Modify  ~/mwc-qt-wallet/wallet713v2.toml  and disable foreign API settings
5. Start qt wallet and check that  Foreign API was activated.
------------------------------
1. Enable TOR with default Foreign API.
2. Check of TOR was active after restart. 
3. Stop qt wallet
4. Modify  ~/mwc-qt-wallet/wallet713v2.toml  and  define tls_certificate_file & tls_certificate_key
5. start qt wallet. Check that it show message about TOR deactivation. CHeck if tor is not running

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
