### ISSUE TITLE
Showing seed in wallet should require password

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#4]

**Comment by bayk** [comment]
will add, no problem. mwc713 require it.
I am thinking about logout by timeout if no action was performed. What do you think? I think it make sense.

**Comment by MWCmax** [comment]
I agree

**Comment by bayk** [comment]
Logout time will be 15 minute from the the moment when user stop switch pages.
Some pages will be exception because you might want wallet keep online forever. I am thinking about Recieve page.  Until you stay on those pages, timeout will never happen.
Also timeout setting will be in config. Let's not put it in UI

**Comment by bayk** [comment]
Exception pages is not good idea.  Point of that to have wallet running but at the same time locked.
To reach that goal we need not Logout by timeout, but Lock the GUI.  That will be the password request Page with listeners status. So wallet GUI is blocked and user can understand that wallet is online. As a result wallet can run in background.
I will prototype that, then we will see usability.

**Comment by cgilliard** [comment]
I think 15 minutes is ok without exception pages. Can you detect mouse
movements though? It might be irritating if you get logged out when you are
about to click.

**Comment by bayk** [comment]
I am resetting timer when user change pages. Let's try that first, will see the usability.  Mouse move we can detect as well, but that might not be related to this app. User might just hover over the app.
Let's start with simple solution. If it will not work well, we will add more logic.

**Comment by cgilliard** [comment]
Ok.

**Comment by bayk** [comment]
Fixed
