### ISSUE TITLE
user reporting notes disappear with new build

### ISSUE THREAD

**Issue by electrum17** [mwcproject/mwc-qt-wallet#402]
User reported that after upgrading to the nightly 1.0.22 beta builds, their notes for old transactions disappeared. New notes are there though.

**Comment by scasaletto** [comment]
In the new release, notes are saved in a different place and by a different key. This new place is in mwc-qt-wallet/context/notes.dat. Previously notes were saved in the app context in the file mwc-qt-wallet/context/context.dat. So the notes from older versions of Qt wallet needed to be migrated to their new format and location.

To test:
    Open and older version of Qt wallet and add some transaction and output notes, then exit the wallet.
    Now open the same wallet instance with the new version of Qt wallet. The notes should be migrated and you should be able to see them now using the new Qt wallet version.
    The transaction notes are actually migrated when you select the transaction screen. So if you open Qt wallet and don't go to that screen and then close the wallet again, you should not lose your notes. The next time you open the wallet and go to the transaction screen you should see that your notes have been migrated and appear ok.
    The output note migration is similar. It doesn't happen until you open the output window. If you open Qt wallet and never go to the output window, you will not lose your notes. When you finally do open Qt wallet and go to the output window, you will see your notes.

**Comment by annabay04** [comment]
I installed version 1.0.21, made multiple accounts, processed some transactions and left transaction and output notes. I then upgraded the wallet to v1.0.22 and all of the notes were still there.
