### ISSUE TITLE
Verify TOR floonet to mainnet send failure

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#405]
@cgilliard , I believe tor address prefix for TOR not implemented. 
But wallet still suppose to handle send from wrong network. 

This ticket is for testing. That is why it will have 'Fixed' status from the beginnigs.

**Comment by electrum17** [comment]
Yeah, I don't think it's possible to do right now. mwc713 can't distinguish between floonet/mainnet.

**Comment by cgilliard** [comment]
Also we should wait for Yang’s task to be complete because it will be a
different key. We can also reuse the mwc713 code at that time too.

**Comment by bayk** [comment]
Let's test how failure looks like.

**Comment by cgilliard** [comment]
Oh actually I tried it with Vinayaga..... So what happens is the
transaction will be confirmed on the sender's network but never confirm on
the receiver's network. Same as if you sent to an http listener that's on a
different network. The receiver can retrieve the coins by entering the seed
as the other network type.

**Comment by bayk** [comment]
Yes, make sense.
Do we want to fix that?  There is a similar low priority ticket about that.
In the slate we can add a network. So wallet at least will be able to
detect such mistakes.
But I don't know how it is needed. Do we want to cover that?

**Comment by cgilliard** [comment]
I think we should wait for Yang's feature. Then implement it correctly. For
now I think it's fine. Users don't normally use floonet, mostly developers
and there's a workaround, we can help them recover funds.

**Comment by bayk** [comment]
close because there is nothing to test now
