### ISSUE TITLE
Windows build failing

### ISSUE THREAD

**Issue by electrum17** [mwcproject/mwc-qt-wallet#406]
windows_desktop/x_walletconfig_w.cpp: In function 'bool wnd::checkKeyBasePath(QWidget*, QString)':
windows_desktop/x_walletconfig_w.cpp:64:71: error: no matching function for call to 'control::MessageBox::questionText(QWidget*&, const char [22], const char [176], const char [7], const char [14], bool, bool)'
                                "Cancel", "Use this path", true, false ) )

**Comment by jbyrer** [comment]
confirmed builds working with Chris
