### ISSUE TITLE
[QT-Wallet] Unable to send amount from one wallet to another.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#408]
**Description:** 
From QT-Wallet, Unable to send amount from one wallet to another and getting the error messages "Your send request was failed:
MQS unable to transfer slate 89605866-7695-45ea-b8c2-a15b05bc06cd to the worker, mwcmqs connection error Sender returned invalid response."

![image](https://user-images.githubusercontent.com/63310656/84685119-54ec2880-af57-11ea-85c3-380bf9dc0bd9.png)

![image](https://user-images.githubusercontent.com/63310656/84685305-b01e1b00-af57-11ea-86c2-50b691bac710.png)

**Comment by bayk** [comment]
Is it any specific about the wallets?

**Comment by vinayaga07** [comment]
MQS was down, hence unable to send amount.
Hence closing this ticket.
