### ISSUE TITLE
mwc713 taking too long message appears on login

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#409]
It seemed to appear very soon after clicking login. Times should be adjusted upwards.

<img width="741" alt="Screen Shot 2020-06-16 at 5 47 29 AM" src="https://user-images.githubusercontent.com/7232183/84776258-f0e85500-af94-11ea-8eaf-b38cfb3fc049.png">

**Comment by bayk** [comment]
Change mwc713 stopping timeout from 3 to 8 seconds. Reason: stopping tor listener might take more time

**Comment by vinayaga07** [comment]
Successfully verified with the latest build - https://ftp.mwc.mw/nightly_builds/06-19-2020/ , hence closing this ticket.
