### ISSUE TITLE
[QT-Wallet] "MWC" should be always in CAPS

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#411]
**Description:**
 "MWC" should be always in CAPS, but in the login screen it is in small case.
Please refer the screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/84800416-6bf44e80-b01b-11ea-8cba-1965c54a8015.png)

**Comment by bayk** [comment]
@mwc-design ,  I think it is a logo, so like this is fine?
