### ISSUE TITLE
Some desktop .ui files still refer to resources.qrc which no longer exists

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#413]
In the new architecture, resources.qrc has been changed to resources_desktop.qrc. However there are still some .ui files which refer to resources.qrc.

On Mac (probably works on Linux also), from the top-level mwc-qt-wallet directory run the commnd:
    grep -R "resources.qrc" .
This will display a list of the files which still refer to resources.qrc

**Comment by scasaletto** [comment]
The list of files I get are:
    core_desktop/mwctoolbar.ui
    windows_desktop/h_hodl.ui
    dialogs_desktop/w_selectcontact.ui
 
dialogs_desktop/helpdlg.h is also listed but it just has resources.qrc in a comment.

**Comment by scasaletto** [comment]
Opening any of the .ui files in Qt Creator causes an error saying the specified .qrc file cannot be found.

**Comment by vinayaga07** [comment]
@scasaletto,
With the latest QT wallet on Mac Platform, when I executed the command "grep -R "resources.qrc" ." from the top-level mwc-qt-wallet directory got the empty outputs. 


The list of below files are not getting listed,
- core_desktop/mwctoolbar.ui
- windows_desktop/h_hodl.ui
- dialogs_desktop/w_selectcontact.ui

Please let me know, whether those files are removed from latest QT wallet ?

**Comment by scasaletto** [comment]
@vinayaga07 These files still exist. When you run: grep -R "resources.qrc" .    You are ensuring that resources.qrc no longer shows up in these files. The fact that they are not listed when you run the command, confirms that the files have been fixed.

**Comment by vinayaga07** [comment]
Closing this ticket, as per the above mentioned comments.
