### ISSUE TITLE
[QT wallet] Send transaction failed, need error message correction.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#416]
**Description:**
Have tried sending MWC to the wallet where TOR services are stopped and got the below notification message.

![image](https://user-images.githubusercontent.com/63310656/84937801-f14e3080-b0f9-11ea-9855-50941aad9f39.png)

**Expected Result:**
Error message should be short and much more meaningful to the Users.

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/84960030-7a8f4400-b0b5-11ea-9af7-6e265d81a6b3.png)

**Comment by cgilliard** [comment]
Can we include some info for debugging though?

**Comment by cgilliard** [comment]
Or will full details be in the logs?

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/84960961-f5f1f500-b0b7-11ea-8cfe-6ecae1598004.png)

**Comment by bayk** [comment]
Logs will have the original error message in any case

**Comment by vinayaga07** [comment]
Verified and got the below error message, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/85054623-f7a3e180-b1b9-11ea-8943-d12fdf9885e3.png)
