### ISSUE TITLE
[Documentation]  How to configure api secret key for QT-Wallet.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#417]
**Description:**
Need a documentation/steps to be followed on how to configure api secret key for QT-Wallet.

![image](https://user-images.githubusercontent.com/63310656/84942085-f615e300-b0ff-11ea-8d57-e157de8675f0.png)

**Comment by bayk** [comment]
We talk with Chris,  documentation is not needed, instead we need to make our terms uniform.

![image](https://user-images.githubusercontent.com/42393608/84961424-17071580-b0b9-11ea-9f80-dc405832e087.png)


![image](https://user-images.githubusercontent.com/42393608/84961446-2a19e580-b0b9-11ea-8792-4e0d20ed53f5.png)

**Comment by annabay04** [comment]
The captions match the description according to the images and everything seems logical.
