### ISSUE TITLE
[QT wallet] [Windows] After logout from the wallet, sometime unable to login to the same wallet. 

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#418]
**Description:**
In QT-Wallet Windows platform, after logout from the wallet, sometime unable to login to the same wallet. Getting the below message continuously. 

![image](https://user-images.githubusercontent.com/63310656/85054066-19e92f80-b1b9-11ea-814b-a358880b8352.png)

**Logs**
[mwcwallet.log](https://github.com/mwcproject/mwc-qt-wallet/files/4800254/mwcwallet.log)

**Comment by bayk** [comment]
Note. All listeners better to be active to reproduce.

**Comment by jbyrer** [comment]
I experienced the same issue.  I believe Tor is taking a while to stop, the problem disappears for me after about 30 seconds, it seems to be when the second time the "taking to long" warning appears.

**Comment by vinayaga07** [comment]
Successfully verified and able to logout and login in QT wallet Windows platform. Hence closing this ticket.
