### ISSUE TITLE
Always display current receiving account

### ISSUE THREAD

**Issue by Jonbros01** [mwcproject/mwc-qt-wallet#420]
Often funds are not getting to the expected account,  it would be really helpful to always display the current receiving account anywhere in the wallet, even when if we are logged out of the QT wallet.  Maybe it could be display in the bottom bar ?

**Comment by bayk** [comment]
@mwc-design , what do you think about that?  Display at the bottom in not a problem, but it is already many elements there. 
I think we might should solve that issue with wallet selection and notification changes. 
If we start show notifications differently, we will have space at the status bar.

**Comment by bayk** [comment]
Receive account currently shown in the "Receive" page with addresses that can be used to receive the coins.
In the past we had different bug because of that funds sometimes were getting to any account and that was fixed a while ago.
Closing the ticket as fixed
