### ISSUE TITLE
[QT-Wallet] Copyright year (2020) need to be updated.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#421]
**Description:**
License Agreement page need to be updated Copyright for the year 2020, currently it is displaying 2019.

Please refer the below screenshot for more details.
![image](https://user-images.githubusercontent.com/63310656/85155061-e6200f80-b275-11ea-9e6e-1dd76969436c.png)

**Comment by electrum17** [comment]
Fixed. should be seen in next nightlys.

**Comment by vinayaga07** [comment]
Successfully verified with the latest build, hence closing this ticket.
