### ISSUE TITLE
[QT wallet] Need an option to select buttons All & Next using keyboard keys.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#424]
**User Experience:**
In QT wallet on "**Send**" Page (Mac platform), unable to navigate and select button "All" , "Next" using keyboad keys like "Tab" or "Arrow".
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/85316183-f20c0b80-b4d9-11ea-85bd-b22cfbfbf806.png)

**Expected Result**

- Need an option to select buttons All & Next using keyboard keys.

**Comment by bayk** [comment]
Please note, we get a checkbox there. It is in the focus loop as well

**Comment by vinayaga07** [comment]
In QT wallet on "Send" Page (Mac platform), able to navigate and select button "All" , "Next" using keyboad keys like "Tab". Hence closing this ticket.
