### ISSUE TITLE
Not able to receive file from mwc-wallet

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#43]
Was unable to receive a file based transaction from mwc-wallet. Got error "Unable to parse". There are several slate versions. mwc-wallet probably uses slightly different values than mwc713. We should be able to accept the transaction files from mwc-wallet directly into mwc-qt-wallet as well as mwc713 and support all slate versions. See screenshot below. mwc713 did accept the slate when used to directly receive the slate.

<img width="844" alt="Screen Shot 2019-08-22 at 12 21 07 AM" src="https://user-images.githubusercontent.com/7232183/63494737-302c3f00-c473-11e9-9693-64b27186be9b.png">

**Comment by cgilliard** [comment]
Slate versions can be specified in mwc713 and mwc-wallet with the -v option. Versions available are 0, 1, and 2:

send --help

or mwc-wallet send --help

**Comment by bayk** [comment]
Support v 0,1 & 2
