### ISSUE TITLE
 QT wallet Listeners page,selection of Keyboard key (Tab) navigation is irregular

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#430]
**User Experience:**
In QT wallet Listeners page,selection of Keyboard key (Tab) navigation is irregular. It starts from "keybase" stop button and then "MWC MQS" Stop button and then "Http" stop button.

**Expected Result:**
Focus should start from  "MWC MQS" Stop button, then "keybase" stop button and then TOR stop button and then  "Http" stop button. It should be in order.

![image](https://user-images.githubusercontent.com/63310656/85318687-0c47e880-b4de-11ea-84f1-40d344fed335.png)

**Comment by bayk** [comment]
Still an issue, will fix that.

**Comment by vinayaga07** [comment]
Verified with the latest build and observed Keyboard key (Tab) navigation is still not orderd.

**Actual Result:**
Focus started from "MWC MQS" Stop button,  "MWC MQS" address and then TOR stop button and then "Http" "Configure" button and then TOR address. 

**Expected Result:**
Focus should start from "MWC MQS" Stop button,  "MWC MQS" address and then TOR stop button , TOR Address and then "Http" "Configure" button. 

![image](https://user-images.githubusercontent.com/63310656/97726287-136aad00-1af5-11eb-9704-67ce2d476a70.png)

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
