### ISSUE TITLE
Re-sync with full node confirmation should default to Yes button

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#433]
Somewhere between releases, the default focus of the confirmation dialog when requesting to re-sync with the full node was changed from Yes to No.  The default focus should be changed back to the Yes button.

**Comment by scasaletto** [comment]
Committed the fix for this at the end of June but forgot to move this to fixed.

**Comment by vinayaga07** [comment]
Verified and the default focus is set to the Yes button. hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/87174226-7e009e80-c2f4-11ea-8375-459aa71f3424.png)
