### ISSUE TITLE
Minor UI bug - Addresses are being hidden, resizing column fixes issue

### ISSUE THREAD

**Issue by privateidentity** [mwcproject/mwc-qt-wallet#434]
In the contacts section of the wallet the column width seems to hide the details of the contact name and the address.
The fix appears to be to size the column  using larger default width values.

![addresses are hidden](https://user-images.githubusercontent.com/64110976/85718163-98058300-b731-11ea-9fc1-be256b3328d8.png)

**Comment by bayk** [comment]
Column with is not a problem to adjust. But the real solution is a changing of the formatting rule. I will try to find if it can be updated

**Comment by bayk** [comment]
Make column wider by default, so the address will fix.
The permanent solution will be better when we start with Swaps. Also Transactions and Outputs will need to have a mobile  wallet look. We will need a special control to address that. That custom control will be used in address page as well.

**Comment by vinayaga07** [comment]
Verified the Column width, hence closing this ticket.
