### ISSUE TITLE
confirmation and creation dates in mwc-wallet / mwc713 are innacurate

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#437]
They currently use the first time the transaction is viewed as opposed to the time the transaction was confirmed.

**Comment by bayk** [comment]
We need request node by confirmation height for the real confirmation time.

**Comment by yyangli** [comment]
Some conversation about fixing this bug:
We want to remain decentralized so cannot use the block explorer.
I think we can get the time from the block api.
Getting a real confirmation time might be a problem. I think we can only request header info from the node to get a time
Currently it is time - when we found that it is confirmed and it is not correct.
chris-dev06/25/2020
I think <node>/v1/headers/<block_num> will work.

**Comment by vinayaga07** [comment]
Verifiied the creation dates in mwc-wallet post txt, hence closing it.
