### ISSUE TITLE
finalize will not get to lock outputs because verify_slate_payment_proof is called first

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#438]
Current behaviour:

trying to finalize a slate that was generated by owner api, results in error message

Expected bevaviour:
finalize should succeed.

Steps to reproduce:

Create a slate via api:

curl -u mwc --request POST --data-raw '{"jsonrpc":"2.0","method":"init_send_tx","params":{"args":{"src_acct_name":null,"amount":100000000, "minimum_confirmations":1,"max_outputs":20,"num_change_outputs":1,"selection_strategy_is_use_all":false,"message":"Take money, please!","target_slate_version":null,"estimate_only":null,"send_args":null,"exclude_change_outputs":false, "minimum_confirmations_change_outputs": 1,"payment_proof_recipient_address":null,"ttl_blocks":1000}},"id":1}' http://127.0.0.1:3420/v2/owner

receive slate with another wallet.

finalize with first wallet:

mwc-wallet finalize -i slate.tx.response

You will see:

Wallet command failed: LibWallet Error, Payment Proof generation error: TxLogEntry with original proof info not found (is account correct?)

**Comment by bayk** [comment]
Works fine now.
