### ISSUE TITLE
mac-wallet owner rest API init_send_tx failed 

### ISSUE THREAD

**Issue by yyangli** [mwcproject/mwc-qt-wallet#439]
Command used:
curl -u mwc:JjbqaBqczSe7I0xlLJuR --request POST --data-raw '{"jsonrpc":"2.0","method":"init_send_tx","params": { "args": {"src_acct_name":null,"amount":"600","minium_confirmations":2,"max_outputs":500,"num_change_outputs":1,"selection_strategy_is_use_all":true,"message":"my message","target_slate_vesion":null, "payment_proof_recipient_address":"xmgJ11o4rR7jEhUTz2GDrScYoGXtSGB462REcn1egiK7D5Wucgqn","ttl_blocks":null,"send_args":{"method":"mwcmqs","dest":"xmgJ11o4rR7jEhUTz2GDrScYoGXtSGB462REcn1egiK7D5Wucgqn","apisecret":null,"finalize":true,"post_tx":true,"fluff":false},"address":null,"estimate_only":false }}, "id":"curltext"}' http://127.0.0.1:3420/v2/owner -v

or:
curl -u mwc:JjbqaBqczSe7I0xlLJuR --request POST --data-raw '{"jsonrpc":"2.0","method":"init_send_tx","params": { "args": {"src_acct_name":null,"amount":"600","minium_confirmations":2,"max_outputs":500,"num_change_outputs":1,"selection_strategy_is_use_all":true,"message":"my message","target_slate_vesion":null, "payment_proof_recipient_address":null,"ttl_blocks":null,"send_args":{"method":"mwcmqs","dest":"xmgJ11o4rR7jEhUTz2GDrScYoGXtSGB462REcn1egiK7D5Wucgqn","apisecret":null,"finalize":true,"post_tx":true,"fluff":false},"address":null,"estimate_only":false }}, "id":"curltext"}' http://127.0.0.1:3420/v2/owner -v

Error: TxLogEntry with original proof info not found (is account correct?)
[wallet_data.zip](https://github.com/mwcproject/mwc-qt-wallet/files/4838266/wallet_data.zip)

**Comment by bayk** [comment]
Hi @yyangli 
Currently it fails on signature verification step 

mwc-wallet/libwallet/src/internal/tx.rs

fn verify_slate_payment_proof

crypto::verify_signature(&msg, &signature, &receiver_pubkey)
				.map_err(|e| ErrorKind::TxProofVerifySignature(format!("{}", e)))?;

crypto::verify_signature return that signature doesn't match the message and public key. 
I believe original problem is solved, so it is what you working on now. 

Assigning back to you

**Comment by yyangli** [comment]
This should have been fixed with the complete of proof feature.
