### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#44]
Need a way to deal with versioning. I have a build number that I can pass in during the build process. The debian/redhat systems require that we increment build versions. Right now, here's what I'm using for them: 1.0-5.beta.$BUILD_NUMBER where BUILD_NUMBER is supplied by Azure. The value looks like this: 1.0-5.beta.20190822.14
The debian package looks like this:
mwc-qt-wallet-1.0-5.beta.20190822.14-linux64-08-22-19.deb

Would like to use this for all platforms. Is there a way to pass this parameter into mwc-qt-wallet at build time so it can be displayed just as the version in the filename?

**Comment by bayk** [comment]
I am thinking about the file
build_number.h
With content:
#define BUILDNUMBER  0

The file will be at the root of mwc-qt-wallet  project and will be checked in.

The build scripts will be overwrite its content with real build number, something like this.
#define BUILDNUMBER  20190822

Is it ok?

**Comment by bayk** [comment]
Created:
/mwc-qt-wallet/build_version.h
with content:

#define BUILD_NUMBER  0

Build system can overwrite the value and it will be putted into the tittle

**Comment by cgilliard** [comment]
It's ok, but azure gives us a number that looks like this: "20190822.14" So if it's a string it will be easier to implement.

**Comment by cgilliard** [comment]
Actually I also need the version number too because for instance in NSIS we pass the version number.

**Comment by bayk** [comment]
let's make content

#define BUILD_NUMBER  ""

**Comment by bayk** [comment]
With NSIS we can read this file and parse the version.
File will have a single line, it should be fine. NSIS has some capability to parse strings.

**Comment by cgilliard** [comment]
Ok, that works. So in the current version BUILD_NUMBER would be set to
1.0-5.beta build 20190824.2 for instance right?

**Comment by bayk** [comment]
Yes. That what we will be shown.
You will specify the fill version with major and minor, right?

**Comment by cgilliard** [comment]
Yep, perfect.

**Comment by bayk** [comment]
Great, so the content will be something like this (let's name it BUILD_VERSION)

#define BUILD_VERSION  "1.0-5.beta build 20190824.2"

And the title will be:

mwc wallet v1.0-5.beta build 20190824.2

**Comment by bayk** [comment]
@cgilliard ,  /mwc-qt-wallet/build_version.h is pushed. Please update the build scripts and then we will close an issue.

**Comment by cgilliard** [comment]
Getting a compile error:

Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers
-I. -I../../../Qt/5.9/clang_64/mkspecs/macx-clang
-F/Users/christophergilliard/Qt/5.9/clang_64/lib -o a_initaccount.o
state/a_initaccount.cpp

*state/a_initaccount.cpp:184:32: **error: **too few arguments to function
call, expected 2, have 1*

                        seed ) );

*                               ^*

*state/../core/windowmanager.h:36:5: note: *'switchToWindowEx' declared here


Not sure if it's related to my environment or not.

**Comment by bayk** [comment]
Sorry, didn't test release build. Will fix soon

**Comment by cgilliard** [comment]
Looks like it just needed a title. I checked in this change which I think
is the one you were going to add to fix the build:

*diff --git a/state/a_initaccount.cpp b/state/a_initaccount.cpp*

*index 11c382a..be85a23 100644*

*--- a/state/a_initaccount.cpp*

*+++ b/state/a_initaccount.cpp*

@@ -179,7 +179,7 @@ void InitAccount::submit(QString word) {

         }



         // switch to 'show seed' window

-        context->wndManager->switchToWindowEx(

+        context->wndManager->switchToWindowEx(mwc::PAGE_A_INIT_ACCOUNT,

             new wnd::NewSeed( context->wndManager->getInWndParent(), this,
getContext(),

                         seed ) );

         return;

If that's not correct, please update.

**Comment by cgilliard** [comment]
Tried to run locally, getting this error:

**Comment by cgilliard** [comment]
Here is my mwc-gui-walletv2.conf:

mwc_path = "build in"

wallet713_path = "build in"

airdrop_url = "https://seed2.mwc.mw:8443"


# Logout timeout in seconds. Put non positive number to disable it

logoutTimeout = 900


# If you have slow hardware or network, please increase this value to
eliminate timeout messages from the wallet

timeoutMultiplier = 1.0

**Comment by cgilliard** [comment]
After deleting my mwc-qt-wallet directory it seems to work. I guess we tell
users to delete this directory if they already have it installed? There are
only a few users, but in the future we'll probably have to deal with this
as migration.

**Comment by bayk** [comment]
That was because of   airdrop_url = "https://seed2.mwc.mw:8443"
There is another 2 keys instead of it.
Yesterday I send an email about migration

**Comment by bayk** [comment]
Currently we don't have users, only we are. In the future we can have toml with next version. 
Currently I don't want to bump versions.

**Comment by cgilliard** [comment]
Yeah, I saw the email. There are a few others who installed. For the
release, lets name the directory something else so we avoid conflicts.

**Comment by bayk** [comment]
I rename  mwc-gui-wallet-v2.conf  to mwc-gui-wallet-v3.conf.
That will help

**Comment by cgilliard** [comment]
Technically we don't know if there are others who installed the wallet
because anyone could have downloaded it. I mentioned the nightly builds
directory in an article last night.

**Comment by bayk** [comment]
Just update the version for  mwc-gui-wallet-v3.conf
Now for debug we will need to update the mwc713 binary location.
Installer will be fine, should run without errors and wallet data should be be fine

**Comment by bayk** [comment]
I get the point. Assuming that we have have users so we will migrate.

**Comment by cgilliard** [comment]
build_version.h is now being updated in the pipeline. Closing this issue.
