### ISSUE TITLE
tor sending failure

### ISSUE THREAD

**Issue by yyangli** [mwcproject/mwc-qt-wallet#440]
recipient wallet tor is listening(just restarted the wallet)
wallet713> send 0.01 --to http://a3renimariif7r5dy4lk5m2nioq5nuebciiiuq7vpjjcg3whmxps2nyd.onion
Error: Adapter Callback Error, Performing version check (is recipient listening?): Request error: Cannot make request: error trying to connect: deadline has elapsed
Backtrace:    0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: failure::backtrace::Backtrace::new
   4: grin_wallet_impls::adapters::http::HttpSlateSender::check_other_version
   5: <grin_wallet_impls::adapters::http::HttpSlateSender as grin_wallet_impls::adapters::SlateSender>::send_tx
   6: mwc713::do_command
   7: mwc713::main
   8: std::rt::lang_start::{{closure}}
   9: std::panicking::try::do_call
  10: ___rust_maybe_catch_panic
  11: std::rt::lang_start_internal
  12: _main

after restart the sending wallet, the sending went fine.

**Comment by cgilliard** [comment]
It was a timeout error. The tor network timed out. This is expected behavior.
