### ISSUE TITLE
qt wallet on exit should always wait for mwc713 to exit

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#442]
If mwc713 executing a long task, qt wallet can kill it. 
It allow to exist qt wallet during relatively short time, but there is a small chance for the data corruption.

We think it is better to wait. QT wallet will show the message about needed waiting abs will wait as long as needed and then exit nicely from mwc713 wallet.

@vinayaga07 , just FYU, exit might start occasionally take longer time because of that.

**Comment by bayk** [comment]
Revert back the waiting for the last wallet task even it can be long.

To cover original  @vinayaga07  concern, I add the message box that will be active until wallet will exit

![image](https://user-images.githubusercontent.com/42393608/91516275-dccba880-e89f-11ea-85f7-d3b8bb949d18.png)

**Comment by bayk** [comment]
Testing:

Open the wallet and start long operation. For example, resync task is good for that, it will take about 30 minutes to finish.
So start resync with wallet and exit. Then you should see that message that will be active for a while. Then it should disappear and wallet should exit

**Comment by bayk** [comment]
Just trigger the build. So Nightly will be ready in an hour.

**Comment by vinayaga07** [comment]
Got the below error message before wallet exit. Hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/93114198-ee9eaf80-f6d7-11ea-8e61-262da2fca491.png)
