### ISSUE TITLE
[Qt-Wallet] Transaction failed error messages need to be updated.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#444]
**Description:**
Tried TTL Blocks with lesser values and observed Transaction failed in the receiver side with the below message,

![image](https://user-images.githubusercontent.com/63310656/86041250-019fcd00-ba63-11ea-9bda-e5dcc997778a.png)

**Expected Result:**
Error messages should be simple and easy to understand. Current error messages need to be updated with some word rephrasing.

**Comment by bayk** [comment]
New message  
![image](https://user-images.githubusercontent.com/42393608/97221445-1d557e80-178a-11eb-976b-2bb658a541d6.png)

Note, error massage mapping is done on QT wallet side.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/97727321-4a8d8e00-1af6-11eb-91f8-86cc79c7d489.png)
