### ISSUE TITLE
production values for claims

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#45]
We need to implement production values for claims servers. Let's do the following:

mainnet -> Use the following server: https://wallet.mwc.mw and obey the claimsAvailable flag as documented here: https://github.com/starrymoonlight/mwcairdrop/blob/master/DOC/ClaimsVersion2
https://wallet.mwc.mw/v1/claimsAvailable

testnet -> remains https://seed2.mwc.mw:8443

**Comment by bayk** [comment]
ok. There will be two setting into config file:
airdrop_url_mainnet  & airdrop_url_testnet
