### ISSUE TITLE
Incorrect send amount displayed when ALL selected

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#452]
In the send screen, select to send ALL coins for an account. Sometimes the amount will be greater than the actual available amount.

**Comment by scasaletto** [comment]
The issue can be seen when the number of inputs used in the send is greater than:
    (4*changeOutputs) + 1
In the case of ALL changeOutputs will be 1, so you can see the issue if the coins to send are in 6 or more outputs. When calculating the weight for the transaction fee, I was using an unsigned int instead of a signed int. So a comparison in the calculation of the transaction fee was failing when it was checking for values less than 1 because a value which should have been negative ended up being a really large unsigned value.
Fixed the variable type and tested with 24 inputs.

**Comment by jbyrer** [comment]
This may not pertain to the original problem, however the description is basically the same, so I am updating here.  This test used the miner wallet.  When selecting all, the amounts were not quite the same, off by a thousandth of a coin.  I can see how it might be related to rounding issues.  Although I know the difference is small, I think this might generate service calls (or Discord/Telegram DMs) 

![image](https://user-images.githubusercontent.com/10661009/97502324-26805000-1930-11eb-9071-3c49a4cb0a0e.png)

**Comment by jbyrer** [comment]
I do seem to be able to change the amount manually, therefore not marking this as critical

**Comment by jbyrer** [comment]
my bad, S pointed out that this is because of the transaction fee.  Closing
