### ISSUE TITLE
Inconsistent spelling of Tor in messages

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#456]
I see three different spellings of Tor being used in messages: Tor, tor and TOR.
I believe the correct spelling is Tor according to torproject.org so we should fix so spelling is consistent.

**Comment by scasaletto** [comment]
Modified all user visible strings which refer to Tor to use the spelling "Tor" and not "tor" or "TOR". Files were modified in mwc-wallet, mwc713, and mwc-qt-wallet.

**Comment by vinayaga07** [comment]
Observed **TOR** in QT wallet.

![image](https://user-images.githubusercontent.com/63310656/90267560-5bbdeb80-de73-11ea-85ec-8e307a972d0f.png)

**Comment by vinayaga07** [comment]
Still observing the issue, hence re-opening this ticket.

![image](https://user-images.githubusercontent.com/63310656/93915646-f38ddf80-fd25-11ea-8f41-c3ec90b1211e.png)

**Comment by scasaletto** [comment]
TOR in the list of listeners at the bottom is now spelled Tor.

**Comment by vinayaga07** [comment]
Successfully verified with the latest build, hence closing this ticket.
