### ISSUE TITLE
Crash when switching between online wallet and cold wallet and vice versa

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#458]
![Snip20200730_12](https://user-images.githubusercontent.com/7772099/88985079-0f7c8400-d295-11ea-95c7-6c86163f4c08.png)

**Comment by electrum17** [comment]
ried to switch to cold storage mode and I got stuck in a loop telling me that my node is not loading and i kept switching to the dev node, but it didn't make the change.
The only way out was to modify the wallet713v2.toml file and create a new instance.

**Comment by vinayaga07** [comment]
Not observing crash while switching between online and cold wallet with the latest build.
Hence closing this ticket.
