### ISSUE TITLE
Account combo boxes reset after some time

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#459]
In the accounts transfer page the from and to account fields get cleared if you wait for a short time.

**Comment by scasaletto** [comment]
Maybe related to an issue that was fixed for the Send screen and may need to be propagated to the Account transfer screen. See https://github.com/mwcproject/mwc-qt-wallet/issues/349

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
