### ISSUE TITLE
Accounts combo box resets to default account in Outputs screen

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#460]
In the Outputs screen, select a non-default account in the account combo box. After a short period of time, the account will be reset to the default account but the outputs displayed remain for the original account.
When fixing this issue, need to check that all account combo boxes in all screens do not get reset to the default account (e.g. transactions screen, send, etc.)

**Comment by vinayaga07** [comment]
Verified the below screens,

- Transactions

- Outputs

- Send.

Hence closing this ticket.
