### ISSUE TITLE
[QT wallet] "Send MWC by file" failed

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#462]
**Description:**
In QT wallet, "Send MWC by file" failed on Receiving end.

![image](https://user-images.githubusercontent.com/63310656/89212186-ab352980-d5e0-11ea-9b92-deeecf3112c1.png)

**Comment by electrum17** [comment]
Fixed: https://github.com/mwcproject/mwc-qt-wallet/commit/b13ccab1d8cdc79066a1f44ccde3889a85af65dc

**Comment by vinayaga07** [comment]
Able to send via File on the latest QT build, hence closing this ticket.
