### ISSUE TITLE
n_child is sometimes wrong

### ISSUE THREAD

**Issue by electrum17** [mwcproject/mwc-qt-wallet#464]
/// Last part of the path (for last n_child)
        pub fn last_path_index(&self) -> u32 {
                if self.depth == 0 {
                        0
                } else {
                        <u32>::from(self.path[self.depth as usize - 1])
                }
        }
can cause the wallet. to create the n_child at the wrong place.

**Comment by bayk** [comment]
Test results:
Broken data before scan
Wallet Outputs:
OutputData { root_key_id: Identifier(0200000000000000000000000000000000), key_id: Identifier(0300000000000000000000000100000000), n_child: 1, commit: Some("08a0724a71ae7d606e5c97f984bcef54baf8a706a72bc23142921f47142e53098d"), mmr_index: None, value: 96000000, status: Unspent, height: 467449, lock_height: 0, is_coinbase: false, tx_log_entry: Some(0) }
OutputData { root_key_id: Identifier(0200000000000000000000000000000000), key_id: Identifier(0300000000000000000000000400000000), n_child: 4, commit: Some("088e84ba9ad99e3816ce37cb7e28c66406504d0ede8e5732ac9d4ffbaeafc395ca"), mmr_index: None, value: 100000000000, status: Unconfirmed, height: 508891, lock_height: 0, is_coinbase: false, tx_log_entry: Some(1) }
OutputData { root_key_id: Identifier(0200000000000000000000000000000000), key_id: Identifier(0300000000000000000000000500000000), n_child: 5, commit: Some("08c5769e9a89f07a9eb88d7fd28a12524d38ef7b347bee1edf92788a2967470f85"), mmr_index: None, value: 10000000000, status: Unspent, height: 508893, lock_height: 0, is_coinbase: false, tx_log_entry: Some(2) }

The data after scan 
OutputData { root_key_id: Identifier(0200000000000000000000000000000000), key_id: Identifier(0300000000000000000000000000000000), n_child: 0, commit: Some("08a0724a71ae7d606e5c97f984bcef54baf8a706a72bc23142921f47142e53098d"), mmr_index: None, value: 96000000, status: Unspent, height: 467449, lock_height: 467449, is_coinbase: false, tx_log_entry: Some(0) }
OutputData { root_key_id: Identifier(0200000000000000000000000000000000), key_id: Identifier(0300000000000000000000000400000000), n_child: 4, commit: Some("088e84ba9ad99e3816ce37cb7e28c66406504d0ede8e5732ac9d4ffbaeafc395ca"), mmr_index: None, value: 100000000000, status: Unconfirmed, height: 508891, lock_height: 0, is_coinbase: false, tx_log_entry: Some(1) }
OutputData { root_key_id: Identifier(0200000000000000000000000000000000), key_id: Identifier(0300000000000000000000000500000000), n_child: 5, commit: Some("08c5769e9a89f07a9eb88d7fd28a12524d38ef7b347bee1edf92788a2967470f85"), mmr_index: None, value: 10000000000, status: Unspent, height: 508893, lock_height: 508893, is_coinbase: false, tx_log_entry: Some(2) }


Output  08a0724a71ae7d606e5c97f984bcef54baf8a706a72bc23142921f47142e53098d  changes n_child and key_id as expected. Now we can spend this output without any problems.
