### ISSUE TITLE
Wallet Instances support for QT wallet

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#465]
QT wallet need to have friendly switch to wallet instances

**Comment by bayk** [comment]
Testing.  This ticket includes Both new instances and  mwc-node connection related changes.

Testcases:
1. Migration.  Upgrade the wallet to this one and check if it found all wallet location from ~/mwc-qt-wallet.   Wallet names will be equal to directory names.
Then go to configs and change the instance names to the Any name that you like. For instances you can use Unicode symbols.

2.  Very first run. Delete all the data from  ~/mwc-qt-wallet.   The first screen should be similar to what is defined for the mobile  https://www.figma.com/file/e7ONL5huxvRDFfst4Iuo01tJ/wallet?node-id=1584%3A0

3. Check Create/Restore new instances workflow.

4. Try to import the wallet data from another location.  It should be clear from UI how to do that.

5. Try USB stick case. Create a new wallet on USB drive. Do something. Close the wallet. Unmount the stick. Chekc if wallet handle that correctly. Mount it back and check if wallet handle that well.

------------------------------------------------------------------------------

Node tescases.
1. Try to switch between Online Wallet, Cold Wallet and Online Node AND floonet/mainnet.   Validate that all those 6 modes can have different settings and switch between them.

2. Check if it recovered after crash with embedded MWC node.  Start QT wallet, do something and simulate the crash by killing the qt wallet process. Check if embedded mwc node still running.   QT wallet should be able to start with some reasonable delay. Go to the Node info and check if you can see the node logs.

**Comment by vinayaga07** [comment]
Verified the possible QT wallet instances, hence closing this ticket.
