### ISSUE TITLE
Swaps Testing: Validate if swap resulting outputs and transactions has correct amount

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#466]
Testing:

Do swap with redeem. Check outputs & tx amount. Send ALL coins to another wallet. Check if Slate was accepted by the chain.

Do swap with refund. Check outputs & tx amount. Send ALL coins to another wallet. Check if Slate was accepted by the chain.

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
