### ISSUE TITLE
When internet down, TaskList fails causing popup and wallet exit

### ISSUE THREAD

**Issue by electrum17** [mwcproject/mwc-qt-wallet#468]
![image](https://user-images.githubusercontent.com/66847843/89750139-8b3db400-da7f-11ea-9ede-aeafa67cc59f.png)

This message is displayed if the internet is not working. Would be better to just log the error and continue on in the case that TaskAccountList (or other background threads) fail.

**Comment by bayk** [comment]
Works fine now. Probably was fixed.
