### ISSUE TITLE
[MWC-WALLET] CLI - Help text for swap needs gramatical and spelling corrections

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#470]
Current text: 
Modify the swap trade workflow. Normally it is not needed. Sometimes you can use 'cancel'. We do not
            recommend adjusting unless you know ehat you are doing

Expected: ...Normally this should not be necessary.....   you know what you are doing.

**Comment by hcasalet** [comment]
Pushed in the changes. Please check and approve. :)

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
