### ISSUE TITLE
[MWC-WALLET] AUTO-SWAP Error when transferring (seller side)

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#471]
When doing auto swap, after the transaction completed on the buyers side, the error below showed up on the sellers side.  In addition the seller never received the funds in the electrum wallet.

mwc-wallet> Swap Trade ca56d5de-293b-409a-9556-828f49fdfde1: Offer message was sent
Swap Trade ca56d5de-293b-409a-9556-828f49fdfde1: Waiting for Accept Offer message
Processed income message for SwapId ca56d5de-293b-409a-9556-828f49fdfde1
Swap Trade ca56d5de-293b-409a-9556-828f49fdfde1: Processed Offer Accept message
Swap Trade ca56d5de-293b-409a-9556-828f49fdfde1: MWC lock slate is posted
Swap Trade ca56d5de-293b-409a-9556-828f49fdfde1: Waiting for MWC Lock transaction to be confirmed; Waiting for BCH Lock transaction to be posted
Swap Trade d0727cca-144e-4fd8-b864-7c47a15bf497: MWC and BCH funds are Locked
Swap Trade d0727cca-144e-4fd8-b864-7c47a15bf497: Waiting for Init Redeem Message
Swap Trade ca56d5de-293b-409a-9556-828f49fdfde1: MWC funds are locked; Waiting for BCH Lock transaction to be posted
Swap Trade ca56d5de-293b-409a-9556-828f49fdfde1: MWC funds are locked; BCH Lock transaction is in the memory pool, waiting to be mined
Processed income message for SwapId ca56d5de-293b-409a-9556-828f49fdfde1
Swap Trade ca56d5de-293b-409a-9556-828f49fdfde1: Init Redeem message is accepted
Swap Trade ca56d5de-293b-409a-9556-828f49fdfde1: Send response to Redeem message
Swap Trade ca56d5de-293b-409a-9556-828f49fdfde1: Waiting for Buyer to redeem MWC. If get no response, will post refund slate in 0 minutes
20200811 08:51:33.101 ERROR grin_util::logger - 
thread 'unnamed' panicked at 'dispatch dropped without returning error': <::std::macros::panic macros>:2   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: grin_util::logger::send_panic_to_log::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   6: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
   7: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
   8: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   9: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  10: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  11: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
  12: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  13: <hyper::client::ResponseFuture as core::future::future::Future>::poll
  14: <std::future::GenFuture<T> as core::future::future::Future>::poll
  15: std::thread::local::LocalKey<T>::with
  16: tokio::macros::scoped_tls::ScopedKey<T>::set
  17: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  18: tokio::runtime::context::enter
  19: crossbeam_utils::thread::ScopedThreadBuilder::spawn::{{closure}}
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: ___rust_maybe_catch_panic
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  24: std::sys::unix::thread::Thread::new::thread_start
  25: __pthread_start

Thread 'unnamed' panicked with message:
"dispatch dropped without returning error"
See /Users/jbyrer/swaptest/mwc-wallet.log for further details.
20200811 08:51:33.101 ERROR grin_util::logger - 
thread 'wallet-auto-swap' panicked at 'called `Result::unwrap()` on an `Err` value: Any': impls/src/client_utils/client.rs:401   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: grin_util::logger::send_panic_to_log::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: _rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: std::panicking::try::do_call
   8: ___rust_maybe_catch_panic
   9: grin_wallet_impls::client_utils::client::Client::send_request
  10: grin_wallet_impls::client_utils::client::Client::post
  11: grin_wallet_impls::node_clients::http::HTTPNodeClient::get_kernel_impl
  12: <grin_wallet_impls::node_clients::http::HTTPNodeClient as grin_wallet_libwallet::types::NodeClient>::get_kernel
  13: grin_wallet_libwallet::swap::bitcoin::api::BtcSwapApi<C,B>::get_slate_confirmation_number
  14: <grin_wallet_libwallet::swap::bitcoin::api::BtcSwapApi<C,B> as grin_wallet_libwallet::swap::api::SwapApi<K>>::request_tx_confirmations
  15: grin_wallet_libwallet::api_impl::owner_swap::swap_process
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
  17: std::panicking::try::do_call
  18: ___rust_maybe_catch_panic
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
  20: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  21: std::sys::unix::thread::Thread::new::thread_start
  22: __pthread_start

Thread 'wallet-auto-swap' panicked with message:
"called `Result::unwrap()` on an `Err` value: Any"
See /Users/jbyrer/swaptest/mwc-wallet.log for further details.

**Comment by jbyrer** [comment]
[mwc-wallet.log](https://github.com/mwcproject/mwc-qt-wallet/files/5058007/mwc-wallet.log)

**Comment by hcasalet** [comment]
Checked in the fix. Please verify. Thanks.

**Comment by jbyrer** [comment]
verified
