### ISSUE TITLE
Status notification windows display on top of other apps.

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#473]
When Qt Wallet is open, the status notification windows should not display on top of other apps that may also be open. The status notification that appears when the wallet is iconified is the only thing that should display on top of other apps.

**Comment by scasaletto** [comment]
Tried several ways to prevent the status message from appearing on top of other apps when the wallet is not iconified. So far best working approach causes statuses to not be displayed when the wallet is up but you are working in a different window.
A possible option to try is using QDockWidget. See https://stackoverflow.com/questions/26064386/place-non-modal-qdialog-window-only-on-top-of-my-application-instead-of-all-appl?rq=1
However, this will take time to figure out.
Chris says to move this to low priority for now.

**Comment by scasaletto** [comment]
On Linux, instead of using the window flag of Qt::SubWindow, Qt::Tool works better and notifications do not pop-up on top of other apps. Also there was a problem with the windows not being repositioned correctly which changing this flag also fixed.

**Comment by scasaletto** [comment]
The same fix for Linux relating to notifications appearing on top of other apps is used for Windows. Notifications will not appear on top of other windows now on Windows also.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
