### ISSUE TITLE
[MWC-WALLET] after an auto swap is initiated, the swap id is given to the user as a warning rather than an info

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#474]
Talked to K, he agreed it should be info

mwc-wallet> swap_start --mwc_amount .01 --secondary_currency bch --secondary_amount 0.0001  --mwc_lock_confirmations 1 --secondary_lock_confirmations 1 --message_exchange_time 60 --redeem_time 60 --secondary_address mxz64SWzbwcQTVtAy6dxYAUfFjxypWbRuR --who_lock_first seller
20200812 11:47:25.531 **_WARN_** grin_wallet_controller::command - Seller Swap trade is created: 5d0fc0b5-8af7-4871-a817-ea6515a15788
Command 'swap_start' completed

**Comment by hcasalet** [comment]
Fixed the issue to display the message without "warn". Please verify.
