### ISSUE TITLE
[QT wallet]  Unable to save Node network as Floornet.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#476]
**Description:**
In the "Node network", after selecting "Floornet" QT wallet is getting restarting and Node network--> Floornet is not getting saved.

**Steps to be followed,**

1. Select the Running node "Online Node - that provides blockchain data for cold wallet" option.
![image](https://user-images.githubusercontent.com/63310656/90166460-e93c0580-ddb7-11ea-9677-76548d91c0ac.png)

2. Select the Node network from the Configuration menu.
3. Select Node network--> Floornet... and then click Apply Button.

![image](https://user-images.githubusercontent.com/63310656/90166629-2a341a00-ddb8-11ea-8a57-462b1bc14f13.png)

**Note:**
Unable to 'Save Blockchain Data' for MWC Floonet network.

**Comment by vinayaga07** [comment]
[mwc-server.log](https://github.com/mwcproject/mwc-qt-wallet/files/5070512/mwc-server.log)

**Comment by bayk** [comment]
Update. Currently it is impossible to switch to the floonet at all.  
Also I will store the last network type for the Online Node.

**Comment by bayk** [comment]
@vinayaga07 , I found another minor UX issue. at step 'Select Node network--> Floornet... and then click Apply Button.'  node restart takes time (for me it is few seconds). We should show progress in this case, some pages might miss it.
I will update this page. But if you found such problem, please rise a ticket.

**Comment by bayk** [comment]
@vinayaga07 , the nightly is ready.
For the test please switch first to the Wallet and then to the Online Node and do the testing.

**Comment by vinayaga07** [comment]
@bayk ,
With the latest build, followed the below steps,

1. Logged into QT wallet (floonet)
2. Select the Running node "Online Node - that provides blockchain data for cold wallet" option.
3. Select the Node network from the Configuration menu.
4. Select Node network--> Floornet... and then click Apply Button.
5. Got the below error message,

![image](https://user-images.githubusercontent.com/63310656/90415811-404f1c80-e0cf-11ea-8d7a-61ecce4db0ef.png)

**Comment by bayk** [comment]
Just try and wan't be able to reproduce.
Please reproduce and attach the logs.

**Comment by bayk** [comment]
Hi @vinayaga07 ,
I was able to reproduce the issue when I clean up all the data. In this case every Online Node start will cause this problem. The next restart will be fine.
I hope it is a root problem.

**Comment by vinayaga07** [comment]
@bayk ,  This fix available in Today's build ?

**Comment by vinayaga07** [comment]
Successfully verified with the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/91469740-689a0080-e8b1-11ea-822f-1dcecb12fd01.png)
