### ISSUE TITLE
Swaps Journal need to include swap commands error.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#478]

**Comment by bayk** [comment]
Now journal will log all errors that occur during the processing stage.


-------- Trade Journal --------
    August 14 14:02:19  Swap offer is created
    August 14 14:03:03  Offer message was sent
    August 14 14:05:38  Processing error: Swap Error , Swap generic error, Please define '--message_file_name' value if you you are processing income message from the file

Journal length will be capped on 1000 messages because we might get too many errors.

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
