### ISSUE TITLE
[MWC-WALLET] Swap (useability) We should not have a default method for sending

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#479]

**Comment by jbyrer** [comment]
ran the command 
swap --process --dest xmfcZq9XPXZNF7xKdH25NbJaHGzbJapZcoFT3hfRi95FCbEvf9RS --secondary_fee_per_byte 1 -i 57b9b64d-c208-437c-863e-4a9fbe657e4d

without specifying method and it was assumed I was using file.  I talked to K and he believes this is confusing and we should not have a default.

**Comment by hcasalet** [comment]
Ok, agree. I will remove the default from --method.

**Comment by hcasalet** [comment]
Pushed in the fix. Please verify. Thanks!

**Comment by jbyrer** [comment]
verified
