### ISSUE TITLE
remove keybase listener warning modal

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#48]
This modal that says "Keybase listener is not listening, consider installing it first" can be removed. Some users will not install keybase and I don't think we should show this modal every time. I think a notification in wallet events is fine here.

**Comment by cgilliard** [comment]
Actually, I just realized it looks like this modal only appears once correct? If so I think it's fine to display once, just not after you have seen it the first time.

**Comment by cgilliard** [comment]
So, if that's correct and it's displayed once this issue can be closed.

**Comment by bayk** [comment]
Chris.  The modal dialog with message shown only when you manually try to start Keybase listener. 
But also there is a message at notifications with critical level, that highlight the icon. That message will be every start.  I will change Level from critical to info. So it will not highlight the icon
