### ISSUE TITLE
[Qt-Wallet] Online wallet is not syncing after transaction completed.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#482]
**Description:**
After sending MWC from online wallet to cold wallet using send via File option, online Node wallet Block count is not getting increased.

In Online node wallet, transaction got confirmed, whereas Cold wallet transaction is in unconfirmed state. (even after loading Blockchain data)

![image](https://user-images.githubusercontent.com/63310656/90433854-253dd600-e0ea-11ea-9859-4d826b121aa5.png)

**Comment by bayk** [comment]
According to our discussion, we need button "Resync Node"

@vinayaga07 , the root problem is that Node unable to sync with a network.  I see that there are 2 connections. Recently I saw the same issue and not much what I could do. Enough online nodes helped with that

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/91647852-ab281e00-ea14-11ea-82b9-6adf333ce1f7.png)

New button: "Resync Node"

**Comment by vinayaga07** [comment]
Verified  the following scenarios with the latest build and it is working as expected.

After sending MWC from online wallet to cold wallet using send via File option, online Node wallet Block count is  getting increased.

In Online node wallet & Cold wallet , transaction got confirmed, ( after loading Blockchain data)

![image](https://user-images.githubusercontent.com/63310656/92567191-f525c500-f29a-11ea-8da6-fe93dc885c2a.png)

Hence closing this ticket.
