### ISSUE TITLE
Android, mwc713 and tor integration.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#484]
The tests under the Android on physical device shows that some optimization needed:
1.  mwc713 doesn't need to manage tor connection quality. Tor by itself does that great. As a result of double management we have worse performance then we could.
2. permissions on tor dir must be the same as we do for Unix

here is error message  
18.08.2020 10:55:26.094 Notification INFO  Unable to start Tor listener. Tor Process Error: Unable to start tor at /data/user/0/mw.mwc.wallet/files/mwc-qt-wallet/gui_wallet713_data/tor/listener/torrc, Tor Reported Error [err] Reading config failed--see warnings above., and warnings: ["[warn] Path for DataDirectory (./data) is relative and will resolve to /data/data/mw.mwc.wallet/files/mwc-qt-wallet/gui_wallet713_data/tor/listener/./data. Is this what you wanted?", "[warn] Path for HiddenServiceDir (./onion_service_addresses/fd4qovmbtdgwuchmywgf7k33754hpcpyywkejteoaeviavpnysmh7had) is relative and will resolve to /data/data/mw.mwc.wallet/files/mwc-qt-wallet/gui_wallet713_data/tor/listener/./onion_service_addresses/fd4qovmbtdgwuchmywgf7k33754hpcpyywkejteoaeviavpnysmh7had. Is this what you wanted?", "[warn] Permissions on directory ./onion_service_addresses/fd4qovmbtdgwuchmywgf7k33754hpcpyywkejteoaeviavpnysmh7had are too permissive.", "[warn] Failed to parse/validate config: Failed to configure rendezvous options. See logs for details."]

Here is 'ls -al' output 
drwxrwxrwx 3 u0_a655 u0_a655 4096 2020-07-31 20:46 .
drwxrwxrwx 4 u0_a655 u0_a655 4096 2020-08-15 15:27 ..
drwxrwxrwx 3 u0_a655 u0_a655 4096 2020-08-15 16:05 fd4qovmbtdgwuchmywgf7k33754hpcpyywkejteoaeviavpnysmh7had

**Comment by electrum17** [comment]
Checked in fix to check for windows or not windows. Android should be not windows.

**Comment by bayk** [comment]
@electrum17 , what about #1. mwc713 restart for tor make connection worse. Can you fix that as well?

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
