### ISSUE TITLE
[QT-wallet]  Changing  "Cold wallet" to "Online wallet" throws error message.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#486]
**Description:**
While changing "Running Node" from "Cold wallet" to "Online wallet", getting the below error message.
- Failed to start mwcmqs subscriber. Error connecting to mqs.mwc.mw:443<<+)mwc713(+>>

![image](https://user-images.githubusercontent.com/63310656/90663577-79ba9000-e267-11ea-94ff-d89bd6596a29.png)

**Comment by bayk** [comment]
Works fine now, can't reproduce. I hope it is already fixed.

**Comment by vinayaga07** [comment]
Successfully verified the fix with the latest build, hence closing this ticket.
