### ISSUE TITLE
Status notification windows overlap vertical scrollbar.

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#488]
When the height of the window is low enough the notification hovers over the vertical scrollbar, the scrollbar is still usuable though.

**Comment by scasaletto** [comment]
Will not fix. The status notifications are always displayed just above the status bar and just inside the right hand border. If the window is resized and the vertical or horizontal are displayed, the scroll bars are still usable even though they are partially covered. This is the same behavior as for buttons which may be partially covered. You need to click on the portion of the button that is not covered by a notification window or wait until the window disappears.

**Comment by vinayaga07** [comment]
Closing this ticket as per the above comments and also verified the Notification window overlapping scrollbar.
