### ISSUE TITLE
Clicked notification turns white

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#489]
Comment from user testing on Windows:

When the notification is clicked and the modal pops up, the notification turns white but has rounded edges and a different purple background color.

**Comment by scasaletto** [comment]
The latest behavior requested from mwc-design is that when the notification is clicked, the background should be white with the text the same purple color as the background when the notification was not clicked. The colors have been fixed as part of https://github.com/mwcproject/mwc-qt-wallet/issues/521. The rounded edges have been fixed and they are now no longer rounded.

**Comment by vinayaga07** [comment]
Verified the color fix on Notifications messages, hence closing this ticket.
