### ISSUE TITLE
Notification messages can make edit controls lose cursor

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#490]
From Konstantin:
Seems like notification messages can make edit controls loose cursors.  I can edit there, I can see the border that show the focus. But there is no cursor.  You can reproduce it on Send page. Chances are about 50%

**Comment by scasaletto** [comment]
This may have been an effect when the notifications were all being created dynamically each time a notification message needed to be displayed. This behavior has been changed so that all of the windows used are created up front. Since that change, I no longer see this issue.

**Comment by vinayaga07** [comment]
Closing this ticket as per the above comments.
