### ISSUE TITLE
Swap mwc-wallet.  Secondary currency should define default fees and fee units.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#491]
Currently default fee is 26 satoshi  per byte. It is fine for BTC.
For BHC this value is wrong, very likely it is different.

**Comment by electrum17** [comment]
Default should be much smaller for BCH.

**Comment by bayk** [comment]
@electrum17 , actually fees in satoshi are the same. It is cheaper in USD because the coin is cheap.
https://bitinfocharts.com/comparison/bitcoin%20cash-transactionfees.html#3m

![image](https://user-images.githubusercontent.com/42393608/90830352-5db1ff80-e2f6-11ea-8ca4-343eafc9f9f7.png)

**Comment by bayk** [comment]
Fees already defined at the secondary currency.   Default fee of 26 satoshi looks reasonable as well.
Closing the ticket, no changes needed.
