### ISSUE TITLE
Qt-Wallet Can't run cold wallet when not connected to network.

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#497]
When starting up the cold wallet without a network connection, after a few minutes you will get a dialog pop-up saying:
    Embedded MWC-Node Error
    mwc-node process exited due some unexpected error. The exit code: 127
    ...
Since this is a dialog, all use of the wallet is blocked even if you move the dialog out of the way and try to continue to use the wallet. Once you click on either option in the dialog (e.g. keep embedded, switch to cloud), the wallet shuts down.

**Comment by vinayaga07** [comment]
Verified with the latest QT wallet build without a network connection and not hitting "get a dialog pop-up saying:
Embedded MWC-Node Error...". Hence closing this ticket.
