### ISSUE TITLE
[MWC-WALLET]Swap id returned after issuing a swap command has an extra 'er' on the end.

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#505]
mwc-wallet> swap_start --method mwcmqs --dest xmfcZq9XPXZNF7xKdH25NbJaHGzbJapZcoFT3hfRi95FCbEvf9RS --mwc_amount .007 --secondary_currency bch --secondary_amount 0.0000001  --mwc_confirmations 1 --secondary_confirmations 1 --message_exchange_time 0 --redeem_time 0 --secondarSeller Swap trade is created: 6b360151-146b-4a1e-b331-77266b194843**er**
Command 'swap_start' completed
mwc-wallet> swap --adjust cancel -i 6b360151-146b-4a1e-b331-77266b194843er
20200827 14:58:07.336 ERROR grin_wallet_controller::command - Unable to adjust the Swap 6b360151-146b-4a1e-b331-77266b194843er: Swap Error , Swap trade 6b360151-146b-4a1e-b331-77266b194843er not found
LibWallet Error, Unable to adjust Swap 6b360151-146b-4a1e-b331-77266b194843er: Swap Error , Swap trade 6b360151-146b-4a1e-b331-77266b194843er not found
mwc-wallet> swap --list

____ Swap trades ____

 Swap ID                              | Status 
--------------------------------------+------------------------------------------------------------------
 ed9c085e-c2d1-4806-904b-b2599c99960b | Seller swap was cancelled, nothing was locked, no need to refund 
 cbfcd6a0-e568-47d5-ba63-3b76b28d8d68 | Seller Swap trade is successfully complete 
 **6b360151-146b-4a1e-b331-77266b194843** | Offer is created 
 14f33b4c-86fc-430e-bed6-0d63c5238835 | Seller swap was cancelled, nothing was locked, no need to refund 
 9a782f7b-dda0-40b3-9479-c7361bf1b83e | Seller swap was cancelled, nothing was locked, no need to refund 
 57e72aea-34d0-46d9-92b0-055d6beb2ee4 | Seller Swap trade is successfully complete

**Comment by bayk** [comment]
Issue is related to the terminal, not to mwc-wallet
