### ISSUE TITLE
mwc-wallet support export_proof and verify_proof

### ISSUE THREAD

**Issue by yyangli** [mwcproject/mwc-qt-wallet#506]
command: verify_proof --input $input_file
export_proof --output $output_file --id $tx_id

**Comment by yyangli** [comment]
Vinayaga, please test this one. Thanks!

**Comment by bayk** [comment]
@yyangli ,  if you want QA start testing, please change ticket status to "Fixed". I just update this ticket with that.
![image](https://user-images.githubusercontent.com/42393608/96516837-ae71a600-121c-11eb-8bc4-3d80880f72e0.png)

Testing:  You can use QT wallet for proofs testing, if it works and can export proofs - this ticket can be closed.

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
