### ISSUE TITLE
Replay Attacks and possible mitigations

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#508]
https://forum.grin.mw/t/replay-attacks-and-possible-mitigations/7415

We want to solve this issue on the wallet level because we don't want want node to be heavy and do tracking of kernels.

On wallet level solution must survive wallet restore from the seed case. 
Wallet solution will recognize such possible outputs and automatically take care about them. 
Note: false alarm will happens, for example swap outputs MIGTH classified like those (happy path will be fine, but edge cases will trigger false alarm).

**Comment by bayk** [comment]
Need to discuss the solution and fix it.

**Comment by yyangli** [comment]
I will implement a simple solution Konstantin proposed, add height information to the output. Then in the node consensus level, we need to add that extra check.
