### ISSUE TITLE
cold wallet - mwc713 process exits when restoring new wallet from seed

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#509]
Create a brand new cold wallet installation following instructions in https://github.com/mwcproject/mwc-qt-wallet/blob/master/DOC/cold_wallet_software_installation_guide.md
When you first run mwc-qt-wallet, try to recover a wallet from seed. Get error in attached screenshot.
![recoveringFromSeed](https://user-images.githubusercontent.com/7772099/91928618-22261680-eca2-11ea-8a66-8a7e6397060b.png)

**Comment by bayk** [comment]
currenly mwc713 report error correctly. It require the node connection for restore. This usecase need to be fixed

**Comment by bayk** [comment]
mwc713 is not only the problem.  Because of that we will need to show the resync progress.  Currently qt wallet will show that with notification messages.

**Comment by vinayaga07** [comment]
In cold wallet, when restoring new wallet from seed, not observing issue.
Hence closing this ticket.
