### ISSUE TITLE
Notification message about send/receive might be incorrect

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#51]
I think there are some problems with generation of the message about send/receive.  Messages was never tested for few wallets. There is a high chance that phrases are incorrect.

**Comment by cgilliard** [comment]
I think send/receive are correct, but it just means the sender has sent the funds and the receiver has received them. It doesn't mean the network has confirmed them. These terms all mean different things:

Send - slate is sent to receiver
Receive - slate is received by receiver
Finalized - slate has been finalized (signed) by sender
Confirmed - miners have included the finalized slate into a block
Multiple confirmations - miners have included it in a block and subsequent blocks have been mined in the chain. (This is where the settings of 10 confirmations comes from).

**Comment by bayk** [comment]
There are bunch of updates, mostly regarding reporting of the events. So far everything works fine.
Also, when wallet gets funds, it shows Message box
