### ISSUE TITLE
Placement of notifications too high on node status window

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#513]
The placement of the status notification windows is based upon the location and dimensions of the status bar. Evidently in some windows, like the Node Status window, the dimensions of the status bar changes. Need to find a way to work around this issue.

**Comment by scasaletto** [comment]
Fixed the code so the notifications are always placed relative to the static dimensions of the main window status bar.

**Comment by vinayaga07** [comment]
Verified the Notification status windows, hence closing this ticket.
