### ISSUE TITLE
[QT-Wallet] After re-sizing the QT-wallet window size, unable to click buttons

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#515]
**Description:**
After re-sizing the QT-wallet window size, unable to click buttons like "Wallet Settings", "Account Options".
Please refer the screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/92624293-f8de3980-f2e4-11ea-96bc-6b250969b3a0.png)

**Expected Result:**
If window size got changed, then the existing buttons should get auto aligned.

**Actual Result:**
If window size got changed, then unable to click the buttons.

Note:
Tested on Mac OS Platform.

**Comment by bayk** [comment]
It is pretty bad issue because it happens pretty often ind it is confusing. Will try to make buttons to get events first

**Comment by bayk** [comment]
Fixed with page titles ticket.  Because of the title controls need to be lower and they can't overlap the buttons any more.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
