### ISSUE TITLE
[MWC-QT-WALLET] UX Unable to switch wallets from the settings tab

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#516]
I used to be able to change wallets by modifying the wallet config (under the main tab). This Functionality no longer exists.  Maybe it is just me, but having multiple wallets, it can be very helpful to be able to switch wallets from here.

**Comment by bayk** [comment]
Now you can logout to change the wallet.  I will update "Logout" with something like "Logout / change wallet"

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/97123598-d31cc080-16e9-11eb-91eb-a86240159353.png)

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
