### ISSUE TITLE
[MWC-QT-WALLET] UX Unable to select wallets from the non-default folder when opening qt wallet.

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#517]
Previously I could select wallets from different folders when opening qt wallet.  Now there seems to be no way to do this.  As users may have their wallet data stored in different locations (including flash drives) I think this functionality needs to be added back.

**Comment by bayk** [comment]
It is already addressed with a new UI. 
![image](https://user-images.githubusercontent.com/42393608/96513078-63ed2b00-1216-11eb-9ce5-56002a7a5746.png)

**Comment by vinayaga07** [comment]
Verified Open wallet function, hence closing this ticket.
