### ISSUE TITLE
[QT-Wallet] Same error message displayed twice, when bad seed phrase is used in recovery

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#518]
**Description:**
Same error message displayed twice, when bad seed phrase is used in recovery.

**Error Message**
BIP39 Mnemonic (word list) Error, Unable to convert mnemonic passphrase into seed, bip39 checksum 0x1c does not match expected 0xee
BIP39 Mnemonic (word list) Error, Unable to convert mnemonic passphrase into seed, bip39 checksum 0x1c does not match expected 0xee

![image](https://user-images.githubusercontent.com/63310656/93356156-77465880-f85c-11ea-9e00-7076beabe78f.png)

Try to recover with a phrase
taxi volcano position attend call glory
taxi volcano position attend call glory
taxi volcano position attend call glory
taxi volcano position attend call glory

**Environment:**

- QT Wallet on Windows

**Comment by bayk** [comment]
With current release there is 1 message. Probably issue was fixed.

But there is another issue with qt elements drawing. Will use this ticket for that

**Comment by vinayaga07** [comment]
Verified with the latest build and observed the same message twice.
Hence re-opening this ticket.

![image](https://user-images.githubusercontent.com/63310656/97729241-832e6700-1af8-11eb-85bb-111c5fd9d18e.png)

**Comment by bayk** [comment]
Able to reproduce it under the Windows (MacOs is fine).

**Comment by bayk** [comment]
Testing:  Please use  Windows to verify

**Comment by vinayaga07** [comment]
Verified on Windows, hence closing this ticket.
