### ISSUE TITLE
[QT-Wallet] Cancel button is not working on the QT-Wallet, while trying to recover with a phrase.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#519]
**Description:**
**Cancel** button is not working on the QT-Wallet, while trying to recover with a phrase.
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/93357235-b45f1a80-f85d-11ea-8fa7-f816740df1d7.png)

**Comment by bayk** [comment]
Taking it. One month since assignment is passed. Need to be done by release.

**Comment by bayk** [comment]
It works now is expected for account restore. Cancel returns to the starting screen

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
