### ISSUE TITLE
Amounts not updated for long after transaction occurs

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#52]
There are some problems with the amounts being updated in the latest builds. In the past there were some minor issues but I think now in the latest build something has broken because even after confirmations, the amounts are not updating. I had to click on several tabs to get the amounts to update. This feature was not really defined, so will try to define here. All amounts should be updated as soon as a slate is received on the receive side and when it's finalized on the sender side. Probably the best way to achieve this is by calling "info" every time a slate is received or finalized and updating all values. If the amounts aren't updated right away, users will get concerned.

**Comment by bayk** [comment]
Yesterday there was a fix for accounts. That issue might be related. 
I will take a look at that. I didn't check wallet to wallet workflow yet.

**Comment by cgilliard** [comment]
Saw more issues on this one. It was showing my coins as locked when they were not. When I ran mwc713 command line, I saw that no coins were locked. I could not get it to refresh. The only way was to close the application and restart. I think this is the most critical bug now that we are feature complete. Let's prioritize this one.

**Comment by cgilliard** [comment]
Also as a note: on re-sync this should be called so that amounts are updated afterwords.

**Comment by bayk** [comment]
Balance update after re-sync is fixed.

**Comment by bayk** [comment]
Update: found that issue is because of incorrect usage if 'no-refresh' flag.

**Comment by cgilliard** [comment]
Mostly this is fixed, but the drop down in the transactions tab is still not updating until you click the send tab. See screenshot. I have confirmations set to '1'.
<img width="812" alt="Screen Shot 2019-09-01 at 7 53 41 PM" src="https://user-images.githubusercontent.com/7232183/64087551-6fb81e00-ccf2-11e9-8b7f-94d2a5e5222c.png">

**Comment by cgilliard** [comment]
Also, the upper left account balance seems to never update until you click on 'transactions'. This will make users concerned. Lets update all values when we receive slate. See image.
<img width="1006" alt="Screen Shot 2019-09-03 at 6 29 18 PM" src="https://user-images.githubusercontent.com/7232183/64212917-f991f380-ce78-11e9-8978-9cc5ef943302.png">

**Comment by bayk** [comment]
It should be updated when you receive some coins.  Income slate should
trigger the balance update
