### ISSUE TITLE
[cold wallet]Filter out listener notifications

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#523]
When running a cold wallet, it is expected that the wallet is not connected to the network. However, notifications about the listeners not being connected are displayed repeatedly. These messages not should be displayed as part of the notification messages when you are running a cold wallet.

**Comment by scasaletto** [comment]
For the cold wallet, all notification messages which include the word "sync" are now being filtered out and not displayed using the notification windows.

**Comment by vinayaga07** [comment]
In Cold wallet, "Sync" notifications are not getting displayed, hence closing this ticket.
