### ISSUE TITLE
Notification window placement too high.

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#525]
If notifications were being displayed when the wallet restarts, the placement of the notifications windows is too high. This issue can be seen when running the cold wallet and importing blockchain data. After you click to import the blockchain file and select a file to import, a couple of notifications are displayed and then the wallet restarts. On restart the placement of the notifications will be too high as they are placed as if the notifications being displayed during the restart are still visible.

**Comment by scasaletto** [comment]
The issue was that the number of visible messages was not being reset when the wallet restarts. This has been fixed.

**Comment by vinayaga07** [comment]
Verified Notification messages after wallet restarts, hence closing this ticket.
