### ISSUE TITLE
QT-Wallet]  Restore page, UI (text message) need to be re-aligned.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#526]
**Description:**
In QT wallet, Restore page, UI (text message) need to be re-aligned.
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/94048547-4da7a700-fdf1-11ea-8838-a2a0e3228b29.png)

**Comment by bayk** [comment]
I changed the sentence so it fit now:

![image](https://user-images.githubusercontent.com/42393608/97254898-aa212c00-17cc-11eb-9217-629a0d5e677e.png)

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/97728155-34cc9880-1af7-11eb-802c-58a02bd6bcb1.png)
