### ISSUE TITLE
[QT-Wallet] Notification message - need to be removed

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#527]
Description:
In the QT wallet login page, if we provide an invalid login credentials, getting the below Notification message in the bottom of the page but it doesn't make any use to the User. 

![image](https://user-images.githubusercontent.com/63310656/94175020-b0617700-feb3-11ea-8eed-5bb742834553.png)

Expecting: This particular notification message need to be removed - "Notifications Waiting To Be Read: 2".

**Comment by scasaletto** [comment]
When the wallet is locked, I have fixed the notification that appears to now allow it be clicked. So now you will only see the notification but it cannot be clicked and it won't change color when the cursor hovers over it.

**Comment by vinayaga07** [comment]
Now Notifications are not clickable, hence closing this ticket.
