### ISSUE TITLE
Block explorer data storage need to be optimized.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#529]
Block explorer keep data into the single directory, one file per block.
Currently there are almost 500k files in a single dit. It is not efficient, OS doesn't like that even it can deal with that.
For performance we better to use hierarchy for those files.
It is easy to change, so we better do that before we hit performance problems.

**Comment by bayk** [comment]
@hcasalet ,  I think you implemented that, right?  Is it done?

**Comment by hcasalet** [comment]
Yes, this is implemented. I am closing it.
