### ISSUE TITLE
QT wallet support for the proofs

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#530]
We talk with @yyangli  and so far we identify the list of needed changes for QT wallet.

1. Receive page need to have "File, HTTP prove address"  that very likely will be very similar to tor address. We can't use tor address because tor can be disabled.

3. Send page for HTTP and Files will ask for the recipient's proof address.

**Comment by bayk** [comment]
Here is a UI description.
https://docs.google.com/document/d/1cc3zFjri2mJ1aFpUp3kScP9N_T0RE0DHicSDMKksjMo/edit?usp=sharing

Please note, test need to include explorer. Explorers need to show proofs.

**Comment by vinayaga07** [comment]
Successfully verified "Receive page", "Listener Page"; hence closing this ticket.
