### ISSUE TITLE
[QT wallet] "Transfer MWC between accounts" page, able to select "From" and "To" accounts as same.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#539]
**Description:**
In QT wallet "Transfer MWC between accounts" page, able to select "From" and "To" accounts as same.
Expecting,  "To Accounts" field should not allow user to select same account  selected in the "From Account".

![image](https://user-images.githubusercontent.com/63310656/95491784-bc6f2d80-09b7-11eb-9690-9426fc661d76.png)

**Comment by bayk** [comment]
We probably can deselect another account is they are the same.

**Comment by bayk** [comment]
Now it is impossible to select the same account twice. The another combobox will be reseted.

**Comment by vinayaga07** [comment]
Verified with the latest fix, hence closing this ticket.
