### ISSUE TITLE
Pace display of "at limit" notifications when wallet is locked or iconified.

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#541]
When using the mining wallet and it is first syncing up, a whole bunch of notifications get displayed for a fairly long period of time. If the wallet is locked or iconified, the "at limit" notification message displays fairly frequently which can be somewhat annoying. So once the notification queue limit is reached, pace the display of the "at limit" notification so it will be displayed less frequently.

**Comment by scasaletto** [comment]
Implemented an internal counter so that once the notification queue limit of 25 is reached, we don't display the "at limit" message again until another 25 messages have been received. Note these "at limit" messages are only displayed when the wallet is locked or iconified.

**Comment by vinayaga07** [comment]
Closing this ticket.
