### ISSUE TITLE
[Qt-Wallet]Notifications misplaced when wallet changed to full screen

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#543]
When changing the wallet to full screen, new notifications will appear to be offset higher from notifications already being displayed. This is because the window dimensions of the wallet have been changed, but the existing notifications are not redisplayed with the new dimensions.

It is easiest to see this problem by starting the wallet and then changing to full screen right away. Usually there are about 4-5 messages which get displayed when the wallet first starts, so switching to full screen before all of these messages have been displayed should duplicate the issue.

**Comment by scasaletto** [comment]
Fixed notifications so that they are redisplayed, and therefore repositioned, whenever the wallet is switched between full screen and back.

**Comment by jbyrer** [comment]
Confirmed fix, shrank and grew screen.
