### ISSUE TITLE
Proofs for files. Show receiver address

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#548]
Receive page for the files need to show the proof address for the slate. User should be able to verify that data comes from the expected wallet.

**Comment by bayk** [comment]
Testing:  
If proof is selected for the files, you should see the receiver address

![image](https://user-images.githubusercontent.com/42393608/96919603-d94c3c00-1460-11eb-9c3b-1ef72f922004.png)

**Comment by vinayaga07** [comment]
Verified the Receiver address, hence closing this ticket.
