### ISSUE TITLE
Proof for HTTP. User need to see whom he send the funds. 

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#549]
Before send funds with proofs, QT wallet need to do:
1. Request proof address from another party
2. Ask user if he want send to this wallet
3. Send funds through http and verify that response slate has that address.

On mwc713 / mwc-wallet  it will require changes.
1.  Add command show receiver proof address. Argument is http address of that wallet.
2. send command should have additional parameter  expected_address.  That address will be checked for the received slate.

**Comment by bayk** [comment]
For http add the receiver address at the confirmation dialog
![image](https://user-images.githubusercontent.com/42393608/96952375-8d6eb680-14a3-11eb-97a1-e00fdc815e4d.png)

**Comment by bayk** [comment]
Note,  currently HTTP doesn't work if receiver has api secret.  There is another ticket about that issue.

**Comment by vinayaga07** [comment]
Verified the fix, hence closing this ticket.
