### ISSUE TITLE
placeholder for release: rename directory structure such that old installs don't conflict

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#55]
For the release version we will need to make it so that no matter which old version was installed, the new version installs cleanly. Users will not be able to delete/rename the config files. This will mean that old configurations will be gone, but that will be easier to deal that users that have old configurations.

**Comment by bayk** [comment]
All config has versions. Will increase the version with modifications. gui wallet config version was increased, so now we should be fine.

**Comment by bayk** [comment]
Also, recently mwc-gui-wallet was renamed to mwc-qt-wallet. So we are good for now.
Will update versions in the future, we release will not conflict.
