### ISSUE TITLE
Mobile like controls for the notification page.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#550]
Desktop QT wallet adopting the Mobile look for the list.
Here is a Notification.

Here is design image just to compare the look.
![image](https://user-images.githubusercontent.com/42393608/96211428-2c863200-0f29-11eb-846d-e751f8373e94.png)

**Comment by bayk** [comment]
Testing.  Please check if there are no issues on different platforms.

**Comment by vinayaga07** [comment]
@bayk In MWC QT wallet(desktop), there is no separate Notification page.
Please let me know,  what need to be verified on the MWC QT wallet(desktop) ?

**Comment by bayk** [comment]
@vinayaga07 ,  there is a page "Event Log".  We probably should rename it to "Notifications" so names will be the same. Notifications is better name. I will create a ticket for that.

![image](https://user-images.githubusercontent.com/42393608/98844172-cf36b100-2400-11eb-81f2-f43877313519.png)

Press a button with exclamation mark.


![image](https://user-images.githubusercontent.com/42393608/98844202-da89dc80-2400-11eb-9e55-e75228622b1b.png)

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
