### ISSUE TITLE
mwc-walet, file transactions, creating 0 size files in case of failure

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#551]
For files operations wallet create the file first and then processing slate. If make sense because we want to check FS errors first. As a result in case of failure we have issues:
1. Prev file will be overwritten and has 0 length
2. For new file it will be 0 length file, so user assume that everything is file.

The solution:
1. Write to the bak file (in case if file exist, we don't want to overwrite it)
2. Move the file on success and delete it on failure.

**Comment by yyangli** [comment]
@bayk can you point to me where this part of code is?

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
