### ISSUE TITLE
Mobile like controls for the transactions page

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#554]

**Comment by bayk** [comment]
Testing: 
1. Check if functionality works for the buttons: Cancel, Repost, proof.
 Check for repost:  FInalize file based transaction when wifi is off. Keep it of for few minutes until connection error will be reported.  Then turn wifi on and check that transaction is not confirmed.  Then do repost and check if it will be confirmed after some time.
Note:  Repost active even transaction is not finalized. It is a known issue for the wallet, we are not changing it. Currently there is impossible to check if the transaction was finalized.

2. Try on different OS.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
