### ISSUE TITLE
Remove Keybase form the QT wallet

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#564]

**Comment by bayk** [comment]
Testing:  
1. Check that No keybase we have onto UI. Including the help.
2. Check if TOR and MQS indicator are valid.  I think we have them at logout page, Listen page and Receive page. When network goes down, indicators should go offline. hen network back on - they should turn green.
3. At the listen page try to change the wallet address and verify that both MQS and Tor are changed and for the same index use the same addresses. And if you start listeners, really those addresses work.

Any OS is fine.

**Comment by vinayaga07** [comment]
Verified successfully with the latest build, hence closing this ticket.
