### ISSUE TITLE
Proofs supports for the mobile

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#568]
This code is already implemented in the mobile. Will need to revisit for proofs.

Here are changes on Finalize page.
https://github.com/mwcproject/mwc-qt-wallet/issues/548

Here are changes on send page.
https://github.com/mwcproject/mwc-qt-wallet/issues/549

**Comment by sarawut11** [comment]
@bayk This was sorted in https://github.com/mwcproject/mwc-qt-wallet/pull/669
Please check it.

**Comment by bayk** [comment]
There are some UI changes,  I will demo you next week

**Comment by sarawut11** [comment]
This was already done and merged into master.

**Comment by bayk** [comment]
Testing:
Please check for proofs, the mobile app show other party address before finalize the transaction for http (send confirmation step) and files (before finalize step).

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
