### ISSUE TITLE
Platform testing

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#57]
Opening this issue to track testing of platforms. So far platforms that have been tested with a clean install are:

1.) MacOSX 64 bit 10.14.x
2.) Windows 10 - 32 bit
3.) Windows 10 - 64 bit
4.) Linux - Ubuntu latest 64 bit
5.) Linux - Fedora latest 64 bit

Everything works on those platforms. We should verify release builds on those platforms as well.
The additional platforms that would be good to support are: Windows 7 and Windows XP (however it's less important due to the fact that MS is allowing free upgrade to Windows 10 for everyone and ISOs are downloadable.

**Comment by cgilliard** [comment]
After the older windows platforms, the only remaining platforms that would be potentially useful are Linux 32 bit. That is low priority though.

**Comment by bayk** [comment]
Ubuntu:
- Radio buttons, should be fixed.
- Console runs with app.
Windows:
- Radio buttons.
- Links are not open.
- Try to brand the windows title

**Comment by bayk** [comment]
Platforms testing is done with current nightly build. There are few issues and I created different tickets for that. So far all platforms supported well.
