### ISSUE TITLE
Test is QT wallet show correctly message "You get coins"

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#570]
Please test with all transports that qt wallet correctly shows the message that some coins was received.
Any OS is fine

**Comment by vinayaga07** [comment]
Message shows: Info: Congratulations! you received xxx MWC.
![image](https://user-images.githubusercontent.com/63310656/98264369-d3e90880-1fad-11eb-885b-9ca3dde27f99.png)

Hence closing this ticket.
