### ISSUE TITLE
Add dynamic fees for atomic swap.

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#572]
When using atomic swap, the user must enter a fee to use to pay the miners when retrieving their non-MWC coin from the "lock address". Currently it is up to the user to decide on the fee amount without any guidance from us. If too low of an amount is entered, the user may never receive their coin as it might never be picked up by miners and included in the blockchain. 

There are some APIs available for retrieving the current range of mining fees for different coins. One being https://bitcoinfees.earn.com/api/v1/fees/recommended

To make atomic swaps easier to use and less error prone, we should provide dynamic mining fee support for atomic swaps.

**Comment by bayk** [comment]
For BCH tx fee problem doesn't exist.

For BTC  there are bunch of API https://b10c.me/blog/003-a-list-of-public-bitcoin-feerate-estimation-apis/

We will use https://www.bitgo.com/api/v2/btc/tx/fee   because it provide exactly what we need.
