### ISSUE TITLE
Save Restore Wallet size, find the best default ones.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#574]
App suppose to remember and be able to restore it latest size. We don't want user open app and resize it first

**Comment by bayk** [comment]
Testing
QT has a nice functionality that save and restore the last window size and position. QT suppose to handle edge cases when windows might be not visible or doesn't fit.  I tested under MacOS. Looks good for me. 
Please test Linux and Windows.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
