### ISSUE TITLE
Remove Keybase form the mobile wallet

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#576]
Keybase support will be removed. I will keep bridge interfaces but put asserts there. 
So you will need to get rid from those calls.

When this ticket will be done, I will continue and remove the bridge interfaces.

**Comment by sarawut11** [comment]
@bayk I removed all keybase related things in mobile in https://github.com/mwcproject/mwc-qt-wallet/pull/669
So now you are fine to remove the bridge interfaces.

**Comment by bayk** [comment]
done, closed
