### ISSUE TITLE
Qt Wallet - Text cut off in some of the screens.

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#578]
![Screen Shot 2020-10-29 at 2 22 40 PM](https://user-images.githubusercontent.com/7772099/97625368-6ad62380-19f6-11eb-881e-261e8bb2767e.png)

Text cut off in Receive Coins screen. See MWC Message Queue is cut off.

This happens on both my 13 inch macbook and 15 inch macbook

**Comment by scasaletto** [comment]
![Screen Shot 2020-10-29 at 3 10 57 PM](https://user-images.githubusercontent.com/7772099/97627411-56475a80-19f9-11eb-8a20-32d211483164.png)

Another screen where text is cut off. 'e' in Cold Wallet Node

**Comment by vinayaga07** [comment]
Successfully verified with the latest build, hence closing this ticket.
