### ISSUE TITLE
Electrum X connection should support SSL

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#579]
Currently wallets are using http connection to ElectrumX servers. Is is not great.
Here are changes that need to be made.

1. mwc-wallet/mwc713  configs for the electrumX need to have some prefixes, like http/https  (Or electrumX client must detect that ssl is needed)
2. mwc-wallet, electrumX client need to support ssl connection.
3. mwc-wallet swap & swap_start commands accepting electrumX connection from the user. The format should be similar to #1.

This issue might not be a part of the next release.

**Comment by hcasalet** [comment]
Used openssl however client complains about "Certificate verify failed". Debugging...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(192.168.1.8:53214), peer: V4(24.4.197.142:19339), fd: 12 }, ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 20, error: "unable to get local issuer certificate" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1915 }]))) } })': libwallet/src/swap/bitcoin/rpc.rs:44   0: backtrace::backtrace::libunwind::trace

**Comment by bayk** [comment]
IP  192.168.1.8  doesn't looks correct. Also certificate can pass only you url has a hostname.  I will take a look.

**Comment by bayk** [comment]
SSL support is done. Now wallet can support both SSL and non SSL connection to Electrum X. 
Need to update the setups, configs and after will close the ticket.

**Comment by bayk** [comment]
All servers are switched as planned. So closing the ticket
