### ISSUE TITLE
32 bit windows lmdb files are not compatible with 64 bit files causing errors when switching between wallets

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#58]
This bug is deep in the grin_store library code of the mwc full node which uses lmdb to store transaction data. Probably the easiest solution is to prevent users on 64 bit operating system from running 32 bit binaries, or at least warning them that it might not be compatible.

**Comment by bayk** [comment]
Chris, it is a case that users will run 32/64 bit instance, create the wallet, do something.
Then they switch and will get a problems?
Normally 32bit and 64 bits are not compatible. I think we shouldn't  fix that.  My point if we fix Imdb files there will be something different with that.
Same for big/small endians.  We are not expecting people safely move files between different PCs with different architectures. 
We can support it, it is doable, but I don't think people will appreciate that. Likely nobody will need that.

**Comment by cgilliard** [comment]
The case you described does have problems. You can reproduce it by installing the 64 bit binary, creating a seed, and then installing the 32 bit binary. Your 32 bit binary will not be able to start due to an lmdb error.

I agree with you that we shouldn't fix the lmdb issue. I think we should just prevent users on the 64 bit system from running the 32 bit binary (or at least warn them). This can be done in the installer.

**Comment by bayk** [comment]
We probably can do that with the qt wallet. We can use approach that already implemented for networks to recognize to what network mwc713 data belong (User can select any directory and I have to update config correctly).
I can put file in the folder that will describe if it is 32 or 64 bit data inside. If user will try to switch to incorrect mwc713 data folder, I will print a message.
If somebody backup or restore the data, the file will be there.

Also mwc-qt-wallet might have the similar problems. But in this case the data dir can be named as  ~/mwc-qt-wallet_32 for 32 bit systems. In this case data will be separated.
 
I think it is a solution.

**Comment by bayk** [comment]
Update. Seems like  mwc-qt-wallet  doesn't have 32/64 data related problems for it's own data. QT streams suppose to handle that well. 
On Windows I tried to install 32 & 64 bit versions and there was no issues with that.  Will double check.

mwc713 need to be handled.

**Comment by cgilliard** [comment]
Yeah, its definitely an mwc713 issue. Probably at the lmdb (database file
library) level. I think the best option is your earlier suggestion to name
the files differently on win32/64. Then users will just not see their
balance if they switch, but they can easily go back to the version they
were on before.

**Comment by bayk** [comment]
for mwc713 solution will be similar that we already have for the network.
In setting user can select any directory for mwc713.  In that moment we
will check if it is 32 or 64 bits.
Directory naming is not applicable for mwc713 data because user specify the
name.

**Comment by cgilliard** [comment]
That works.

**Comment by bayk** [comment]
Changes pushed, will do more tests with nightly build
