### ISSUE TITLE
[QT-Wallet] Restore page, Dictionary words needs correction

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#580]
**Description:**
In QT wallet Restore page, Dictionary words needs corrections.

In QT wallet Restore page, if we enter invalid passwords ,then in the error message invalid Dictionary words are getting displayed.

**Expected Results:**
Dictionary words should be meaning dictionary words.

Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/97728774-f683a900-1af7-11eb-8c2a-3568c276d7d6.png)

**Comment by bayk** [comment]
@vinayaga07 ,  dictionary is build for the most used words. It is not necessary a real words, it is most used password combinations. Those dictionaries are available and can be used for attacking the password.  
Probably "Dictionary words" is incorrect wording. I think "Known passwords: " will be better.  What do you think?

**Comment by vinayaga07** [comment]
Here with given below my suggestions,


1. "Common passwords: "
2. "Common words: "
3. "Known passwords: "

**Comment by bayk** [comment]
Changed to 'Common words'. I think it describe the best

**Comment by vinayaga07** [comment]
Verified "Common words", hence closing this ticket.
