### ISSUE TITLE
Cold Wallet - Error retrieving saved tx file

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#581]
When sending coins from the cold wallet and then trying to finalizing the signed tx file from the receiver, an error is reported that the transaction cannot be found.

**Comment by scasaletto** [comment]
The problem was that for cold wallets, when the code is looking for the saved transaction to finalize, it was looking for a file with an extension of .grintx instead of .mwctx.

**Comment by vinayaga07** [comment]
Closing this ticket.
