### ISSUE TITLE
[QT-Wallet] In Receive Coin page, "MWC Message Queue" is not aligned properly.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#584]
**Description:**
In Receive Coin page, "MWC Message Queue" is not aligned properly.
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/97897523-9ccfe880-1d5c-11eb-8f24-3af2ce72c7cc.png)

**Comment by bayk** [comment]
MWC Message Queue is pretty long. That is why we can't make it even. Here how it looks like now
![image](https://user-images.githubusercontent.com/42393608/99202546-5e76f800-2764-11eb-8767-6373f0e983a4.png)

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
