### ISSUE TITLE
[QT-Wallet] In Receive Coins page, all the fields should be aligned same.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#585]
**Description:**
In Receive Coins page, "Account to receive incoming MWC coins" field is left aligned but all other Address (MWCMQS, TOR, payment proof address) fields are center aligned. 

Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/97898312-b58cce00-1d5d-11eb-803f-79ed552c5c7c.png)

Expected Result:
In a page, all the fields should be aligned as same.

**Comment by bayk** [comment]
Seems like it is the only page that center aligned. At least I don't see other pages. 
I think it make sense to make uniform. So I will align everything to the left

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/99202457-0e983100-2764-11eb-9762-66a3b4bc43b1.png)

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
