### ISSUE TITLE
[QT-wallet] Transaction validation proof page, Font Size is not uniform.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#588]
**Description :**
In Transaction validation proof page, Font Size is not uniform.
This particular page has different font size and hence page is not looking good.
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/98022446-a4aa8e00-1e2b-11eb-8888-379a2693308a.png)

**Comment by scasaletto** [comment]
Reassigning to Konstantin. He is implementing so he should fix.

**Comment by vinayaga07** [comment]
Verified the font size in the Transaction validation proof page, hence closing this ticket.
