### ISSUE TITLE
In Explorer, wrong Fee value is getting displayed.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#589]
In Explorer, tried verifying  MWC Transaction Proof and observed "Fee as 8000000"
Actually it should be 0.008 MWC.

Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/98023563-218a3780-1e2d-11eb-9ac4-cb35cd0f705a.png)

**Comment by bayk** [comment]
I will take that. Looking into explorr because of proofs in any case.

**Comment by bayk** [comment]
Fixed

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
