### ISSUE TITLE
In Explorer, "Confirmation" value is always  '0'.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#590]
**Description:**
In Explorer, tried verifying  MWC Transaction Proof and observed "Confirmation" value as always  0.

**Expected Result:**
Confirmation should display the actual number of confirmations.

Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/98023791-6c0bb400-1e2d-11eb-8916-273906d7fb12.png)

**Comment by yyangli** [comment]
We don't have "confirmation" number in the proof files, I am not sure how we support this in the past and where do we store this info.

**Comment by bayk** [comment]
> We don't have "confirmation" number in the proof files, I am not sure how we support this in the past and where do we store this info.

Explorer can calculate that value. The Block height and tip height are known. Probably something wrong with that.

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/99347407-ea178400-284b-11eb-8be6-50f6cf7bd2ed.png)

Fee is fixed. But confirmations was fine. Will test more.

P.S. Ticket is not fixed, yet. It is my local deployment.

**Comment by bayk** [comment]
Actually confirmation was 1 less than needed. Minor issue, fixed. Explorer updated
Formula: height - block + 1

**Comment by bayk** [comment]
Issue still exist in the last deployment. Will continue looking

**Comment by bayk** [comment]
now woks as expected on deployment

**Comment by vinayaga07** [comment]
Verified the number of confirmations, hence closing this ticket.
