### ISSUE TITLE
[QT-Wallet]Send Request failed with the error message which needs corrections.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#592]
**Description:**
While the Receiver wallet is offline,   the Send Request failed with the error message which needs corrections.
The Error message should be short and meaningful to the End User.

![image](https://user-images.githubusercontent.com/63310656/98140153-1990cd00-1eeb-11eb-9d2f-9ad129c01df4.png)

**Comment by scasaletto** [comment]
Reassigning to Konstantin. He is implementing so he should fix.

**Comment by bayk** [comment]
I can't reproduce yours, but it is not needed. The last root connection error will be included

![image](https://user-images.githubusercontent.com/42393608/99212211-5f695300-277f-11eb-999a-8d9634991b90.png)

Here is mapper:

Adapter Callback Error, Performing version check \(is recipient listening\?\): Request error: Cannot make request: error trying to connect: (.*)

Unable connect to receiver wallet. Probably it is offline or you have network connection problems. $1

**Comment by vinayaga07** [comment]
Verified the Error message, when the receiver is in offline.
Hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/99556728-e91b5980-29e7-11eb-803a-da0d5df72ef3.png)
