### ISSUE TITLE
Verifying  MWC Transaction Proof, status message getting displayed twice.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#593]
**Description:**
While Verifying  MWC Transaction Proof (https://explorer.floonet.mwc.mw/#verifyproof) which is not yet confirmed, then getting status message twice in the portal.
Please refer screenshot for more details.

Expected Result:

- Status message need to be displayed once.

![image](https://user-images.githubusercontent.com/63310656/98141298-793ba800-1eec-11eb-9dc5-dd6731db95b0.png)

**Comment by bayk** [comment]
@vinayaga07 ,  it is not bug, it is designed this way because every we need to search for every item like kernel and outputs. We are reporting separately, it make sense in case of some data corruption or fraud transactions.
I am closing this issue as wan't fix.
