### ISSUE TITLE
[QT-wallet] Error message during the Repost operation need to be corrected

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#594]
**Description:**
Error message during the Repost operation should be short and meaningful to the End User.
Current error message need to be corrected.

![image](https://user-images.githubusercontent.com/63310656/98142949-85286980-1eee-11eb-9cc2-1cb5c0c50f89.png)

**Comment by bayk** [comment]
Done with prev ticket.  Here is a mapper record:

Client Callback Error, Client error: {"Internal":"Failed to update pool, Tx Pool Duplicate tx"}
Transaction is already posted and stored at the transaction pool

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
