### ISSUE TITLE
Unable to verify the MWC Transaction Proof 

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#595]
**Description:**
Verification of an MWC Transaction Proof on the https://explorer.mwc.mw/#verifyproof  failed with the error message "Sorry, this proof file was unable to be verified."

Have successfully transferred MWC from one wallet to another wallet and tried to verify the Transaction Proof  on the https://explorer.mwc.mw/#verifyproof  after transaction got confirmed but it failed with the error message "Sorry, this proof file was unable to be verified."

![image](https://user-images.githubusercontent.com/63310656/98149559-6082c080-1ef3-11eb-97e1-b08c368d92c4.png)

**Comment by yyangli** [comment]
@vinayaga07 If you have the proof file, please attach it to this bug so I can try to verify it locally from mwc713.

**Comment by bayk** [comment]
That was a deployment issue at the floonet. Fixed

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
