### ISSUE TITLE
[QT-wallet] send MWC transaction failed messages need to be corrected.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#596]
**Description:**
While send MWC transaction failed, getting the below error message which need to be corrected.

Expected Results:
Always error messages need to be short and meaningful to the End Users.

![image](https://user-images.githubusercontent.com/63310656/98150317-75ac1f00-1ef4-11eb-865d-8f7c2b458f37.png)

**Comment by scasaletto** [comment]
Reassigned to Konstantin. He is implementing so he should fix.

**Comment by bayk** [comment]
@vinayaga07 , for such bugs please add how to reproduce it. Also please copy the message a s text.
For this one figured out what you did. You send, cancel and send once more. So it is double spending. 
This one is good. I will come with some error description.

**Comment by bayk** [comment]
Here is a new message 
![image](https://user-images.githubusercontent.com/42393608/99211107-6e9ad180-277c-11eb-9d97-19bf46ad6046.png)

**Comment by vinayaga07** [comment]
Closing this ticket.
