### ISSUE TITLE
[QT-wallet] Description box should allow users to enter multiple line of inputs.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#597]
**Description:**
In QT wallet, while sending amount using address, in the **description** box unable to enter more than 1 line of input.

**Expected Result:**

- Description box should allow users to enter multiple line of inputs.

Please refer the below screenshots for more details.
![image](https://user-images.githubusercontent.com/63310656/98260346-3a1f5c80-1fa9-11eb-80db-443f1b166744.png)

![image](https://user-images.githubusercontent.com/63310656/98260367-43102e00-1fa9-11eb-8011-1d6c5bf0ee03.png)

**Comment by bayk** [comment]
We can't disable multilines in UI. We can convert the multiline input into a single line, so functionality will not be broken.

**Comment by scasaletto** [comment]
Reassigning to Konstantin. He is implementing so he should fix.

**Comment by bayk** [comment]
Replacing '\n'  with ' ' works fine. You can reviews details with files. Of just send from qt wallet to qt wallet to see the message.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
