### ISSUE TITLE
[QT-Wallet] In pages "Restore", "New Instance", "TestNet" need to be replaced by "Floonet".

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#599]
**Description:**
In QT Wallet, "Restore", "New Instance" pages observed "**TestNet**" instead it should be "**Floonet**".
Please refer screenshots for more details.

![image](https://user-images.githubusercontent.com/63310656/98386204-e7f83d00-2075-11eb-8ce6-6d1e1532f1f5.png)
![image](https://user-images.githubusercontent.com/63310656/98386237-edee1e00-2075-11eb-8b5c-bb55a69b2618.png)

**Expected Results:**

1. "Restore", "New Instance" page "TestNet" need to be replaced by "Floonet".
2. "MainNet" need to be replaced by "Mainnet".

**Comment by scasaletto** [comment]
Reassigning to Konstantin. He is implementing so he should fix.

**Comment by vinayaga07** [comment]
Successfully verified with the latest build, hence closing this ticket.
