### ISSUE TITLE
[QT Wallet] "Restore", "New Instance" pages needs  "Cancel" button.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#600]
**Description:**
In QT Wallet, "Restore", "New Instance" pages needs "Cancel" button option.
From "Restore", "New Instance" pages, User could goto Next page but not able to go back to the previous page, so Users are forced to close the QT-wallet.

![image](https://user-images.githubusercontent.com/63310656/98387030-ed09bc00-2076-11eb-865c-de69fa5d3b9a.png)
![image](https://user-images.githubusercontent.com/63310656/98387149-10346b80-2077-11eb-8a68-6256e81e7214.png)

**Expected Result:**
Need a "Cancel" button in "Restore", "New Instance" pages.

**Comment by scasaletto** [comment]
Reassigning to Konstantin. He is implementing so he should fix.

**Comment by bayk** [comment]
Add "Cancel" button

**Comment by vinayaga07** [comment]
Verified Cancel button, hence closing this ticket.
