### ISSUE TITLE
QT-Wallet configuration Main page needs UI improvement.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#601]
**Description:**
In QT-Wallet configuration Main page, observed lot of empty spaces.
Wallet Config page needs a UI redesign to avoid empty spaces. Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/98387581-981a7580-2077-11eb-9681-9baf76d14933.png)

**Comment by scasaletto** [comment]
Reassigning to Konstantin. He is implementing so he should fix.

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/99200898-fcff5b00-275c-11eb-870f-a5d10adf2447.png)

**Comment by vinayaga07** [comment]
Successfully verified with the latest build, hence closing this ticket.
