### ISSUE TITLE
Verify if Explorer send Reorg alarms.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#603]
Both mainnet and floonet  explorers handle reorgs the same way.
Please make REORG if the height more then 5 on the floonet and then check if alarm will be sent. Alrm will be sent to the discord and by emails. Also please notify Jon before that test, he will get an email as well.

**Comment by suemto** [comment]
https://github.com/mwcproject/mwcexplorer/blob/master/src/main/java/servlets/BlockExplorer.java#L509-L543
👍

**Comment by bayk** [comment]
> https://github.com/mwcproject/mwcexplorer/blob/master/src/main/java/servlets/BlockExplorer.java#L509-L543
> 👍

This repo is private.  In worst case somebody can spam our alarm channel and send bunch of emails. Let's keep it.

**Comment by bayk** [comment]
Done last week
