### ISSUE TITLE
[QT-Wallet] "Finalize", "Swap"--> "Help" page needs a description message

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#607]
**Description:**
"Finalize"--> "Help" page needs a description message about the Finalize page and fonts need to be aligned same like "Transactions"--> Help Page.

Please refer the below screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/99092630-65ccc300-25f7-11eb-89f2-728e4f51c3b8.png)

**Comment by bayk** [comment]
@hcasalet , please take a look. It is lower priority than SSL. It can go into the next release. 
Also, please note, this ticket about Swaps page as well. 
You can write a content, I will update the help pages.

**Comment by bayk** [comment]
@vinayaga07   please check if it is enough for the help. Do you feel that we need put more explanations here. We are expecting users to watch videos and read docs from MrT.  We might say that here.

**Comment by vinayaga07** [comment]
@bayk - Expecting a short description of "Auto Swap". 
Herewith given below the Help description for "Transaction" page.

![image](https://user-images.githubusercontent.com/63310656/104935695-8c312500-59d1-11eb-8ea1-4fe7f20295b3.png)

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
