### ISSUE TITLE
[QT-Wallet] "Show passphrase"  - Listeners are getting restarted.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#608]
**Description:**
In QT wallet, after clicking "Show passphrase"  and provided "Password", while "Mnemonic passphrase" is getting loaded observed Listeners (TOR, MWC MQS) are getting restarted.

Please refer the screenshot.

![image](https://user-images.githubusercontent.com/63310656/99093711-db855e80-25f8-11eb-9a5c-4efb51070b79.png)

**Expected Result:**
while "Mnemonic passphrase" is getting loaded, Listeners should not get restart.

**Comment by bayk** [comment]
@vinayaga07   it is how mwc713 works in the past, but we should change it. For now I think there is no reasons to restart the listeners. I will probably fix that.
