### ISSUE TITLE
In Explorer MWC Transaction Proof page, "Amount" value got truncated after 4 decimal values.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#610]
Description:
In Explorer MWC Transaction Proof page and observed "Amount" value got truncated after 4 decimal values.

Steps to reproduce
1. Transferred 0.0000001 MWC from one wallet to another.
2. In Explorer MWC Transaction Proof page, Amount is getting displayed as  0.0000 MWC.
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/99416763-354e9700-291f-11eb-9b62-ae6476e5978e.png)
****
Proof attached here with.
[Nov-17-1.proof.zip](https://github.com/mwcproject/mwc-qt-wallet/files/5554773/Nov-17-1.proof.zip)

**Comment by bayk** [comment]
Explorers are updated.  Here is how the proof looks like now

![image](https://user-images.githubusercontent.com/42393608/99592813-8ef9a480-29a5-11eb-9a12-a882729e3478.png)

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
