### ISSUE TITLE
[QT-Wallet] During Automatic Swap, observing error messages.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#612]
**Description:**
During Automatic Swap, observing error messages.
Please refer the screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/99701357-5d263200-2aba-11eb-9a12-340e1431494b.png)

**Comment by vinayaga07** [comment]
mwcwallet.log.zip

**Comment by bayk** [comment]
Note, to reproduce wallet need to be connected to the offline mwc node. The message need to be rewritten in a way that makes more sense for the user.

**Comment by bayk** [comment]
Now you should see the errors: 

At the list page:
![image](https://user-images.githubusercontent.com/42393608/99719785-9f6f5500-2a61-11eb-8990-19d65eb4ecc0.png)

At thee details:
![image](https://user-images.githubusercontent.com/42393608/99719874-bca42380-2a61-11eb-92ff-9e1deb62047b.png)

**Comment by vinayaga07** [comment]
Closing this ticket.
