### ISSUE TITLE
[Swap] Unable to copy the intermittent BTC address from the receiver QT wallet MWC Swap Trades pages.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#614]
**Description:**
Unable to copy the intermittent BTC address from the receiver QT wallet MWC Swap Trades pages.

**Expected Result:**
1. User should have the option to copy the Intermittent BTC address Swap Trades page.

**Actual Result:**
It is very difficult to manually type the  Intermittent BTC address on the Receiver Electrum wallet to send BTC.

**Comment by bayk** [comment]
This issue is Fixed. I found the QLable can be selectable. I will update some UI pages where we use Edits instead of QLables for that.

**Comment by vinayaga07** [comment]
Verified the fix, hence closing this ticket.
