### ISSUE TITLE
[Swap Trade] Transaction amount mismatch observed

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#615]
**Description:**
Using Swap Trade, transferred 0.020 MWC from Sender but receiver received 0.016 MWC only.

From Sender 0.02 + 0.008 (fee) MWC (totally 0.028 MWC) has been deducted but receiver received 0.016 MWC only.

**Expected Result:**
Exactly 0.02 MWC should be transferred to the receiver.

Please refer the below screenshots for more details.

**Sender Transaction Details**
![image](https://user-images.githubusercontent.com/63310656/99835639-e60c9e80-2b8a-11eb-9ae9-b62b5d7e54e9.png)

**Receiver Transaction Details**
![image](https://user-images.githubusercontent.com/63310656/99835846-35eb6580-2b8b-11eb-8235-bd69f0b1ac37.png)

**Comment by bayk** [comment]
@vinayaga07 , it is expected.  Transaction goes through mulisig account.  If A swap with B,    The MWC goes first to Lock account (that is fee that you see at the ticket), so Loc account will get 0.02 mwc. then from Lock account to B (that transaction you don't see and it is from where another 0.004 comes). Lock account will pay another 0.004 for the fees.

Similar workflow is for the BTC

**Comment by vinayaga07** [comment]
@bayk , Is it possible to display this information in the Swap Trade page ?

**Comment by bayk** [comment]
I don't see where we can display it. It is more "Learn More" and "FAQ" section. I don't think it is a critical fact that need to be put into UI. We want to keep UI simple. 
Also this problem is same for all swaps. There are 2 transactions for both parties.

**Comment by bayk** [comment]
Moved to fixed since nothing can be done about that

**Comment by vinayaga07** [comment]
Closing this ticket.
