### ISSUE TITLE
[SWAP] Receiver MWC wallet Label need to be renamed.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#616]
**Description:**
Have initiated Swap trade from the Sender MWC wallet and on the receiver MWC wallet observed the label "BTC address to receive the coins" which is confusing. 

**Expected Result:**
On the receiver MWC wallet label should be "**BTC address to send the coins**".

![image](https://user-images.githubusercontent.com/63310656/99837089-00e01280-2b8d-11eb-8dfa-9d30d275a6b2.png)

**Comment by bayk** [comment]
@vinayaga07 ,  it is the address for the refund. In case if transaction will be cancelled, Buyer will get the BTC back to this account. So it is not send, it is receive. I will put refund there to be more clear.

**Comment by vinayaga07** [comment]
That's perfect!

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/99917280-14da6000-2cc4-11eb-8ccc-0bec049ffb23.png)

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
