### ISSUE TITLE
[SWAP] Low amount Swap will fail due to "dust", Seller can't redeem BTC

### ISSUE THREAD

**Issue by MrCryptoT** [mwcproject/mwc-qt-wallet#618]
**Version:** 

OS: Windows 10 [Version 10.0.18363.1198]
QT-Wallet: 20201119.2.beta
Log: [mwcwallet (4).log](https://github.com/mwcproject/mwc-qt-wallet/files/5578059/mwcwallet.4.log)

**Description:**
Have initiated Swap trade from the Sender MWC wallet and after posting the Buyers BTC Lock Transaction and waiting for needed MWC blocks for the Locktime, the Sender/MWC-Sellers BTC Redeem Transaction fails due to the below Error.
The Buyer received the MWC from the Swap, so the MWC redeem TX for the buyer worked. But the Seller never could redeem his BTC from the Swap as of now.

> "Swap Error, Electrum Node error, Received Error: the transaction was rejected by network rules

I assume this is due to "dust" as the electrum Server seems to complain that the BTC Amount is "Dust" (too low) but I am not entierly sure about this.
The BTC Amount used in the Lock Transaction was around 0.0001 BTC. (See next line from the logs for the hint "dust") 

> 20.11.2020 22:11:57.610 MWC713 emit onPerformAutoSwapStep with de43e226-9b30-4435-bab5-fe60a04d92ec, SellerRedeemSecondaryCurrency, Posting BTC redeem transaction, Redeem Secondary Currency, Swap Error , Electrum Node error, Received error: the transaction was rejected by network rules.
> 
> dust
> [0200000001f5f259df83498347ed4f80e4155bd6fac871319da1bda4b9d94c86880ec3e53300000000fd080100473044022003e76ee01ab156b939861f6b2f4c0ccebaae0a709cdb1b73f4dd26d2ecda1c55022054110dcb2e5a265c7232d4e1d27854596d75df6ac3f971b51857a6c0ae2bc05c0147304402203b84b5349ecc8dd5a70dcb6f817c684b9eff5db62a0e19ad338443a9fee29fcf022027c8cee57e54a0cbe5e3811f2ea0dd0009987a955db547f41fb5cb6dc57f0c0e01004c7463045f1cba5fb1752103db48c7ded67098a019fdbf92630d6e141e2f7be6e842c2423c6b3797afd054f1ac67522103ca6df273ebe887c02a2618bd4735f321bcdbeed9eff467add3db0e54dde3fe7d210329fb0731a2534cdad8f0b2ee18ba3d08ffd507b9b29ed4b66371784c8dca46c452ae68000000000100000000000000001976a914aa8169e4ef9a794fb96b54f33f735e60f70c7db988ac00000000]
>  Backtrace:    0: <unknown>
> 

**Reproduction:** 
The exact Values used for the Swap can be seen here: 
![image](https://user-images.githubusercontent.com/8693733/99883535-6fbe7980-2c28-11eb-99e4-732f024c7f99.png)

**Expected Result:**
I would expect the BTC redeem TX should be able to post at this stage as the trade was nearly completed. Or that if it is due to a "dust" amount used, the User should not be able to create a Swap offer that will fail "due to network rules".

**Guesses:** 
I guess the "Dust" Amount of the Electrum Server is either:
1)Configured really high (unlikely out of the box i guess) 
2)The default "dust" Value is above 0.0001 BTC which was used for this test, if so we may want to warn users about this. 

This whole "Dust" theory is all based on the 1 word dust in the logs tho, I may be off track here.

Attatched is a full Log of the Day I encountered the Issue for full stack traces, tho they seem rather empty. 
Have a good day ☕

**Comment by bayk** [comment]
Closed because minimum amount of BTC are introduced and already released. Because of that dust amount shoudn't be possible.
