### ISSUE TITLE
QT wallet on Windows platform is not displaying wallet Type - Mainnet/Floonet on the wallet Login page.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#619]
**Description:**
QT wallet on Windows platform is not displaying wallet Type - Mainnet/Floonet on the wallet Login page.
Please refer the screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/99990914-6b39c280-2dda-11eb-8ebf-91a5437aa324.png)

**Note:**
Not observed the same issue on Mac platform.

**Comment by bayk** [comment]
@vinayaga07 ,  It display only if you have both Mainnet and Testnet wallet. If all the wallets of the same type, there is no reason to display that. Market as fixed, please check if it shows type if you have wallets at different network.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
