### ISSUE TITLE
MWC-QT-Wallet[Spelling and Grammatical issues]

### ISSUE THREAD

**Issue by JiraiyaMalard** [mwcproject/mwc-qt-wallet#621]
This will be a general issue used to communicate spelling and grammatical issues as they are found. Currently this will be assigned to bayk as these should pertain to the atomic swap feature.

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/100031150-c4d5c900-2da9-11eb-9b4a-9cb795340ec3.png)

For the following screen showing information to the party starting the swap, it should read:

**Required** lock ....

In case **the trade is** cancelled...
...**The other party's** BTC...

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/100031341-3e6db700-2daa-11eb-901c-60e50e169099.png)

Should read: ... has been successfully created.

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/100031427-7bd24480-2daa-11eb-88ea-1a9899f4af3d.png)

**Comment by jbyrer** [comment]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/10661009/100031819-63aef500-2dab-11eb-9a25-a8d4057efda7.png">


Time limits: 1 hr for messages **to be exchanged** and 1 hr for ...

MWC funds **will be** locked until block ..., **and are** expected to be mined....
BTC funds **will be** locked ...
Private **instances provide** extra...

**Comment by jbyrer** [comment]
if you press accept on the (to accept a swap) without filling in the btc address:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/10661009/100032027-e20b9700-2dab-11eb-90cd-ad6f35f256a5.png">

Please define **the** BTC address...

**Comment by jbyrer** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/10661009/100032141-2434d880-2dac-11eb-9843-eb042cfbd01d.png">


Please backup **the** data  for the swap .....

We strongly recommend **that you** backup the trade data to **a separate data storage device, like** a ....
....this backup will be the only way to restore the trade and get (no "an") access ...

**Comment by jbyrer** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/10661009/100032343-a7eec500-2dac-11eb-964f-64a47d90b42a.png">

This applies to the popup too:
Please deposit exactly ... BTC **to** ...

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/100032433-dec4db00-2dac-11eb-94d1-6e650b7822c8.png)
Swap offer created (no is)

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/100032483-f9974f80-2dac-11eb-9f6b-d68d215efbb8.png)

MWC lock state posted (no is)

**Comment by jbyrer** [comment]
<img width="728" alt="image" src="https://user-images.githubusercontent.com/10661009/100032581-2fd4cf00-2dad-11eb-8e53-38c39bb2751f.png">

Cancelled because **the** buyer posted funds greater than the expected amount to the lock account...

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/100032744-8215f000-2dad-11eb-8e41-74fbcb8c28fe.png)

...because the buyer posted funds greater than the agreed upon amount to the Lock account

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/100036034-39ae0080-2db4-11eb-901a-3f5e688c638f.png)
Please specify **_a_** BTC ..

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/100036130-7974e800-2db4-11eb-9c4b-c532934651ac.png)

**Comment by jbyrer** [comment]
![Uploading image.png…]()

**Comment by jbyrer** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/10661009/100036397-fdc76b00-2db4-11eb-9ccf-ab136f3a72e3.png">

Please specify **_the_** number of confirmations ....

**Comment by jbyrer** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/10661009/100036483-25b6ce80-2db5-11eb-9960-a05dcf213e9b.png">
Please specify **_a_** correct ...

**Comment by jbyrer** [comment]
<img width="175" alt="image" src="https://user-images.githubusercontent.com/10661009/100037165-74b13380-2db6-11eb-8017-2ab49786e11d.png">
Receive a swap offer

**Comment by jbyrer** [comment]
<img width="259" alt="image" src="https://user-images.githubusercontent.com/10661009/100037230-8c88b780-2db6-11eb-97e3-5ce64900cea1.png">
Seller has started locking MWC funds

**Comment by jbyrer** [comment]
<img width="268" alt="image" src="https://user-images.githubusercontent.com/10661009/100037304-ae823a00-2db6-11eb-8f97-8313edf4dd05.png">
Funds have been posted to the **_l_**ock account

**Comment by bayk** [comment]
At tomorrow build should be fixed until this point.  Let's keep the ticket open for more updates.

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/100270655-3bd7a280-2f0d-11eb-8b86-872dbef0a5f0.png)
Waiting for locked MWC to be refunded.

**Comment by bayk** [comment]
Updated until this point. The build will be ready in an hour

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/100635122-f9cfa780-32e4-11eb-9f91-6e50edff9763.png)

Redeem transaction has enough confirmations.

**Comment by bayk** [comment]
Updated by this point

**Comment by bayk** [comment]
Moving to fixed since it is included into the release
