### ISSUE TITLE
[MWC-QT-Wallet] message

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#625]
When using 2 screens, this message popped up while sending an atomic swap (osx)
![image](https://user-images.githubusercontent.com/10661009/100036743-a5dd3400-2db5-11eb-8fa5-de3c8760c514.png)

**Comment by scasaletto** [comment]
Can you give me more info on this? Which screen was Qt Wallet being displayed on? Are you saying that the message popped up on the screen without the wallet? Which screen had your cursor focus? If you could give me steps to duplicate the issue, that would help.

**Comment by jbyrer** [comment]
Sure, the wallet was on a different screen than where the message popped up, the cursor was also on the different screen.

**Comment by jbyrer** [comment]
I have been trying to replicate this today, but no luck so far.  We have mad a large number of fixes to spelling and grammatical issues with messages, it is possible K fixed this already.  For now I will close the issue, and if I am able to replicate it again at some point, I will re-open.
