### ISSUE TITLE
[MWC-QT-Wallet] When exiting the wallet, an error message is displayed indicating swaps in progress even though there are none

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#629]
![image](https://user-images.githubusercontent.com/10661009/100254480-38392100-2ef7-11eb-8819-202854ae9575.png)
You can see from the image above, there are no current incoming or outgoing swaps.  In addition, the text should read:

You have 2 trades in progress.  **_The_** wallet **_needs_** to stay online to process the swaps.  Are you sure you want to close the wallet even **_though_** your trades are not finished.

**Comment by bayk** [comment]
It is possible if swaps just finished. Execution engine have some delay, probably up to a minute. I will update that.

**Comment by jbyrer** [comment]
confirmed fixed
