### ISSUE TITLE
resync full node allows you to click on other tabs which will cancel resync

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#63]
Other buttons should be disabled during resync.

**Comment by bayk** [comment]
They will not canceled, it will finish occasionally. But yes, we should disable that because sync task is very long and that is why the next requests to mwc713 will be waiting for a while. So UX will be not good.

**Comment by bayk** [comment]
Hide all controls for resync page:

![image](https://user-images.githubusercontent.com/42393608/64046783-9b37de80-cb21-11e9-8b1e-d0b0bb274408.png)
