### ISSUE TITLE
Buyer post too low amount. We should show how much is waiting in the memory pool.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#632]
Currently I see "Status: MWC funds are locked; BTC Lock transaction is in the memory pool, waiting to be mined"

We want to see something like this, MWC funds are locked; 0.0004 BTC Lock transaction is in the memory pool, waiting for another 0.0006 BTC"

**Comment by bayk** [comment]
For small amount the status is incorrect:

Status: MWC funds are locked; BTC funds are locked

Issue: it should be create that Buyer DIDN'T post enough BTC.
This problem is critical, need to be fixed.

**Comment by bayk** [comment]
Testing:  Let's buyer post smaller amount and see is Status on both sides will represent that more BTC are needed.

**Comment by vinayaga07** [comment]
Successfully verified the status on both Sender and Buyer.
