### ISSUE TITLE
UI/UX Improvements

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#656]
Change requests from Jon.

**Comment by bayk** [comment]
Here are the changes:

Few changes at the create swap trade screen 1

![image](https://user-images.githubusercontent.com/42393608/100680147-cf520e80-3325-11eb-8777-67f97c189d78.png)

Swap list:
  the tab name.  
 swap initial time instead of time interval for this tab only.

![image](https://user-images.githubusercontent.com/42393608/100680267-07595180-3326-11eb-8de3-1f4274f23833.png)

All Swap review info has Rate now

![image](https://user-images.githubusercontent.com/42393608/100680388-4a1b2980-3326-11eb-95f5-aa7d2a4592a6.png)

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
