### ISSUE TITLE
Swap error message on Receiver wallet down

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#658]
**Description:**
While Swap trade is in-progress, Receiver wallet was offline, hence Swap Trade got failed as expected but error message received on the Sender wallet need to be improved.

**Actual Result (Error message)**

Processing error: Swap Error , Unable to deliver the message 938da682-20b6-42a8-bfc3-afca70165440 by tor: Adapter Callback Error, Posting swap message (is recipient listening?): Request error: Cannot make request: error trying to connect: Unsuccessful reply: HostUnreachable

**Expected Result:**
Processing error: Unable to deliver the message 938da682-20b6-42a8-bfc3-afca70165440 by tor.
Request error:  Error trying to connect: HostUnreachable

Error messages should be simple and easy to understand by the End User.

![image](https://user-images.githubusercontent.com/63310656/100757794-cc821700-3414-11eb-8314-780815b9a9f1.png)

**Comment by bayk** [comment]
It is fixed but build wasn't triggered. The message will be:

Unable to send message to another wallet for trade 00ac6fb3-b751-402d-b2bc-f1ca67e7dbbf, error trying to connect: ......

**Comment by vinayaga07** [comment]
Verified the fix, hence closing this ticket.
![image](https://user-images.githubusercontent.com/63310656/100889902-ac6a5a80-34dd-11eb-96c9-0a0560e57f0a.png)
