### ISSUE TITLE
[MWC-QT-Wallet] Grammar - error message  (unable to connect to tor recipient)

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#662]
![image](https://user-images.githubusercontent.com/10661009/101109457-d24e3880-358b-11eb-8b89-57ff474a00b5.png)

Your send request **_has_** failed.
Unable to connect to the receiving wallet.  The receiving wallet may be offline, or you may be experiencing connection issues.

Because this is only in an error message, I don't THINK it warrants a rebuild of the release candidate; however, if we end up rebuilding, we may want to get this in there (I assume it is a 1 line fix, if it is difficult, nvm).

**Comment by vinayaga07** [comment]
Verified with the latest build and got the below error message, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/105202476-0d222500-5b68-11eb-8f28-8df6aab7b9ce.png)
