### ISSUE TITLE
Flag that enforce Armored slates.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#663]
With current approach the wallet is keeping the lowest version of the slate. That allow to maintain backward compatibility, so our users are happy.

But for the armored slates has the highest version (V4) and no features that can trigger wallet to use it.
It is applicable to:

- wallet REST API
- wallet send/receive with files, MQS
- wallet send with HTTP/TOR is covered because other party supported version is know and will be used.

The proposed solution:
- For rest API  we can add OPTIONAL flag: "slate_v4".  If flag is there, then Armored slate will be used.
- For the files and send with MQS, wallet will need an extra argument about that. That argument need to be propagated into mwc713 and QT wallets. On QT wallet at the config we want to have this flag. By default it is false.

To understand the problem please search for the 
slate.lowest_version()  at  mwc-wallet source code.

**Comment by bayk** [comment]
It make sense to do with a rebase.

**Comment by suemto** [comment]
I read the source and now I understand the problem here.

https://github.com/mwcproject/mwc-wallet/blob/3.3.0/impls/src/adapters/mwcmq.rs#L414-L415
https://github.com/mwcproject/mwc-wallet/blob/3.3.0/api/src/owner_rpc_s.rs#L2261-L2262

```Rust
		let version = slate.lowest_version();
		let slate = VersionedSlate::into_version(slate.clone(), version);
```
It will always force to use lowest version, i.e. `V3`.
```Rust
	/// Calculate minimal Slate version. For exchange we want to keep the varsion as low as possible
	/// because there are might be many non upgraded wallets and we want ot be friendly to them.
	pub fn lowest_version(&self) -> SlateVersion {
		if self.payment_proof.is_some() || self.ttl_cutoff_height.is_some() {
			SlateVersion::V3
		} else {
			SlateVersion::V2
		}
	}
```
So the `SlateVersion::V4` will never be used in our wallet.

But "add OPTIONAL flag" will also require an upgrading on exchanges, right?

**Comment by bayk** [comment]
Optional flag must be really optional. The payloads for API like send get an input as Json. Serde deserializer can handle that if object field is  Option<bool>.  The default will be nothing or false.

**Comment by bayk** [comment]
Closed because it is already implemented and tested. From API point there are a slate version. The wallet is able to contact other party and request if slatepacks are supported and use them in this case.
Only exception is MQS. But MQS has it's own encryption, so it is not an issue.
This workflow was tested by me. I was able to see that wallet switch for slatepacks for tor and http integration is other wallet support that. Otherwise it use legacy V3 without compact slates.
P.S. The most critical it is a compact slate feature, not a data format. But naturally both of them are used together.
