### ISSUE TITLE
SWAPS, Incorrect error handling for wrong tor address

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#665]
![image](https://user-images.githubusercontent.com/42393608/101401206-d8dbf900-3886-11eb-80c4-228f65b9bcde.png)

![image](https://user-images.githubusercontent.com/42393608/101401230-e1343400-3886-11eb-8568-a64b05ec0d1e.png)

The issue was a tor address

**Comment by bayk** [comment]
Update:  BTC  fees edit is too small

![image](https://user-images.githubusercontent.com/42393608/101403109-94059180-3889-11eb-8ee2-e941a95656ab.png)

**Comment by bayk** [comment]
Update:  
At accept page we need to say "Bitcoin sending address will be provided at a future step"

**Comment by bayk** [comment]
Update: BTC Address  add 'Legacy address'

**Comment by Viv-dev-mwc** [comment]
Verified, hence closing this ticket.
