### ISSUE TITLE
HTTP listener indicator should show local/global flags.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#668]
Currently HTTP listener indicator is the same for listening locally on 127.0.0.1 or globally on 0.0.0.0.
We better to have different indicators about that

**Comment by bayk** [comment]
Based on the feedback, HTTP Foreign API Listener  dialog is updated. Here is how it looks like now

![image](https://user-images.githubusercontent.com/42393608/104958075-3b470f80-5984-11eb-9d3e-35ac63961a1e.png)

![image](https://user-images.githubusercontent.com/42393608/104958094-41d58700-5984-11eb-8ee4-6369e6fa1546.png)

![image](https://user-images.githubusercontent.com/42393608/104958105-4863fe80-5984-11eb-9049-da4bb6d8689d.png)

![image](https://user-images.githubusercontent.com/42393608/104958186-67629080-5984-11eb-9c36-2ed380a18262.png)

**Comment by bayk** [comment]
Confirmed that screenshot match the expected UX. 
Testing:
The app should behave the same way as it did before. Also "Advanced" can be used to view the settings from Local & Local and Internet. Think about "Local", "Local and Internet" as special values that we can recognize. If you specify those values at "Advanced", on the next call it will switch to appropriate choice.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
