### ISSUE TITLE
Display transaction fees on confirm screen

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#67]
I think it would be a good idea to display the transaction fees on the confirms screen.

**Comment by bayk** [comment]
We talk with Chris about that. Yes, it is nice to have feature, but it is not easy to implement. Fee is not a constant, so we will need additional request to mwc713 to calculate the fee.
We can start to implement that only when we finish with other bugs.

**Comment by bayk** [comment]
For send we already have that logic. We can implement in on QT wallet level. I don't think it is worth to add new API for mwc713 wallet for that even internally this API already exist

**Comment by scasaletto** [comment]
The transaction fees are now displayed for send online and send offline by file. They are not displayed for transferring funds between accounts as there currently is not a confirmation screen for that.
[mwc_txn_fees.txt](https://github.com/mwcproject/mwc-qt-wallet/files/4674163/mwc_txn_fees.txt)
