### ISSUE TITLE
[Mobile Wallet] UI alignments are not proper.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#673]
**Description:**
Deployed latest Mobile wallet on 6.2 inch Android Mobile and observed UI alignments are not proper.
Please refer the below screenshots for references.

![image](https://user-images.githubusercontent.com/63310656/102793832-73cceb00-43d0-11eb-988b-9112c2f571c5.png)

![image](https://user-images.githubusercontent.com/63310656/102794005-b393d280-43d0-11eb-90ac-993afd706073.png)

**Comment by bayk** [comment]
@sarawut11 ,  traditional formatting are by 6 words in the line (it is what QT wallet does). For mobile I think 4 words in the line is fine, so that will be 6 rows.

**Comment by vinayaga07** [comment]
In Mobile wallet, I could see 6 words in a line (Total 4 rows), hence reopening this ticket.

![image](https://user-images.githubusercontent.com/63310656/108738236-6ad7d180-7559-11eb-8aba-21167a3a44fb.png)

**Comment by sarawut11** [comment]
why is it an issue? 6 words * 4 rows -> It is what qt desktop works
many rows increase the box height and it's not good to manage the space in mobile
traditional way is fine to use. @vinayaga07

**Comment by vinayaga07** [comment]
In 6.2 inch android mobile, Passphrase looks misaligned. If we display 4 words in a row, then it looks perfect. 

![image](https://user-images.githubusercontent.com/63310656/109324253-6cb3d480-787a-11eb-9fbe-ee77f89a4dae.png)

**Comment by bayk** [comment]
@sarawut11 ,  can you show 6 words per line in a landscape orientation and 4 words per line in portrait orientation. That should help.

**Comment by vinayaga07** [comment]
Verified.
