### ISSUE TITLE
[Mobile wallet] Unable to create new wallet instance and getting invalid passphase error message.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#675]
**Description:**

Deployed latest Mobile wallet on 6.2 inch Android Mobile.
While creating new instance, entered correct 1 passphrase but getting the error  message and unable to proceed further.

![image](https://user-images.githubusercontent.com/63310656/102798513-3fa8f880-43d7-11eb-8aca-b8fdd0baf994.png)

**Comment by bayk** [comment]
@sarawut11 ,  you need to convert words to low case. At least my phone automatically adding capital letters to the words.

**Comment by vinayaga07** [comment]
@sarawut11 ,
Verified with the latest build and still observed words are getting converted into capital letters.

**Comment by sarawut11** [comment]
I can't handle this since all works well on my side. As discussed in the last engineering meeting, can you handle this capital work? @bayk

**Comment by bayk** [comment]
I will handle that on wallet side. Passphrase words will be converted to lowcase.

**Comment by bayk** [comment]
Just tested, I can enter mixed words for words test and for mnemonic wallet restore.

**Comment by vinayaga07** [comment]
Verified with the latest build and able to provide both Lower & Captial case letters.
