### ISSUE TITLE
[Android Mobile wallet] Button Labels are in CAPS

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#676]
**Description:** 
In Android Mobile wallet, Button Labels are in CAPS rather it should be in Camel case (same as QT wallet).

Please refer the below screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/102904450-c02f2e00-4497-11eb-9c1e-fe8d94f4668b.png)

**Comment by bayk** [comment]
@sarawut11 ,  also HTTP indicator for mobile doesn't needed.  For the mobile we don't expect users to do port forwarding.

For the QT desktop wallet there is a ticket about HTTP Local/Global  indicator.  For the mobile it will be only http Local and it doesn't give user any information. I think the easiest way to fix - just delete the indicator for HTTP.

**Comment by bayk** [comment]
@sarawut11 , this page is looks fine for me. But there is another issue.

Please rename MWCMQ  to MWCMQS.   There is indicator and a button with that word.

Also 'Receive by Slatepack'  takes too much space. But I don't know how to reduce the text size. So let's keep it as ti is.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
