### ISSUE TITLE
Show separators on transaction screen table 

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#68]
I think it might be helpful if there was at least a faint separator between the columns displayed on the transactions table.  As the number of rows grows, it may become harder to distinguish between columns.

**Comment by bayk** [comment]
I can try highlight the columns a little, like we do for the odd/even rows. That might improve visual effect. Bright and very visible separators will not fit into the design that we get from Brent.

**Comment by bayk** [comment]
Jim, we can't show grid because it make look worse and it is against Brent design.
I did try to highlight columns with gradient color. It doesn't look better

![image](https://user-images.githubusercontent.com/42393608/64043766-17c6bf00-cb1a-11e9-8ed4-4c3b5af2ceaf.png)

**Comment by bayk** [comment]
So far Brent's design looks the best
