### ISSUE TITLE
In Mobile Wallet "Account Options", need to have "Accounts" Page.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#681]
**Description:**
In Mobile Wallet "Account Options", "Accounts" Page is missing.
This tab allows you to manage accounts, you can add as many accounts .

In QT wallet, we have the page to display "Accounts" expecting the same page in Mobile wallet too.

Currently "Account Options" page has only  "Show PassPhrase" , "List Contacts", "Log Out" .

![image](https://user-images.githubusercontent.com/63310656/102909034-55cdbc00-449e-11eb-8125-864b41513470.png)

**Comment by sarawut11** [comment]
@bayk & me discussed not to involve accounts in this page since we have overview page which is only available in mobile
and we have accounts in the overview page.
So we agreed not to duplicate the same thing in the account options page.

**Comment by bayk** [comment]
Yes, we discuss that. I think the problem now is the name of that page. "Account Options"  without accounts button. So should rename the page or return button back so the content will match the name.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
