### ISSUE TITLE
Android Mobile wallet, Login Page-->Help link is not clickable.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#683]
**Description:**
Android Mobile wallet, Login Page-->Help link is not clickable.

![image](https://user-images.githubusercontent.com/63310656/103013845-d2769e00-4563-11eb-823c-445c0e35756d.png)

**Comment by bayk** [comment]
@vinayaga07   @sarawut11 ,  I am thinking about that "Help" as "Learn More". We probably can put a link to the MWC website there. What do you think?

**Comment by vinayaga07** [comment]
@bayk Prefer to have the same naming conversion as QT wallet.

**Comment by bayk** [comment]
QT wallet doesn't have that button, there is Open Wallet that is not applicable to Mobile.

**Comment by sarawut11** [comment]
I removed help button here, let's see "Learn More" button later after fixing all the issues.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
