### ISSUE TITLE
Slatepack support at QT wallet

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#684]

**Comment by bayk** [comment]
Here is a changes  for the slatepacks on QT wallet side
https://github.com/mwcproject/mwc-qt-wallet/blob/master/DOC/bridge_change_history.md#january-5-2021

Testing.
1. Check the doc above, ignore the bridges part, check that you can reach UI elements and you see the changes.
2. Check if  send/receive with slatepacks works. QT wallet understand the text, QR code should be converted to the same text by QR reader. Also QR code you can save.
3. Check if Proofs generated with all settings for the slatepacks.
4. Check if proofs are generated with files.
5. Check if proofs are generated with tor transactions.
6. Check if proofs are generated with MQS transactions.
7. Check if 'Lock on finalize' works as expected. 
8. Verify backward compatibility as usual. The slatepack is supported by the new version only. New and old wallets should work with each other without a problem.
9. I will verify that send with tor and http  select slates V2/V3 when interacting with old wallets  and switch to encrypted slatepack for a new wallets. 
10. Validate REST API. Owner V2 & V3 now has the same functionality.  And they get a slatepack support. Our doc tests cover it, so it is documented. Please try and check how it looks from UX point of view.  Also Foreign API does support slatepacks now as well.  https://mwcproject.github.io/grin_wallet_api/trait.OwnerRpcV2.html
11. Verify if address at transactions is correct for all types of interactions with proofs and without proofs.

**Comment by bayk** [comment]
Update about #9  "I will verify that send with tor and http select slates V2/V3 when interacting with old wallets and switch to encrypted slatepack for a new wallets."
We need to change the send methods logic in order to handle that. I will create a ticket about that.

**Comment by bayk** [comment]
There are bunch of tickets for UI related changes. Let's keep all changes with this ticket so it will easier to track them

**Comment by vinayaga07** [comment]
Closing this ticket.
