### ISSUE TITLE
QT wallet need to validate network and coin values in the payload

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#685]
After rebase wallets will add coin and network information into the slates. We need to check those optional fields at QT wallet.
It is related to file operations.

**Comment by bayk** [comment]
Done with a slatepack integration. 
Testing: 
- try send/receive files and slatepacks between floonet/mainnet. You should see the error
- Try the same for tor.
- For MQS that problem should be caught on address level, probably QT wallet will catch that.
- Try swaps. One wallet on mainnet,  another of floonet.

**Comment by vinayaga07** [comment]
Verified the possible combinations, hence closing this ticket.
