### ISSUE TITLE
Mobile Wallet: Logo need to be corrected.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#686]
**Description:**
In Mobile Wallet Login Screen - MWC Logo is not displaying same as QT wallet. 

![image](https://user-images.githubusercontent.com/63310656/103559576-5e7db380-4edc-11eb-9922-75047a8127a1.png)

**Comment by bayk** [comment]
@vinayaga07 , we need a designer for that. Let's keep how it is for now.

**Comment by vinayaga07** [comment]
@bayk 
Here with given below the Login screen comparison between Mobile wallet and desktop wallet.
Logo / MWC symbol looks different. Expecting both should be same.

![image](https://user-images.githubusercontent.com/63310656/103663941-ae6d8080-4f97-11eb-9b7c-07aeff80274b.png)

**Comment by bayk** [comment]
Let's use Desktop logo.  The layout is better, it takes less space vertically.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
