### ISSUE TITLE
Slatepacks support for Mobile Wallet

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#689]
Here are the changes that was done. In order for mobile to support the slatepacks, the same need to be done for the mobile wallet.

Here is changes.
https://github.com/mwcproject/mwc-qt-wallet/blob/master/DOC/bridge_change_history.md#january-5-2021

Here is a ticket with transactions  https://github.com/mwcproject/mwc-qt-wallet/issues/684

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
