### ISSUE TITLE
finalize tab stays highlighted after clicking on other tabs

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#69]
See screenshot.
<img width="1006" alt="Screen Shot 2019-08-30 at 9 30 37 AM" src="https://user-images.githubusercontent.com/7232183/64036820-f14c5800-cb08-11e9-9e29-67dff381c5a1.png">

**Comment by bayk** [comment]
That is already fixed. It is what I write in update yesterday.
