### ISSUE TITLE
Slatepacks with noise

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#698]
Check if slatepacks string can be with a noise. With some prefixes, suffixes, new line in the middle.

**Comment by bayk** [comment]
Fixed at the latest build.  Slate like this work

   BEGINSLATE_BIN. 32FieTgWJm117kD aRxosU8GC9f9R9e tz5GaRfiWn
mUgV5 me91yumfFEnooDh xoK5EHsQry3dema QxdEBi8be6pnXiz am9qwzZf4EMiBqL rDuqWKPuf
wKaMNj aUiZ  HZizD 5217bG 2drHRZ6QfRWeNMb 
G1DEYVn2dg4KdB3 iF81MZ3gem6g8uo XuapKpR3GfKAGxv qsryjLzYbdNqtfX xX9C2jgQrvK  XpEK 5qx94MbwhZHy2Ni T. ENDSLATE_BIN   dl;kds  ldslkdfkdfsk some noise at the end

Testing:
It is expected that slates are send by email. Emails can add new line symbols and format the text. Users will do copy/paste that text. Please check if we handle that.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
