### ISSUE TITLE
Add 'Finalize' widow to the final send slatepack window

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#700]
Here we can have a finalize window below. There alos we can accept ONLY the finalize slatepack for the same transaction.

![image](https://user-images.githubusercontent.com/42393608/103808726-46598180-500d-11eb-97b6-9d5989d5ceea.png)

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
