### ISSUE TITLE
[QT wallet] On the "Finalize Slatepack page"  unable to enter values for the Message box.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#702]
**Description:**
In the QT wallet, on the "Finalize Slatepack page"  unable to enter values for the Message box.
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/103914519-f4f5e300-512f-11eb-99d6-5163c9836fc8.png)

Platform: Mac OS.

**Comment by bayk** [comment]
UI looks more clear, to you can see that you are not supposed to enter anything here.

**Comment by vinayaga07** [comment]
Verified the fix with the latest build, hence closing this ticket.
