### ISSUE TITLE
[QT wallet] on the "Finalize Slatepack page"  Amount & Lock height values are empty.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#703]
**Description:**
In the QT wallet, on the "Finalize Slatepack page"  Amount & Lock height values are empty.
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/103915195-e78d2880-5130-11eb-9842-719b2044eee9.png)

Expecting the fields like Amount & Lock height should have correct values.

**Comment by bayk** [comment]
Fixed in current build. Those values will be filled after short delay

**Comment by vinayaga07** [comment]
Verified with the latest build and observed "Lock Height" is not getting updated. (waited for ~5 mins)

![image](https://user-images.githubusercontent.com/63310656/104203065-b757c980-5451-11eb-9c4a-b6f4b7dad321.png)

**Comment by bayk** [comment]
Lock Height normally is not set.  It is expected. 
Lock Height can limit when transaction can be spent. We are assuming that other wallets might exist, that is why we show this.
In QT wallet you can't set Lock Height.  With mwc-wallet Rest API probably can, I didn't check.  My point that we should show this value even normally it is empty.

**Comment by vinayaga07** [comment]
Closing this ticket,  as per the above comment.
