### ISSUE TITLE
[QT wallet] on the "Receive Slatepack page" unable to enter values for the Message box.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#704]
Description:
In the QT wallet, on the "Receive Slatepack page" unable to enter values for the Message box.
Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/103916679-b7df2000-5132-11eb-86d2-e48c247b97b6.png)

**Comment by bayk** [comment]
Here we are showing the message from sender. But it is possible to support messages from any party. By wmc-wallet design any party can add some messages.

**Comment by bayk** [comment]
Build just started, nightly will be updated in an hour

**Comment by vinayaga07** [comment]
Verified the fix, hence closing this ticket.
