### ISSUE TITLE
Mobile wallet, retire  bridge::FileTransaction.  Add tx description for receive

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#706]
Original ticket with changes  https://github.com/mwcproject/mwc-qt-wallet/issues/704

We had wnd::FileTransaction and  bridge::FileTransaction  that serve both Receive and Finalize pages. 
Functionality of Receive and Finalize becoming more different. The original ticket introduce another complexity with  descriptions. 
Because of that I separate that into 
wnd::FileTransactionReceive  + bridge::FileTransaction
wnd::FileTransactionFinalize  + bridge::FileTransactionFinalize

bridge::FileTransaction exist only for mobile and it doesn't support adding message on receiver side.
Also please check the naming, it is slightly different on those pages.

**Comment by bayk** [comment]
I see that it is fixed, I can add description on my side.

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
