### ISSUE TITLE
 [Mobile wallet], "Send File Transaction" failed on the Receiver side

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#707]
**Description:**
In the Mobile wallet, "Send File Transaction" failed on the Receiver side with the below error message.

![image](https://user-images.githubusercontent.com/63310656/104038852-9bf38100-51fb-11eb-9798-7615c7d495fc.png)

**Steps to reproduce:**
1.In Mobile wallet,  Initiate Send MWC via File Transaction.
2. On the Receiver Mobile wallet,  select the "Receive MWC by File" option and provide the .tx file.
3.  click "Generate Response" button

**Comment by sarawut11** [comment]
Where did you save the tx file? Did you confirm if it is valid? Did you allow storage access?

**Comment by vinayaga07** [comment]
@sarawut11 
Have stored .tx file on my mobile Downloads folder. While installing the mobile wallet, provided "Allow" to access my Media.

Re-tried and able to reproduce the issue with the latest build.

**Comment by bayk** [comment]
@sarawut11 , I am able to reproduce the issue.  I think the problem is Android OS.  For Latest OS, Android should ask for permissions when this action happens (when we save file) and that doesn't happens. 
On the earlier version of Android permissions was approved when app is installed.
Please try emulator with Android 9 or 10, you should see the same issue.

**Comment by sarawut11** [comment]
![image](https://user-images.githubusercontent.com/35497333/110129641-beb8a500-7dfa-11eb-9e37-49af937f7491.png)
@bayk I guess, it's because you commented the red line code.

**Comment by sarawut11** [comment]
![image](https://user-images.githubusercontent.com/35497333/110146907-b027b900-7e0d-11eb-9b6f-0a5a67256d5b.png)
I guess it's because you commented out the red line code. @bayk

**Comment by vinayaga07** [comment]
Verified with the latest build, still getting the same error message.

**Comment by bayk** [comment]
Just tried and I see the same error. 

@sarawut11 , I think you should use the different directory.  From  here  https://imnotyourson.com/which-storage-directory-should-i-use-for-storing-on-android-6/
There are a list of dirs that should be accessible for all apps:

/sdcard ---> /storage/self/primary
/mnt/sdcard ---> /storage/self/primary
/storage/self/primary ---> **/mnt/user/0/primary**
/mnt/user/0/primary ---> /storage/emulated/0

From the logs I can see you are using '/mnt/user/0/primary'

There some tests on Android 11 device:

> run-as mw.mwc.wallet
> ls /mnt/user/0/primary/
ls: /mnt/user/0/primary/: Permission denied
> ls /mnt/user/0/
ls: /mnt/user/0/: Permission denied
> ls /mnt/user/
ls: /mnt/user/: Permission denied
> ls /storage/emulated/0
Alarms  Android  AudioBooks  DCIM  Documents  Download  Movies  Music  Notifications  Pictures  Playlists  Podcasts  Ringtones  Samsung  Signal  Smart\ AudioBook\ Player\ Backup  Subtitles  log
> ls /storage/self/primary
Alarms  Android  AudioBooks  DCIM  Documents  Download  Movies  Music  Notifications  Pictures  Playlists  Podcasts  Ringtones  Samsung  Signal  Smart\ AudioBook\ Player\ Backup  Subtitles  log

I think we should switch to " /storage/emulated/0"  That directory should exist for prev Android versions as well.

**Comment by vinayaga07** [comment]
Verified with the latest build and getting the same error messages.
Hence re-opening this. ticket.

**Comment by bayk** [comment]
@sarawut11 ,  it failed for me as well.
I see that you are running with params.
--file "/storage/emulated/0/March-23-2021-21-27.tx"

Here are some tests that I run, please check permissions that my phone has.  Seems other apps can create dirs there, but not the wallet. You can read directories and probably write to any on them. "Downloads" looks reasonable. But not all devices might have it. So you probably better to scan dirs and find the best.

beyond0q:/data/user/0/mw.mwc.wallet/files/mwc-qt-wallet/logs $ echo "test" > /storage/emulated/0/March-23-2021-21-27.tx
sh: can't create /storage/emulated/0/March-23-2021-21-27.tx: Operation not permitted
1|beyond0q:/data/user/0/mw.mwc.wallet/files/mwc-qt-wallet/logs $ ls /storage/emulated/0
Alarms  Android  AudioBooks  DCIM  Documents  Download  Movies  Music  Notifications  Pictures  Playlists  Podcasts  Ringtones  Samsung  Signal  Smart\ AudioBook\ Player\ Backup  Subtitles  log
beyond0q:/data/user/0/mw.mwc.wallet/files/mwc-qt-wallet/logs $
beyond0q:/data/user/0/mw.mwc.wallet/files/mwc-qt-wallet/logs $ mkdir  /storage/emulated/0/mwc.wallet
mkdir: '/storage/emulated/0/mwc.wallet': Operation not permitted
1|beyond0q:/data/user/0/mw.mwc.wallet/files/mwc-qt-wallet/logs $ cd   /storage/emulated/0
beyond0q:/storage/emulated/0 $ ls -al
total 192
drwxrwx---  2 root everybody  4096 2020-01-07 08:35 .ColombiaMedia
drwxrwx---  2 root everybody  4096 2021-02-14 20:29 .HhTjqSRo6dybqDAV2ImUSREmnZU=
drwxrwx---  2 root everybody  4096 2021-03-23 21:27 .Samsung\ DeX
drwxrwx---  2 root everybody  4096 2020-09-15 04:50 .eCtcQjbu1dgnvtFnvnr6yepTp1M=
drwxrwx---  4 root everybody  4096 2018-12-31 16:01 .face
drwxrwx---  2 root everybody  4096 2018-12-31 16:01 Alarms
drwxrwx---  5 root everybody  4096 2019-12-26 19:50 Android
drwxrwx--- 27 root everybody 12288 2021-02-11 13:27 AudioBooks
drwxrwx---  5 root everybody  4096 2019-05-18 18:20 DCIM
drwxrwx---  2 root everybody  4096 2019-09-18 22:13 Documents
drwxrwx---  2 root everybody  4096 2021-03-23 21:25 Download
drwxrwx---  3 root everybody  4096 2020-03-13 18:21 Movies
drwxrwx---  3 root everybody  4096 2020-06-22 15:47 Music
drwxrwx---  2 root everybody  4096 2018-12-31 16:01 Notifications
drwxrwx---  5 root everybody  4096 2021-02-04 10:35 Pictures
drwxrwx---  2 root everybody  4096 2019-04-23 19:53 Playlists
drwxrwx---  2 root everybody  4096 2018-12-31 16:01 Podcasts
drwxrwx---  2 root everybody  4096 2018-12-31 16:01 Ringtones
drwxrwx---  3 root everybody  4096 2018-12-31 16:01 Samsung
drwxrwx---  3 root everybody  4096 2020-10-09 14:00 Signal
drwxrwx---  3 root everybody  4096 2019-07-24 05:56 Smart\ AudioBook\ Player\ Backup
drwxrwx---  2 root everybody  4096 2020-01-07 08:35 Subtitles
drwxrwx---  2 root everybody  4096 2019-05-19 00:09 log
beyond0q:/storage/emulated/0/Download $ echo "test" > /storage/emulated/0/Download/March-23-2021-21-27.tx
beyond0q:/storage/emulated/0/Download $
beyond0q:/storage/emulated/0/Download $ cat /storage/emulated/0/Download/March-23-2021-21-27.tx
test

**Comment by Viv-dev-mwc** [comment]
Verified with the latest build and observed Receive MWC via File (from Desktop QT wallet) failed with the below error message.


![image](https://user-images.githubusercontent.com/63310656/114901004-01c25b00-9e32-11eb-99a6-4181551ccdd0.png)

**Comment by bayk** [comment]
Seems like issue on qt wallet c++ side. I will take look.

**Comment by bayk** [comment]
@chaindbkey 
From the log I see:

parseTransaction for  "/storage/emulated/0/Download//com.android.providers.downloads.documents/document/3375"  Body: ""

I think that file is not accessible. I can't get it from adb.  That error is triggered by empty file content.  You probably need something different to open the file.

**Comment by chaindbkey** [comment]
The file should be only imported from download folder for now. In the above example, it is from documents, not download folder.

**Comment by Viv-dev-mwc** [comment]
Verified,hence closing this ticket.
