### ISSUE TITLE
slatepack transaction, failure error message needs correction

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#708]
**Description:**
In slatepack transaction, While trying to finalize the transaction which already got finalized, getting the below error message.

![image](https://user-images.githubusercontent.com/63310656/104202813-66e06c00-5451-11eb-8329-e9b60ba237e3.png)

**Expected Result:**
The error messages should be short and meaningful to the end-user.

**Comment by bayk** [comment]
@vinayaga07 , please copy the errors strings into the ticket. I need to know exact error message to update the mapping. If it will be hard to reproduce, that will be a problem.
You can copy text from the message box.

**Comment by vinayaga07** [comment]
Verified the fix, hence closing this ticket.
