### ISSUE TITLE
Validation of proofs for the http/tor transactions failed

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#709]
**Description:**
Validation of proofs for the http/tor transactions failed with the below error message.

![image](https://user-images.githubusercontent.com/63310656/104212059-cf801680-545a-11eb-889c-11a2dcd2817d.png)

**Comment by bayk** [comment]
Update: this issue is related to compact slate feature. The problem is understandable, but we need to discuss the solution before apply it.

**Comment by bayk** [comment]
Testing: 
Additionally to what was done, please try to verify proofs at the explorers. I will update them in a moment.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
