### ISSUE TITLE
QT wallet Settings, the "Lock Outputs at finalization" option should be enabled by-default

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#710]
**Description:**
In QT wallet Settings, the "Lock Outputs at finalization" option should be enabled by-default, but currently, it is disabled by-default.

![image](https://user-images.githubusercontent.com/63310656/104337607-b12e1f80-551b-11eb-9862-d127a86aa7c2.png)

**Comment by bayk** [comment]
@vinayaga07   I can't reproduce. For me default is correct:

![image](https://user-images.githubusercontent.com/42393608/104354906-c58fff00-54be-11eb-97de-9ddc39e5b012.png)

You should get the same default value if you migrate from old verion of the wallet to this one, or you clean up the settings 
at ~/mwc-qt-wallet/context

**Comment by vinayaga07** [comment]
Closing this ticket, as per the previous comments.
