### ISSUE TITLE
[QT wallet] Http/Tor Send transaction from older wallet version( last released) to the latest version failed.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#714]
**Description:**
Http/Tor Send transaction from older wallet version( last released) to the latest version with "Generate Transaction Proof"  option failed with the error message "Unable to get a wallet proof address for the http://tedlva6wr2xafjuqzut6nt7ojkjm7mnzxyjib6rmsas3um22hi4ryqad".

![image](https://user-images.githubusercontent.com/63310656/104475013-9d9abb80-55e4-11eb-9005-7ddfcbf72d61.png)

**Comment by bayk** [comment]
Nightly will be ready for testing in an hour

**Comment by vinayaga07** [comment]
Tested with the latest build and still hitting the same issue.
Hence re-opening the ticket.

**Comment by bayk** [comment]
@vinayaga07 , I am not able to reproduce. Please check if mwc713 binary comes from the release that you expecting.

You should see something like this.  Please validate that path  /Volumes/mwc-qt-wallet/mwc-qt-wallet.app/Contents/MacOS/  is correct and belong to the version that you are running.

> ps aux | grep mwc713
bay              96515   0.0  0.2  6479836  64544   ??  S    12:28PM   0:08.73 /Volumes/mwc-qt-wallet/mwc-qt-wallet.app/Contents/MacOS/mwc713 --config /Users/bay/mwc-qt-wallet/wallet713v3.toml --disable-history -r <<+)mwc713(+>>

Also please note, proofs works only for the nightly and last release. When you select proof checkbox it shows that.

**Comment by vinayaga07** [comment]
Able to send from the latest wallet to the older wallet, hence closing this ticket.
