### ISSUE TITLE
"Http" Send transaction (without .onion in the wallet address) from the latest wallet version to older wallet version --> Failed

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#719]
**Description:**
"Http" Send transaction (without .onion in the wallet address) from the latest wallet version to older wallet version( last released) with the "Generate Transaction Proof" option enabled failed with the error message "Unable to get a wallet proof address for the http://pezutxljg5doynkfah3fzinzudhej2s56uapbknhtmuwyag6cr7x6kid".

![image](https://user-images.githubusercontent.com/63310656/104944470-4712f000-59dd-11eb-835f-f58d845d249f.png)

**Comment by bayk** [comment]
@vinayaga07 , I am not able to reproduce. It works for me.

**Comment by bayk** [comment]
Fixed, nightly is ready.  The fix is for this nightly only.  The root of the problem is non completed address that was detected as http instead of tor. The fix is detecting such non completed address as tor

**Comment by vinayaga07** [comment]
Verified the fix with the latest build, hence closing this ticket.
