### ISSUE TITLE
QT Wallet, transaction export.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#724]
Tx Export for QT wallet should put 0 to debited and credited values of cancelled and not confirmed transactions.
This data is used to verify the wallet balance and we don't want user to manually clean up the records.

**Comment by bayk** [comment]
Fix in the branch. Keeping open until merge will be done

**Comment by Viv-dev-mwc** [comment]
Verified the fix hence closing this ticket.
