### ISSUE TITLE
Send HTTP error need better explanation.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#730]
That what we get from our users:
Bitforex deposit error in MWC wallet send function. “Your send request has failed: Adapter Callback Error, Checking version: Error: null, Message: null” How to fix?

If should be clear that user need to contact bitforex about that.

**Comment by bayk** [comment]
Fix in the branch. Keeping open until the merge

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
