### ISSUE TITLE
[Mobile wallet] Unable to create a new wallet instance due to screen alignment

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#731]
**Description:**
In Mobile wallet with the latest build, unable to create a new wallet instance due to screen alignment (Next button is not visible).

**Note:**
The mobile device used has a 6.2-inch screen size.

![image](https://user-images.githubusercontent.com/63310656/106637187-6480b600-65a8-11eb-94aa-e8ae314275ac.png)

**Comment by vinayaga07** [comment]
With Feb 7th Build, the "Next" button is partially visible.

![image](https://user-images.githubusercontent.com/63310656/107245724-799c8f80-6a55-11eb-8687-85df0f6836c6.png)

Expecting "Next" button should be fully visible.

**Comment by vinayaga07** [comment]
In 6.2 inch screen, still, Next button is not fully visible which needs a small alignment.

![image](https://user-images.githubusercontent.com/63310656/109325750-50189c00-787c-11eb-80bf-cab4dbd837c5.png)

**Comment by bayk** [comment]
@sarawut11 ,  for such devices you can 4 words per line, not 6.  That should help.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
