### ISSUE TITLE
Slatepack input Dialogs, error reporting

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#733]
Slatepack input dialog parsing message goes into notification. There can be too many messages because parsing happens on every update. 
We need to suppress those error messages from going into notification.

**Comment by bayk** [comment]
High priority because it is easy to fix.

**Comment by bayk** [comment]
Fix in the branch. Will update ticket status after the merge

**Comment by Viv-dev-mwc** [comment]
Verified, hence closing this ticket.
