### ISSUE TITLE
Swap, transaction fees. Add min/max limits

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#734]
Currently we have min limit, but not max. As a result user can input too large value. We should warn the user

**Comment by bayk** [comment]
Fixed but code in the branch. Keeping open until the merge.

**Comment by Viv-dev-mwc** [comment]
Verified the fix, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/117176224-45830180-aded-11eb-9728-c41e3226e571.png)
