### ISSUE TITLE
[Mobile-wallet] Description box should allow users to enter multiple line of inputs

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#739]
**Description:**
In the Mobile wallet, while sending the amount using an address, in the description box unable to enter more than 1 line of input.

**Expected Result:**
The description box should allow users to enter multiple lines of inputs.

Please refer to the below screenshots for more details.

![image](https://user-images.githubusercontent.com/63310656/107245363-127edb00-6a55-11eb-8361-7e6002242ac1.png)

![image](https://user-images.githubusercontent.com/63310656/107245381-190d5280-6a55-11eb-9ffb-efeb5b4e2a0d.png)

**Comment by bayk** [comment]
@sarawut11 , please delete new line symbols before submit the input to the wallet.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
