### ISSUE TITLE
 [Mobile wallet] while Sending MWC via SLATEPACK feature on FINALIZING the transaction box, if we keep pressing the delete button wallet is getting logged out.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#748]
**DESCRIPTION:**
In Mobile wallet, while Sending MWC via SLATEPACK feature on FINALIZING the transaction box, if we keep pressing the delete button wallet is getting logged out.

![image](https://user-images.githubusercontent.com/63310656/107393649-09f3d680-6b21-11eb-95f0-cc06a8edeb6b.png)

**Steps to reproduce:**

1. Log in to Mobile wallet.
2. Initiate Send MWC via SLATEPACK.
3. Copy the Slatepack message and send it to the recipient.
4. Get the Slatepack response message from the receiver and paste it on the FINALIZING the transaction box.
5. Press the "Delete" button on the mobile for few times.
6.  Observed Mobile wallet is getting logged out.

**Comment by sarawut11** [comment]
This seems like mwc713 issue @bayk 
I could reproduce the same issue in desktop wallet.
![image](https://user-images.githubusercontent.com/35497333/108528710-489a4580-7306-11eb-8207-b7235ccf2d16.png)

**Comment by bayk** [comment]
By deleting characters form the slatepack mwc713 was crashed with error

thread 'main' panicked at 'range start index 1618 out of range for slice of length 1617', /home/vsts/.cargo/git/checkouts/mwc-wallet-9ca0cd1867b6d24c/0ee707d/libwallet/src/slatepack/armor.rs:74:28

**Comment by vinayaga07** [comment]
Verified the fix on the mobile wallet, hence closing this ticket.
