### ISSUE TITLE
[Mobile wallet] Build to build upgrade fails

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#750]
**Description:**
In Mobile wallet, unable to upgrade from build to build.  In order to install the new version, we need to uninstall the old one and do fresh install. The data will be lost.

Verified on the latest nightly build dated Feb 10th and observed the same issue.

**Comment by bayk** [comment]
@vinayaga07 , the next time when you update, you should be fine.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
