### ISSUE TITLE
 [Mobile wallet] Unable to find the currently installed build version. 

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#751]
**Description:**
In Mobile wallet unable to find the currently installed build version. 

**Expected Result:**
The mobile wallet should have the option to display the currently installed build version details.

**Comment by bayk** [comment]
@sarawut11 , what do you think about that? 
I am thinking about the login and first time login screens. We probably can show version there.

**Comment by sarawut11** [comment]
yes, I think, it's good to show it under the logo in the login screen

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
