### ISSUE TITLE
[Mobile wallet] By-default TOR service status is STOPPED on a new mobile wallet

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#752]
**Description:**
On a newly installed Mobile wallet, by-default TOR service status is STOPPED. Expecting both MWCMQS & TOR services should be in a running state by-default. (Currently, MWCMQS service alone is in running state on a new mobile wallet).

![image](https://user-images.githubusercontent.com/63310656/107541768-7c31ed00-6bed-11eb-9ead-255d304ea9cd.png)

@bayk Please confirm my expecting is valid?

**Comment by bayk** [comment]
Yes, I think by default TOR should be on, similar to Desktop.

**Comment by sarawut11** [comment]
can you guys @bayk @vinayaga07 check on a new phone? On my side, it is on by default.

**Comment by vinayaga07** [comment]
Thanks, @bayk for the confirmations.

@sarawut11 , To reproduce the issue, please do uninstall the existing build and re-install a new build.

**Comment by sarawut11** [comment]
yes, I did it but couldn't reproduce the issue. can you try once again?

**Comment by vinayaga07** [comment]
Re-tried and able to reproduce the issue with Today's nightly build too...

![image](https://user-images.githubusercontent.com/63310656/108525463-1a146e80-72f6-11eb-84e7-a821d4985bee.png)

**Comment by bayk** [comment]
@vinayaga07 ,  the tor autostart is a setting. It should work similar to desktop wallet. I will check if it works and update the ticket if the are issues.

**Comment by bayk** [comment]
@vinayaga07 .  Just tested, it works fine for me. There is wallet setting that specify autostart for TOR and it works as expected.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
