### ISSUE TITLE
Monospaced Font for Slatepack String

### ISSUE THREAD

**Issue by suemto** [mwcproject/mwc-qt-wallet#753]
Perhaps we can have a pretty display for Slatepack if using monospaced font. See the examples below.

![f2](https://user-images.githubusercontent.com/72774430/107592294-86131a80-6c04-11eb-8332-4877c47051e5.png)

Example with monospaced font:

![f1](https://user-images.githubusercontent.com/72774430/107592320-95926380-6c04-11eb-8e30-bf8ba1a3bb4d.png)

**Comment by bayk** [comment]
Yes, make sense, should be easy to fix

**Comment by bayk** [comment]
Here is how it will looks like. The mono font is very different from rest of UI, but I think it is fine.  Slatepack content looks much better

![image](https://user-images.githubusercontent.com/42393608/108446298-bfeead00-7212-11eb-8460-332cfd7321eb.png)

**Comment by bayk** [comment]
Testing:
Please check under all all platforms if slatepack looks fine.  Please go though all workflow (send, receive, finalize). Self  sending is fine.  There are is a chance that some UI elements need to be resized. I tested on macOs only

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
