### ISSUE TITLE
[mobile wallet] "Send File Transaction" failed while sending the MWC amoun

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#754]
**Description:**
In the mobile wallet, "Send File Transaction" failed while sending the MWC amount with the below error message.

![image](https://user-images.githubusercontent.com/63310656/107663084-fb3c2980-6cb0-11eb-8059-154588f572b8.png)

**Comment by sarawut11** [comment]
Did you allow storage access when the app is opened? when the app is opened, it requires to click "allow", "deny" to access phone storage. If you clicked "deny", then above error will happen since it can't write the tx file.

**Comment by vinayaga07** [comment]
Retried with the Today's nightly build and selected the "allow" option to access the phone Media ... but still getting the same error.

**Comment by vinayaga07** [comment]
Re-tried with the latest build and able to reproduce the issue.

**Comment by bayk** [comment]
@sarawut11 , please check my comment at https://github.com/mwcproject/mwc-qt-wallet/issues/707
I am getting the same errors as Vinayaga.

**Comment by sarawut11** [comment]
https://github.com/mwcproject/mwc-qt-wallet/issues/707#issuecomment-791545062

**Comment by vinayaga07** [comment]
Verified with the latest build and getting the same error message.
Hence re-opening this ticket.

**Comment by bayk** [comment]
@sarawut11 , please see the comment    https://github.com/mwcproject/mwc-qt-wallet/issues/707#issuecomment-792903527

**Comment by vinayaga07** [comment]
Verified with the latest build and getting the same error message.
Hence re-opening this ticket.

**Comment by Viv-dev-mwc** [comment]
Verified with the latest build and getting the below error message.
Hence re-opening this ticket.

![image](https://user-images.githubusercontent.com/63310656/113594059-ca46f800-9654-11eb-9314-a1f470ddf219.png)

**Comment by bayk** [comment]
@sarawut11 ,  I am getting the same error

**Comment by Viv-dev-mwc** [comment]
Verified with Today's build and still observing the same error message. 
Hence re-opening this ticket.

**Comment by Viv-dev-mwc** [comment]
Verified, hence closing this ticket.
