### ISSUE TITLE
Unable to do a fresh install Today's (Feb 12) Nightly build on the Andriod Mobile. 

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#755]
**Description:**
Unable to do a fresh install Today's (Feb 12) Nightly build on the Andriod Mobile. 
Getting the below error message.

![image](https://user-images.githubusercontent.com/63310656/107792975-c8129c80-6d7b-11eb-8741-14f5f731dc4b.png)

**Comment by bayk** [comment]
Seems like it is upload issue. The build is restarted.

**Comment by bayk** [comment]
Nightly is updated with valid apk package

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
