### ISSUE TITLE
After login to the Mobile Wallet, a  default landing page is "Wallet Settings-->Listeners" instead it should be "Wallet-->Home" page.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#757]
**Description:**
After login to the Mobile Wallet, a  default landing page is "Wallet Settings-->Listeners" instead it should be "Wallet-->Home" page.

**Actual Result:**
![image](https://user-images.githubusercontent.com/63310656/107965974-3ac88580-6fd1-11eb-920a-a2e08c7849c0.png)

**Expected Landing page:**
![image](https://user-images.githubusercontent.com/63310656/107966005-461bb100-6fd1-11eb-9d51-c466fb228584.png)

**Steps to reproduce:**
1. log in to the mobile wallet.
2. Verify the landing page as "Wallet Settings-->Listeners".
3. Do some operations on the mobile wallet.
4. Logout from the wallet
5. Close /Kill the background running the MWC process on the mobile.
6. log in to the mobile wallet.
7. Verify the landing page as "Wallet Settings-->Listeners".

**Comment by bayk** [comment]
I will take it. For Desktop we are restoring the last open page. For Mobile it should be different behaviour.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
