### ISSUE TITLE
QT wallet - grammar, typos, UI stuff

### ISSUE THREAD

**Issue by mkd888** [mwcproject/mwc-qt-wallet#759]
1.
![not centered](https://user-images.githubusercontent.com/79090099/108497325-92a20d80-72ab-11eb-9f41-dbac96fe3efb.png)

"SELECTED" needs to be shifted a little to the left

2.
![question mark swaps](https://user-images.githubusercontent.com/79090099/108497535-ddbc2080-72ab-11eb-8035-9047583d4459.png)

Fix to "supported"
Make the link clickable
Fix to "Any questions?"
*if you click anywhere in the text, this text cursor thing appears - I would change it so the text is not "clickable"

3.

![swap trades grammar](https://user-images.githubusercontent.com/79090099/108501889-3b536b80-72b2-11eb-8bfe-9f7731ac0c91.png)

I suggest to fix these and change to:
1. of **a** hardware
2. might **lose**
3. might **lose**
4. on **a** separate drive like **a** USB stick
5. locking or **refunding**
6. before **a** redeem 
7. to finish **the** redeem or **make** a refund
8. refund **your**
9. finish **redeeming a** transaction
10. **which** is optional
11. Please note **that** **(no ",")**
12. **Pause the trade before the lock step, until the trade data is backed up.**

However, consult this with a native speaker just to make sure it's 100% correct.

**Comment by bayk** [comment]
1  - fixed.
2 - 'Make the link clickable'  unable to fix, Qt doesn't support that.
     '*if you click anywhere in the text, this text cursor thing appears - I would change it so the text is not "clickable"'   - unable to fix,  we want users to be able to copy any text. Cursor is needed for that.
3  - fixed

**Comment by mkd888** [comment]
Verified. Good job, I'm closing this issue.
