### ISSUE TITLE
Transaction page, in each transaction "http address" is not getting displayed 

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#760]
**Description:**
In Mobile Wallet--> Transaction page, in each transaction "http address" is not getting displayed instead it is displaying only "http". Please refer screenshot for more details.

**Note:**

- MWCMQS address is getting displayed fully (as expected ).

![image](https://user-images.githubusercontent.com/63310656/108526750-8479de80-72f7-11eb-8feb-ee063dabe7cc.png)

**Comment by bayk** [comment]
It is expected.  For HTTP we don't know the income address. Desktop does the same.

We don't expect the mobile users use http, that will be very hard to configure. But in the latest version with slatepack the address can be retrieved we probably can make better.

**Comment by bayk** [comment]
Testing: 
Use new wallets to send the coins (release wallet is fine). You should see sender tor address for the transactions.
New and old wallet will keep "http" as a sender, here is nothing what we can do.

Also, the same is applicable to desktop wallet.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
