### ISSUE TITLE
Mobile Wallet-->Transcation page, few buttons are missing.

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#761]
**Description:**
In Mobile Wallet-->Transcation page, the following features/buttons are missing.

1.  Validate Proof File.
2. Export .CSV file.
3. Refresh

Expecting these options same like QT-wallet.

![image](https://user-images.githubusercontent.com/63310656/108527582-74aeca00-72f8-11eb-8eaf-c6be0e2db2c2.png)

**Comment by bayk** [comment]
Validate Proof File.  &  Export .CSV file.   we can move to the next release.

Refresh  is done automatically every 30 seconds, this button is nice to have, but it is not very critical. UI looks better as it is.

@vinayaga07 , please verify that refresh is automated and transaction confirmation status will be updated eventually.

**Comment by chaindbkey** [comment]
duplicated with other issues.
