### ISSUE TITLE
Mobile Wallet, creating new instance

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#765]
Creating new wallet, Unable to see the seed.
@vinayaga07 , Update:   Seems it is a blocker. That workaround bug probably was fixed

![image](https://user-images.githubusercontent.com/42393608/108558939-7d2ee280-72af-11eb-9b49-ef45c2494e1d.png)

02-19 12:37:52.094  6956  6980 D mwc-qt-wallet: Processing task ' "TaskInit" '
02-19 12:37:52.094  6956  6980 D mwc-qt-wallet: TaskInit::processTask:  "Evt(T=S_WELCOME, msg=4.1.0), Evt(T=S_LINE, msg=Welcome to wallet713 for MWC v4.1.0), Evt(T=S_LINE, msg=Initialising a new wallet), Evt(T=S_LINE, msg=Set an optional password to secure your wallet with. Leave blank for no password.), Evt(T=S_LINE, msg=Your recovery phrase is:), Evt(T=S_LINE, msg=reject steel elev...... e dish border camp), Evt(T=S_LINE, msg=Please back-up these words in a non-digital format.), Evt(T=S_INIT_WANT_ENTER, msg=)"
02-19 12:37:52.094  6956  6980 D mwc-qt-wallet: Get a passphrase, it has words:  24
02-19 12:37:52.096  6956  6980 W mwc-qt-wallet: qrc:/windows_mobile/NewSeed.qml:9: Error: Invalid write to global property "seedText"

The issue happens because of that:
    mwc-qt-wallet: qrc:/windows_mobile/NewSeed.qml:9: Error: Invalid write to global property "seedText"

**Comment by vinayaga07** [comment]
With Today's build, able to reproduce this issue.
