### ISSUE TITLE
Mobile wallet Dialog pages, Close icon (X button) needs to be removed

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#768]
**Description:**
In the mobile wallet-->Outpiut page, Dialog pages have both the "OK" button and also Close icon (X button).
Please refer to the below screenshot.

**Expected Result:**
In Mobile wallet Dialog pages, Close icon (X button) needs to be removed which looks awkward.

![image](https://user-images.githubusercontent.com/63310656/108737121-47f8ed80-7558-11eb-8165-779ffb84c14c.png)

**Comment by sarawut11** [comment]
The close icon is needed definitely. In small device screen, there is a scroll and users can't see ok button. In this case, close button is useful. If not, they always need to scroll down and click ok to close the dialog, which is not user friendly.
@bayk @vinayaga07
