### ISSUE TITLE
Mobile Wallet. Android system back button should return back to the prev page.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#769]
Currently back button closing the app. Instead it should return back to the prev page

Here are how to get the event. 
https://forum.qt.io/topic/28801/android-backbutton

Also QT wallet will need to maintain the stack of called windows / states.  That need to be done as well.

**Comment by bayk** [comment]
@sarawut11   please reviews the changes  https://github.com/mwcproject/mwc-qt-wallet/commit/10c371b50b21cc393e8429ae70ac7c1fb21c33b9

I can't do that in C++ because there is no QWidget main window.

**Comment by vinayaga07** [comment]
Closing this ticket.
