### ISSUE TITLE
Mobile Wallet. Creating new. Seed confirmation.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#770]
For mobile wallet it is really hard to conform all 24 mnemonic words.
Let's use random 6 words that user need to input. The purpose of that is to make sure that user write those words.

In case of mistake, user will be asked for not the same, but random word.

@sarawut11   @vinayaga07    - FYI.  I think that will help with UX.

**Comment by sarawut11** [comment]
It sounds good @bayk 
I guess, it should be handled in mwc-wallet side, not on the wallet side, right?

**Comment by bayk** [comment]
@sarawut11   Yes, I am expecting to fix on mwc-wallet side. That is why I assigned it to myself.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
