### ISSUE TITLE
Mobile wallet, Recovering an account using passphrase failed.

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#771]
**Description:**
In Mobile wallet, Recovering an account using passphrase failed.

![image](https://user-images.githubusercontent.com/63310656/108744994-98744900-7560-11eb-8f2d-da42ac6c5547.png)

**Comment by bayk** [comment]
@vinayaga07 , how does it fail?

**Comment by sarawut11** [comment]
sometimes it shows network connection issue. In this case, need to restart recover.
Otherwise, it works well. just confirmed again.
@vinayaga07 https://github.com/mwcproject/mwc-qt-wallet/issues/771#issuecomment-791182048

**Comment by vinayaga07** [comment]
Re-tried and able to reproduce the issue.

![Uploading image.png…]()

**Comment by sarawut11** [comment]
@vinayaga07 https://github.com/mwcproject/mwc-qt-wallet/issues/771#issuecomment-791260317

**Comment by sarawut11** [comment]
Maybe we need to increase the time limit @bayk

**Comment by bayk** [comment]
Yes, I will increase connection timeout.  I think for mobile devices it make sense to have it larger.

**Comment by vinayaga07** [comment]
Verified with the latest build and still observed the same issue.

![image](https://user-images.githubusercontent.com/63310656/110360221-74d2f780-8064-11eb-9afb-c759bcc4885a.png)

**Comment by yyangli** [comment]
Code is ready. Need to deploy another node and update the config file:
mwc_node_uri = \"https://mwc713.floonet.mwc.mw;{second node}\"
The two node addresses are separated by semicolon.

**Comment by Viv-dev-mwc** [comment]
Verified, hence closing this ticket.
