### ISSUE TITLE
Mobile wallet, after transferring the MWC recipient, Notification message needs correction

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#774]
**Description:**
In the Mobile wallet, after transferring the MWC recipient, the below Notification message is getting displayed which needs correction.

![image](https://user-images.githubusercontent.com/63310656/108873869-94f4c680-7621-11eb-998f-4def5ab6b29c.png)

**Expected Result:**
![image](https://user-images.githubusercontent.com/63310656/108873930-a8a02d00-7621-11eb-8627-0809fa34f425.png)

**Comment by sarawut11** [comment]
@vinayaga07  Please check again, I couldn't reproduce the issue

**Comment by vinayaga07** [comment]
Resolved with the latest build, hence closing this ticket.
