### ISSUE TITLE
Mobile wallet, Send/Receive MWC transactions via HTTPs address failed with the below error message.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#778]
**Description:**
In the Mobile wallet, Send/Receive MWC transactions via HTTPs address failed with the below error message.

![image](https://user-images.githubusercontent.com/63310656/109032871-157ff980-76ec-11eb-861c-992153aa7574.png)

**Comment by sarawut11** [comment]
@bayk can you please check this issue?

**Comment by bayk** [comment]
Yes, it is wallet core issue. Will check

**Comment by bayk** [comment]
@vinayaga07 , I just try to use tor and it works for me

![image](https://user-images.githubusercontent.com/42393608/109372263-7d098680-785d-11eb-916d-afe9c5726adf.png)

Please specify more details.
Also, if that was a glitch - it is fine.

**Comment by vinayaga07** [comment]
Re-verified, hence closing this ticket.

**Comment by vinayaga07** [comment]
@bayk Please try to send MWC via TOR address.

**Comment by bayk** [comment]
@vinayaga07 ,  I see the problem. For TOR address you can't use https, it must be http.  Your screenshot shows https and it is incorrect. Please check if http was a problem.
 
About https and onion error message I created a ticket  https://github.com/mwcproject/mwc-qt-wallet/issues/790

**Comment by vinayaga07** [comment]
Tried with the TOR address (http://<address.onion>) and it is failing for me.

**Comment by bayk** [comment]
I will check on real device. It it works - I will ask Jim to try as well.

**Comment by bayk** [comment]
@vinayaga07 , just try to send by  http://<tor_address>.onion and it works.
I guess you might have TOR connection issue or there are other potential problems that I created different tickets.
Let's keep this open until I fix others.
Also please note. Tor connection might be unstable. It doesn't show when it is reconnecting. But most of the time it should work fine.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
