### ISSUE TITLE
Android mobile wallet, unable to create a new wallet instance.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#779]
**Description:**
In the Android mobile wallet, unable to create a new wallet instance. In the first Phasehrase input providing screen, it is expecting word#6 instead of word#1. 

Please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/109174211-a4ebe200-77aa-11eb-811e-836670b19c3b.png)

**Note:**

- Nightly Build used 02-25-2021.

**Comment by bayk** [comment]
@vinayaga07 , it is a feature. There is a ticket about that. Mobile wallet will ask 6 random words instead of 24.
If you provide word 6 - that should accept it.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
