### ISSUE TITLE
Mobile wallet Login screen, UI corrections.

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#781]
**Description:**
In the Mobile wallet Login screen, the following corrections are needed.

1. "Open wallet" button width needs to be reduced.
2.  "Restore" & "New Instance" buttons need to be moved up (Currently it is at the bottom of the screen instead it should be below the "Open wallet" button). 

Please refer to the below screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/109176695-13ca3a80-77ad-11eb-89e6-77228758e65a.png)

**Comment by vinayaga07** [comment]
"Open wallet" button width not yet reduced. Hence re-opening this ticket.

**Comment by Viv-dev-mwc** [comment]
Verified, hence closing this ticket.
