### ISSUE TITLE
Mobile wallet, the Instance name is not getting fully displayed.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#786]
**Description:**
In the mobile wallet, the Instance name is not getting fully displayed.
In my 6.2 inches mobile screen, the Instance name is getting displayed as "T" instead of the full name "TEST1". 
Please refer to the below screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/109527609-db429d80-7ad9-11eb-9462-7138ce70eaa4.png)

**Comment by sarawut11** [comment]
Check again, it works well, confirmed again @vinayaga07

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
