### ISSUE TITLE
On the mobile wallet Transaction page, currently don't have the option to cancel the transactions. 

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#787]
**Description:**
On the mobile wallet Transaction page, currently don't have the option to cancel the transactions. 

Expecting Cancel transaction option in mobile wallet same as QT wallet.

![image](https://user-images.githubusercontent.com/63310656/109528338-94a17300-7ada-11eb-92f9-05697268c686.png)

**Comment by sarawut11** [comment]
duplication issue with https://github.com/mwcproject/mwc-qt-wallet/issues/794
