### ISSUE TITLE
On the mobile wallet Transaction page, currently don't have the options - Validate Proof File, Refresh, Export.

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#788]
**Description:**
On the mobile wallet Transaction page, currently don't have the following options 

1. Validate Proof File
2. Export.CSV
3. Refresh

Expecting options in mobile wallet same as QT wallet.

![image](https://user-images.githubusercontent.com/63310656/109528832-198c8c80-7adb-11eb-8524-e8c6b0a781e7.png)

**Comment by bayk** [comment]
@sarawut11   @vinayaga07    Export to CSV is not needed for the first version of mobile.

**Comment by sarawut11** [comment]
Moved export feature into another issue - https://github.com/mwcproject/mwc-qt-wallet/issues/833

**Comment by Viv-dev-mwc** [comment]
Verified, hence closing this ticket.
