### ISSUE TITLE
Mobile wallet, unable to login to first instance

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#789]
**Description:**
In the mobile wallet which is having two wallet instances (Test1 &  Test2); by-default login is going to the second wallet instance(Test2) and unable to login to the first wallet instance (Test1)

**Comment by bayk** [comment]
@sarawut11 , looks like 'Change Instance' is not propagated. From the logs I can see that mwc713 config always point to the latest data directory

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
