### ISSUE TITLE
In the Mobile Wallet Setting config page, the default instance name is getting displayed instead of the actual wallet name 

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#791]
**Description:**
In the Mobile Wallet Setting config page, the default instance name (GUI_WALLET713_DATA2) is getting displayed instead of the actual user-provided wallet name ("Test1")

![image](https://user-images.githubusercontent.com/63310656/109835049-db24d800-7c68-11eb-8ac0-ab8373bdc228.png)

**Note:**
Observed this issue with the mobile wallet having a single instance.

**Comment by sarawut11** [comment]
check again now, it works well @vinayaga07

**Comment by vinayaga07** [comment]
Observed this issue with the mobile wallet having a single instance. 
If the mobile wallet has more than one instance, then this issue doesn't exist.

**Comment by bayk** [comment]
@vinayaga07 , probably it is my problem. You might not end wallet nicely, so it lost the name. I will check if it saved on exit.

**Comment by bayk** [comment]
@vinayaga07 , it should work well. I just try latest build with a single instance wallet and it works. Please uninstall the prev version first so it will delete the data.  The instance name written is reliable way, it can't be lost.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
