### ISSUE TITLE
Mobile Wallet.  Cancel transaction. Resubmit transaction. Generate Proof

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#794]
There are transactions functionality that need to be addressed:
- Cancel, resubmit, generate proof.

At Desktop wallet there are buttons at transaction page. But for mobile we might come with different UI. For example  Transaction detail dialog can be updated with those optional buttons.  We need to show button when action is allowed.

**Comment by Viv-dev-mwc** [comment]
@chaindbkey In Mobile wallet, unable to find Re-submit option.

**Comment by bayk** [comment]
That might be buttons location issue. I saw that sometimes buttons are overlapped. Please  note, you can have resubmit and proof at the same time.

**Comment by chaindbkey** [comment]
ok will fix the duplication issue. Anyway, the button name is Repost(not Resubmit) like desktop wallet. @Viv-dev-mwc

**Comment by Viv-dev-mwc** [comment]
Verified, hence closing this ticket.
