### ISSUE TITLE
Mobile wallet - you can click through windows; help window issues

### ISSUE THREAD

**Issue by mkd888** [mwcproject/mwc-qt-wallet#796]
You can click through these windows: 

1. If a user misclicks "Confirm", they can open the "logout/ change wallet"option (which is hiding behind the "wallet password" window) by accident
![Screenshot_20210302-222759](https://user-images.githubusercontent.com/79090099/110013007-66fa3b00-7d21-11eb-8add-70e0bad754b2.jpg)
2. Opening two windows at once ("show passphrase" + help page "?") is possible and neither of the windows is then shown properly.

![Screenshot_20210302-222807](https://user-images.githubusercontent.com/79090099/110013013-68c3fe80-7d21-11eb-88a7-8047e0322d17.jpg)

3. Opening both help window and sidebar menu is possible and it results in this. 
![Screenshot_20210302-223556](https://user-images.githubusercontent.com/79090099/110013015-695c9500-7d21-11eb-8157-160b586af9d9.jpg)

In general, I suggest locking the background while one of these windows are open, that  would prevent these issues from happening.

**Comment by bayk** [comment]
The root problem that popups are not modal.
@sarawut11 ,  QML  has modality,  https://doc.qt.io/qt-5/qml-qtquick-controls2-popup.html
Also there are dialogs, but they might look differently, not how you are expecting.

**Comment by mkd888** [comment]
Verified, works fine now. Good job, I'm closing this issue.
