### ISSUE TITLE
Mobile wallet - Return button doesn't work properly

### ISSUE THREAD

**Issue by mkd888** [mwcproject/mwc-qt-wallet#797]
![Screenshot_20210303-202630](https://user-images.githubusercontent.com/79090099/110010764-f2260180-7d1e-11eb-8ed1-6783c68bce8c.jpg)

Return button (**<**) doesn't work properly. At step 3 first click doesn't do anything, second click returns me to step 1 (main menu). I only observed this issue here, not in any other situation.

**Comment by bayk** [comment]
@vinayaga07 ,  back button is not perfect. It will return you back to the original state. For Send that will be a problem, you are expecting to be back from send page 2 to send page 1. 
I will try to figure out how to fix that.

**Comment by bayk** [comment]
Testing:  Currently fair back functionality is implemented.  It should behave right now. Please note, back is disabled during wallet sync.

**Comment by mkd888** [comment]
Verified, works fine now. Good job, I'm closing this issue.
