### ISSUE TITLE
Mobile Wallet. Online Send

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#799]
Online Send operation might take time, up to 2 minutes especially if there are connection issues.
We need to:
1.  show the progress is possible
2. Disable Send button until we get send confirmation.

Currently user can press send button several times and make several transactions instead of one.

**Comment by bayk** [comment]
@vinayaga07 ,  FYI, it is critical issue.  I will disable send while we are in the progress in Desktop app as well. In desktop it is less critical because progress exist.

**Comment by bayk** [comment]
@sarawut11 , assigning to you. The desktop part is done.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
