### ISSUE TITLE
Wallet configuration->Send mwc parameters

### ISSUE THREAD

**Issue by MWCmax** [mwcproject/mwc-qt-wallet#8]
In Wallet Configuration, Send mwc parameters: What is Restore original supposed to do?
It’s only clickable once you start typing new parameters, and if you click it it takes you to the latest setting you just had, not to the original 20 confs 1 output.
That is, if you change it more than once, Restore original takes you back to the previous one, not to the original defaults
IMO it should take you back to original, since users may change it and then doubt wether thay may have made a mistake, so it’s best to go back to default.

**Comment by bayk** [comment]
Yes, currently it is a rollback to latest accepted settings.
Will hardcode the defaults ones.

**Comment by bayk** [comment]
Fixed
