### ISSUE TITLE
Mobile Wallet. Sync Page stay on top

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#801]
When Sync is finished and previous page is switched,  sync page is still visible. 
Also you can validate the same by going into the menu and select any other page (try only when when sync is done). 
Then you can try to press Android Back button.
The title at the top will show correct page name, but the only Sync page will be visible.

**Comment by bayk** [comment]
@vinayaga07 , please note, the sync page should disappear when sync is done. Currently after sync user will need to restart the wallet. It is not what we need.

**Comment by vinayaga07** [comment]
Verified with the latest build and observed sync page is not getting disappeared after sync gets completed.
Hence re-opening this ticket.

**Comment by Viv-dev-mwc** [comment]
Verified, hence closing this ticket.
