### ISSUE TITLE
Mobile Wallet.  Messages about the wallet start/stop process.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#802]
There are some UI items that are not implemented at MobileWndManager. They related to mwc713 wallet heath reporting.
We need them for release. Even they are not critical for users, they are critical for support. 

At the  mwc-qt-wallet/core_mobile/MobileWndManager.cpp   need to implement
void MobileWndManager::showWalletStoppingMessage(int taskTimeout)
void MobileWndManager::hideWalletStoppingMessage()

**Comment by vinayaga07** [comment]
Closing this ticket.
