### ISSUE TITLE
Mobile wallet  "Re-sync with full node" page, the Progress bar displaying values in fractional units. 

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#805]
**Description:**
In the mobile wallet  "Re-sync with full node" page, the Progress bar displaying values in fractional units. 
Fractional values need to be removed.

![image](https://user-images.githubusercontent.com/63310656/110495964-09982c80-811b-11eb-92fd-0fb9ab374c8b.png)

**Comment by bayk** [comment]
@vinayaga07 ,  why do you think fraction are not needed?  For the floonet sync takes time and at least you can see that it is not stale and the numbers are changing.

**Comment by bayk** [comment]
ok, let's fix that. Also desktop qt wallet has the same issue.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
