### ISSUE TITLE
Mobile wallet, Re-sync with Full Node failed

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#806]
**Description:**
In the mobile wallet, Re-sync with Full Node failed with the below error message

![image](https://user-images.githubusercontent.com/63310656/110511152-f3459d00-8129-11eb-93ea-d0d951272605.png)

**Comment by bayk** [comment]
@vinayaga07   @sarawut11 ,  I think we need to have failover servers for the mwc-nodes. Currently we have only instance in Montreal and seems like it doesn't work well for you.
We will do that that later.

**Comment by yyangli** [comment]
Code is ready. Need to deploy another node @bayk and update the config file:
mwc_node_uri = "https://mwc713.floonet.mwc.mw;{second node}"
The two node addresses are separated by semicolon.

**Comment by bayk** [comment]
@yyangli , can we have N nodes with the same secret?  Please share the changes. 
I will add more domains for the nodes for mainnet.  Let's have total 6 node at locations: USA, Canada, France, Korea, India and Australia.
Australia zone needs to be deployed. Other 5 we already have.

For floonet that will be Canada, India, France and Australia - total 4.  # are exist, the Australia will be deployed

**Comment by yyangli** [comment]
Yes, we can have multiple. All the nodes need to separated by semicolon.
node1;node2;node3...

**Comment by bayk** [comment]
@yyangli , here are the domains:
Mainnet:  mwc713.mwc.mw    mwc71362.mwc.mw    mwc7133.mwc.mw   mwc7134.mwc.mw    mwc7135.mwc.mw  mwc7136.mwc.mw

Floonet:   mwc713.floonet.mwc.mw    mwc7132.floonet.mwc.mw    mwc7133.floonet.mwc.mw  mwc7134.floonet.mwc.mw

All domains are https, default  port is fine. Node URL can look like this   https://mwc7134.floonet.mwc.mw

Please update default config template and default values with them. 
You can test if wallet switching by disabling  some of domains at /etc/hosts  

Please let me know when you are done with that. I will update qt wallet  with some migration

**Comment by bayk** [comment]
Let's keep this ticket 'in progress'.   Issue is not resolved yet.

**Comment by Viv-dev-mwc** [comment]
In the mobile wallet, Re-sync with Full Node failed with the below error message.
Hence re-opening this ticket.

![image](https://user-images.githubusercontent.com/63310656/115047854-8d9dbb00-9ef6-11eb-9b2c-5fe4adfcfe09.png)

**Comment by bayk** [comment]
Let me build the mobile and check. There was some changes that break the build.

**Comment by bayk** [comment]
@Viv-dev-mwc  please check the nightly. I don't see the issues, it works for me. 

Also please check if resync with node works. I think I have some UI issues.

**Comment by Viv-dev-mwc** [comment]
I'm able to re-produce the issue.

**Comment by bayk** [comment]
@Viv-dev-mwc , please check the discord.  We need to run multiple tests.

**Comment by Viv-dev-mwc** [comment]
Tried with Wifi+Mainnet....Re-sync with Full Node happened successfully. Hence closing this ticket.
