### ISSUE TITLE
Mobile wallet - grammar&typos

### ISSUE THREAD

**Issue by mkd888** [mwcproject/mwc-qt-wallet#808]
A few grammar errors&typos I found in the mobile wallet:

1. Syncronizing -> Sync**h**ronizing
![grammar1](https://user-images.githubusercontent.com/79090099/110939055-185a2b80-8335-11eb-85a7-dbf3cf8a5877.jpg)

2. this -> the
![gr2](https://user-images.githubusercontent.com/79090099/110938930-ea74e700-8334-11eb-8c0d-aa5b6a549f2c.jpg)

3. It says "input your password to continue" twice
![gr3](https://user-images.githubusercontent.com/79090099/110939845-50ae3980-8336-11eb-9d60-27814f725268.jpg)

4. "Are you sure **you** want to log out?
![gr4](https://user-images.githubusercontent.com/79090099/110939269-70912d80-8335-11eb-9dc7-624b8d8a4723.jpg)

**Comment by bayk** [comment]
@sarawut11 , I will check it.

**Comment by bayk** [comment]
Everything should be fixed. Most of types was affected Desktop and Mobile.  Testing in mobile only is ok.

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
