### ISSUE TITLE
Mobile wallet - landscape mode

### ISSUE THREAD

**Issue by vek-kal** [mwcproject/mwc-qt-wallet#809]
On the mobile wallet, when turning the phone on landscape mode, we see that scrolling is impossible and then we cannot have all functionality on the wallet as the button that allow us to get on the next page

Normal mode : 
![Screenshot_2021-03-02-17-36-22-358_mw mwc wallet](https://user-images.githubusercontent.com/80525364/110941340-1a6dbb80-8330-11eb-92c7-0df7ed4eb825.jpg)

landscape mode : 
![Screenshot_2021-03-02-17-36-15-781_mw mwc wallet](https://user-images.githubusercontent.com/80525364/110941365-2a859b00-8330-11eb-870c-f8699f3a69f5.jpg)

**Comment by bayk** [comment]
@sarawut11 , we should support or disable landscape mode.  I think disabling is good, because all layouts are optimized for portrait orientation.
I think in manifest it is possible to specify supported orientation

**Comment by vinayaga07** [comment]
landscape mode is not supported in the latest build, hence closing this ticket.
