### ISSUE TITLE
QT Desktop wallet.  Show that some balance is not confirmed

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#817]
At the wallet balance we want to show that not all coins are confirmed, so user should understand that amount is not finalized.

We can show the balance in green if there are any received and still not confirmed balance available.

**Comment by bayk** [comment]
Here are design proposal that we will have.

vek — 03/15/2021
I don't like how highlighting solve this issue, it's not clear for the user perspective whether why it will be in green or not, and what's the amount involved to have the amount in orange intuitively without getting a look to the account state (spendable - locked - unconfirmed) imo. I think the best would be to show confirmed balance and unconfirmed or dissociate both in the total and show only confirmed balance but i don't like it because it can be confusing to not see the balance in the top left updated when you receive some amount even if it's unconfirmed.
Maybe @privateidentity @MrT could give some through on this to get a better user experience on this issue
MrT — Yesterday at 2:18 PM
Bitpay for example just shows the total amount including unconfirmed.
It's only indicated on the tx itself by saying "incoming" instead of "received", but that's in the tx section of the screen. 
Due to the difference in mw I agree that it would be nice to easily see the amount of unconfirmed funds tho, or to at least get a hint.

I think @vek 's suggestion of printing the unconfirmed Amount below just differently formated is nice (maybe with some "wait" icon infront instead of the unconfirmed text, and/or a bit smaller and maybe a bit grey-ish)
Only thing I'd change is to include the unconfirmed amount above instead of subtracting it so the "main" number still behaves as it does now. 
This would (at least in my brain) mean "the big fat number is the total I "got" with the smaller bit below beeing 'still incoming' "

If we don't wan't to risk the confusion having 2 numbers there maybe a "waiting/syncing icon" below the total amount with some hover over text would suffice too to inform about unfinalized amounts. (behaving as a button taking u to the first unfinalized tx it finds if possible)
vek — Yesterday at 3:18 PM
good idea :thumbsup:

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/112251075-d031e780-8c17-11eb-8af3-d1c7d84bc00e.png)

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
