### ISSUE TITLE
The Export to CSV dosent include Transaction Note and Transaction Message.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#819]
Its important to have them.

**Comment by vinayaga07** [comment]
Verified with the latest build and observed Column. name as "Slate Message" instead of "Transaction Message".
Hence reopening this ticket.

![image](https://user-images.githubusercontent.com/63310656/112174368-5d773b00-8c1c-11eb-8567-4c114712bf61.png)

**Comment by bayk** [comment]
Column name is updated

**Comment by vinayaga07** [comment]
Verified, hence closing this ticket.
