### ISSUE TITLE
QT Wallet. Minimum secondary currency amount need to be set depend on coins.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#821]
Currently we have such features for fees only, need extend it to trading amounts.

**Comment by bayk** [comment]
Testing:
Please check that min amounts for mainnet are:

BTC:  0.001
BCH: 0.001
LTC: 0.01
ZCash: 0.01
Dash: 0.01
Doge: 100

For floonet limits are 10 times smaller.

**Comment by Viv-dev-mwc** [comment]
Verified the fix , hence closing this ticket.

BTC: 0.001
BCH: 0.001
LTC: 0.01
ZCash: 0.01
Dash: 0.01
Doge: 100
