### ISSUE TITLE
QT Wallet - Change Errormessage displayed if TOR already running

### ISSUE THREAD

**Issue by MrCryptoT** [mwcproject/mwc-qt-wallet#825]
**Description:**
A User had an Issue getting Tor up and running appearently because it was already running. 
Not sure why this happened, I have a feeling this was a "fluke" that happens due weird circumstances like TOR "crashing".

I know @bayk mentioned that TOR may be having issue's due to bug #823 but I think Dirty Rusky (The affected Discord user) could run the QT with TOR without Issues after stopping the already-running process. 

I'd like to request a change of the Errormessage displayed when tor is already running anyways. Currently in this case the QT Wallet prints the following Errormessage, which could be better worded imo. Without an inherent feeling for Error-causes I woulnd't have realised that tor is already running by the errormessage used right now. 

(for Example "Tor already running, please stop it first" instead of "No, it's still there". I mean technically tor is still there, and no is probably an anwser to a start request, but it would be nice if the error would tell a user how to resolve it instead)
![unknown](https://user-images.githubusercontent.com/8693733/112459777-81429a00-8d5e-11eb-9510-bd64a8667af4.png)

**Reproducing:**
I cannot reproduce this Error and there isn't much information availlable on what caused it other than longer use of the wallet. (Maybe the user killed the wallet process once or something who knows) I don't think it's an inherent error, probably some weird circumstances that made TOR get stuck.

**Comment by bayk** [comment]
It is relatively easy to reproduce by killing the task. I guess it is Windows, right?
We will print the message that rot is running and user will need to kill tor or reboot.

**Comment by MrCryptoT** [comment]
Yes it's on Windows. 
Thanks alot for changing the message!
