### ISSUE TITLE
QT-Wallet, changing Running Mode failed

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#828]
**Description:**
In QT-wallet, while changing the Running Mode from "Online wallet - MWC wallet with a full functionality" to "Online MNode - MWC node that provides blockchain data for the Cold wallet" , wallet restarted and failed with the below error message.

```
mwc-node process exited. Process error: 1

Command line:

>> cd '/Users/vmoorthy/mwc-qt-wallet/mwc-node/floo/'
>> /Volumes/mwc-qt-wallet 1/mwc-qt-wallet.app/Contents/MacOS/mwc '--floonet' 'server' '--allow_to_stop' 'run'
```

![image](https://user-images.githubusercontent.com/63310656/113017119-c4589f00-919c-11eb-95d2-662926d72455.png)

![image](https://user-images.githubusercontent.com/63310656/113016399-10571400-919c-11eb-9f8d-656916863b92.png)

**Note:**
Build- mwc-qt-wallet_1.2.3-macosx.dmg

**Comment by bayk** [comment]
@Viv-dev-mwc , I can't reproduce it.   I try both mainnet and floonet and it works for me.
I am running with fresh config, MacOS.
Please upload your  mwc-qt-wallet/mwc-gui-wallet-v3.conf    and logs.

**Comment by bayk** [comment]
Work with current build for me

**Comment by Viv-dev-mwc** [comment]
Seems like an old bug.
Verified with the latest build and it works as expected. Hence closing this ticket.
