### ISSUE TITLE
In Mobile wallet, Validate Proof File option is failing

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#838]
**Description:**
In Mobile wallet, Validate Proof File option is failing with the below error message.

![image](https://user-images.githubusercontent.com/63310656/114061064-a0d7d780-98b3-11eb-8cab-b491659843bf.png)

**Comment by Viv-dev-mwc** [comment]
Verified with Today's build and observed the same issue.
Hence re-opening this ticket.

**Comment by Viv-dev-mwc** [comment]
Verified with the latest build and getting the below error message.
Hence re-opening this ticket.

![image](https://user-images.githubusercontent.com/63310656/114751235-83eb4a80-9d72-11eb-859e-b3e21f98557a.png)

**Comment by chaindbkey** [comment]
The file should be imported from download folder for now. In the above example, it is from documents, not download folder.

**Comment by Viv-dev-mwc** [comment]
Verified with the latest build and observing the below error message.
Hence re-opening this ticket.

![image](https://user-images.githubusercontent.com/63310656/116124986-9b1b2800-a6e2-11eb-8cf5-bd8bc9901615.png)

**Comment by Viv-dev-mwc** [comment]
Verified, hence closing this ticket.
