### ISSUE TITLE
MWC MQ  should report if second party is not online

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#84]
Currently behavior of second party was able to process transaction is slightly different from if second party is offline.
By reviewing notifications about slates  it is possible to say what is going on. 
But if will be much better if wallet can notify user that this send is not going to went though because second party is offline. 
I believe, when both will go back online, transaction will be finished, right? I think our Q is persistent.
When mwc713/MQS will be updated with that, we will think what message to show.

**Comment by bayk** [comment]
qt wallet will use slate IOs and warning from mwc713/MQS to determine if second party is offline.
User will be asked about transaction cancellation.

**Comment by bayk** [comment]
Hi @cgilliard ,  what is the timeout for send?  I am putting 1 minute. Is it ok?

**Comment by cgilliard** [comment]
You mean, if the slate is not finalized within 1 minute, you will prompt
the user to cancel? If that's what you mean, I think that's a good number
to use.

**Comment by bayk** [comment]
Yes, that what I meant

**Comment by bayk** [comment]
mwc713  printing the warning about last time when 2nd parti last time was online.  That warning is printed with regular workflow, at notifications.
