### ISSUE TITLE
Mobile wallet, Send via file transaction failed during Finalize page

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#840]
**Description:**
In Mobile wallet, after sending MWC via file, on Finalize stage it is failing with the below error message.

![image](https://user-images.githubusercontent.com/63310656/114750284-71bcdc80-9d71-11eb-9252-bca0b2a2c81c.png)

**Steps followed**
1. log in to Mobile wallet and initiate Send MWC via file transaction.
Note: .tx file will be generated and shared to the receiver's wallet.
2. Login to desktop QT wallet and goto the "Receive MWC by File" option
3. Provide .tx file and generate a response with the file tx.response
Note: send back the .tx.response file to the sender's wallet.
4. In the mobile wallet, click "Finalize" and then select "Upload a File" option

**Comment by bayk** [comment]
Please check logcat  for  

parseTransaction for  "/storage/emulated/0/Download//com.android.providers.downloads.documents/document/3375"  Body: ""

For me this file is not accessible.

**Comment by chaindbkey** [comment]
The file should be only imported from download folder for now. In the above example, it is from documents, not download folder.

**Comment by Viv-dev-mwc** [comment]
Verified with the latest build and observed the below error message, hence re-opening it.

![image](https://user-images.githubusercontent.com/63310656/116125283-eaf9ef00-a6e2-11eb-8955-41bf2bbcb69f.png)

**Comment by bayk** [comment]
@chaindbkey  please take a look.

**Comment by Viv-dev-mwc** [comment]
Verified, hence closing this ticket.
