### ISSUE TITLE
QT wallet, TOR service is not getting started due to the last time it wasn't exited properly.

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#843]
Description:
In the QT wallet, TOR service is not getting started due to the last time it wasn't exited properly.
Expecting a proper message with the steps to fix the issue (starting TOR services).

![image](https://user-images.githubusercontent.com/63310656/115588940-e7cebf80-a2ec-11eb-916a-394bfb534758.png)

![image](https://user-images.githubusercontent.com/63310656/115588968-edc4a080-a2ec-11eb-8933-cfb78018f319.png)

**Comment by bayk** [comment]
Should be fixed in current nightly

**Comment by Viv-dev-mwc** [comment]
Verified with the latest build, hence closing this ticket.
