### ISSUE TITLE
QT wallet, unable to start the marketplace offer in floonet due to  BTC amount must be at least 0.001.

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#844]
**Description:**
In QT wallet, unable to start the marketplace offer in floonet due to  BTC amount must be at least 0.001.

![image](https://user-images.githubusercontent.com/63310656/115589394-6af01580-a2ed-11eb-987b-b826420940fc.png)

**Comment by Viv-dev-mwc** [comment]
Verified with the latest build and observed the same error message, while providing the amount 0.00001 BTC for exchange.

![image](https://user-images.githubusercontent.com/63310656/116905361-813a9180-ac5c-11eb-8339-14489832fa67.png)

**Comment by bayk** [comment]
Issues happens because for floonet we allow to use 10 time less amounts.  We have too much issues with that. That is why now floonet and mainnet operates by equal amounts.

**Comment by Viv-dev-mwc** [comment]
Verified the fix with the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/117169236-8fb4b480-ade6-11eb-9d38-a610f73ef5f0.png)
