### ISSUE TITLE
During Marketplace offer, when TOR just losing the connection there is no clue to the user on desktop QT wallet.

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#846]
Description:
During Marketplace offer, when TOR just losing the connection there is no clue to the user on desktop QT wallet.
Expecting a message, when TOR lost the connection.

**Comment by bayk** [comment]
Just to clarify. It is not related to marketplace issue. Tor p2p connection stop working. It is know problem for tor.

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
