### ISSUE TITLE
Mobile wallet Logout screen, the MWC amount displaying in the account is not matching

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#848]
**Description:**
In the mobile wallet Logout screen, the MWC amount displaying in the account is not matching with the Amount displaying in the other screens.
Please refer to the below screenshot and attached video [recordings.]

https://user-images.githubusercontent.com/63310656/116444021-ee6fb080-a871-11eb-890a-e4dcf6058e42.mp4

![image](https://user-images.githubusercontent.com/63310656/116443596-7acda380-a871-11eb-8ed6-10791cde4e1b.png)

**Steps to reproduce:**
1. Log in to Mobile wallet.
2. Receive the MWC amount into the wallet.
3. Verify the amount displaying in the Logout screen and other screens (as captured in the video recorded)

**Comment by bayk** [comment]
@Viv-dev-mwc   Total wallet amount and Spendable on the account are different numbers.  You can have 0 spendable at default  and 2 MWC total.  This feature works for me.  Please provide more details about this issue. 
So far is doesn't looks like an issue.

**Comment by Viv-dev-mwc** [comment]
MWC amount has been successfully received on the wallet, after confirmation both Spendable and Total available amount have been updated on all the pages, but on the Log out page amount is not getting refreshed.

Attached new video recordings for your reference.
https://user-images.githubusercontent.com/63310656/116576814-88e0fa00-a92d-11eb-9726-bfb5f6318cf4.mp4

**Note:**
After Logout and login, values are getting updated on the Logout screen.

**Comment by bayk** [comment]
@chaindbkey ,  it is a bug or UX issue. In any case it needs to be solved.  If numbers are different because of non confirmed coins issue, you can't tell if it a case.  The same questions we will get form the users as well. 
Please make those numbers consistent or provide the way to see spendable and total amounts.

**Comment by chaindbkey** [comment]
Let's remove the account selection part in the sidebar for now since all every needed pages have account selection part.
And if users request that, then let's restore it later. @bayk

**Comment by Viv-dev-mwc** [comment]
Verified with the latest build, hence closing this ticket.
