### ISSUE TITLE
Mobile wallet, transaction proof validation failure error message need to be corrected.

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#849]
**Description:**
In the Mobile wallet, if transaction proof validation failed due to the file kept in the wrong folder instead of the expected "Download" folder, then there should be an error message to the Users with the meaningful information. 
The current error message will not help Users to understand the issue.

Please refer to the screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/116444660-95ece300-a872-11eb-884b-bf037240303d.png)

**Comment by bayk** [comment]
@Viv-dev-mwc , error message is helps to understand the issue.  It is download folder how app see it. Let's solve the root problem about file access.

**Comment by Viv-dev-mwc** [comment]
Root problem solved, hence closing this ticket.
