### ISSUE TITLE
allow sending to other domains on mwcmqs

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#85]
We support different domains on mwcmqs. So, this is a valid address:

mwcmqs://xmifskXS7CmzhCHxVHvNhJsSLdFx1aipW6MJ94kdpuKEiaHPRwEA@test3.mwc.mw. 

See screenshot for error.

The ui currently prevents you from sending to different domains. test3.mwc.mw has a server setup, so you can configure your mwc713 instance by setting mwcmqs_domain = "test3.mwc.mw".

<img width="683" alt="Screen Shot 2019-09-01 at 11 13 46 PM" src="https://user-images.githubusercontent.com/7232183/64093747-68067280-cd0e-11e9-8558-eca4edd3cedc.png">

**Comment by bayk** [comment]
Will fix address validation.
Also I think we need to display the domain at Contacts and Receive page. Let's talk about that
