### ISSUE TITLE
the Mobile wallet version is getting displayed as 1.2.1 but desktop wallet version is 1.2.3

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#850]
**Description:**
Currently, the Mobile wallet version is getting displayed as 1.2.1  whereas the latest released desktop wallet version is 1.2.3.
1. Expecting Mobile wallet version should be matching with QT wallet version.
2. Currently it is displaying dev build, before release which needs to be updated.

![image](https://user-images.githubusercontent.com/63310656/116445606-b23d4f80-a873-11eb-8fc5-bd771bd7fbe6.png)

**Comment by bayk** [comment]
Yes, for mobile we need to update version manually. 
Keep it in sync with desktop doesn't make much sense because it always behind from features perspective. Features are not match in any case.
Instead I think we should switch to mobile versions that app used for releases.

**Comment by bayk** [comment]
The version need to match what we have at manifest. Android package manager can provide that.  Here is a link how to access to package manager with QML.

https://falsinsoft.blogspot.com/2018/04/qml-get-android-apk-package-info.html
 
"versionName"  - it is what we need to print.

In this case when @jbyrer   do release, he will name the version and that name will be shown in UI.

**Comment by Viv-dev-mwc** [comment]
Assigning this ticket to @jbyrer .

**Comment by Viv-dev-mwc** [comment]
Closing this ticket.
