### ISSUE TITLE
Make indicator of Tor offline when http listener is on "Local and Internet"

### ISSUE THREAD

**Issue by vek-kal** [mwcproject/mwc-qt-wallet#854]
Currently when the HTTP listener is configured on "Local and Internet", Users can't receive on the wallet via TOR but the tor indicator is in green which mislead the user, letting him thinking he can receive via tor.

I'm proposing to switch the indicator of Tor to offline when http listener is on "Local and Internet". And print to the users that he need to switch to "Local Service" or make it automatically if he starts TOR listener.

**Comment by bayk** [comment]
Tor with Local and Internet works fine with current release

**Comment by bayk** [comment]
Just tested all http setting vs tor. I don't see any issues. UI direct user for all edge cases

**Comment by Viv-dev-mwc** [comment]
@bayk, Verified with the latest build and observed that the TOR listener status is green while HTTP listener is configured with "Local and Internet".

![image](https://user-images.githubusercontent.com/63310656/116902689-120f6e00-ac59-11eb-80a1-9359d56346aa.png)

**Comment by bayk** [comment]
@Viv-dev-mwc ,  Tor is expected to work for "Local and Internet".  That what we want

**Comment by Viv-dev-mwc** [comment]
For me also TOR is activated when I switched to local & internet...Closing as per the above comment.
