### ISSUE TITLE
[MWC-QT-WALLET] Grammar 

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#855]
List of grammar corrections to be made

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/116914199-46564080-abff-11eb-86ec-48350ee7f708.png)

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/116914286-638b0f00-abff-11eb-9d00-94af6adb94b0.png)

**Comment by bayk** [comment]
It is a limit. That limit depend on wallet task. Usually it ends faster. 
Exiting is not an option, we can only kill the task and there is a slight chance in data corruption.
