### ISSUE TITLE
[MWC-QT-WALLET] grammar

### ISSUE THREAD

**Issue by jbyrer** [mwcproject/mwc-qt-wallet#856]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/10661009/116922807-b6b68f00-ac0a-11eb-8c31-ab6bf4175a9f.png">
The number of MWC confirmations (10) is less than the recommended number of confirmations (40)</br>
The number of BTC confirmations (2) is less than the recommended number of confirmations (3)</br>
This trade may be vulnerable to a reorg attack.

**Comment by jbyrer** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/10661009/116924977-6d1b7380-ac0d-11eb-9d99-504b9e430c56.png">

**Comment by jbyrer** [comment]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/10661009/116925146-a9e76a80-ac0d-11eb-9de3-9543d60cd021.png">
tbh not sure how to replicate this as I have no idea what the actual error is, could be a bad number of blocks, or could be a bad address.

**Comment by jbyrer** [comment]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/10661009/116928739-4c095180-ac12-11eb-84d8-ab48c70ce5dd.png">
The "Selling 10 MWC for 3 BTC" is incorrect, those are the number of blocks needed, the amounts being traded were .1 and .0001

**Comment by jbyrer** [comment]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/10661009/116929024-b1f5d900-ac12-11eb-8594-70784733e499.png">

**Comment by jbyrer** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/10661009/116930294-6cd2a680-ac14-11eb-89fd-1a7c3bda7c11.png">
Your offer acceptance has been sent to the offer creator (id here).  You should receive a confirmation soon.  </br>
</br>
Please Note:
If several traders have accept this offer simultaneously, the offer will be rewarded to whomever locked funds first.  All parties will be notified accordingly.

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/117042264-96e1a280-acc0-11eb-9693-2c22600c99a9.png)
You have 2 swap marketplace offers active from your previous session.  Would you like to restore and put them on the market?

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/117042587-05befb80-acc1-11eb-9146-f25f79d1719f.png)
Your account doesn't have enough funds to cover the itegrity fees for your offer.  This offer will be deleted.

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/117044018-c691aa00-acc2-11eb-9390-1c37615360a2.png)
Your sell offer has been rejected because the outputs that it used have been spent.  This may have been caused by using the same outputs to make your integrity fee payment. </br>
You do not have enough funds in your account (default). You need at least 1.25 MWC, but have 0 available.

**Comment by jbyrer** [comment]
<img width="976" alt="image" src="https://user-images.githubusercontent.com/10661009/117082999-77666c00-acf8-11eb-9b6d-1964f73414fb.png">
Critical hardware failures (such as a Hard disk failure) during a trade could result in a loss of funds.  We strongly suggest backing up your trades to a non local system drive (such as a usb drive or cloud storage).   In the case of such a hardware failure, trades can be recovered by:</br>

- Restoring your wallet from seed
- Restoring your  trade.

**Comment by jbyrer** [comment]
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/10661009/117083355-5eaa8600-acf9-11eb-8852-627105e5de42.png">
Status: Complete

I think that is all we need, I don't think we need to point out it was a "seller" swap trade, but I could be wrong, feel free to disucss.

**Comment by jbyrer** [comment]
<img width="919" alt="image" src="https://user-images.githubusercontent.com/10661009/117338686-b6f59b00-ae53-11eb-8de9-2199a816709c.png">
I need to have a better understanding of this, will follow up with K.

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/117356568-bd424200-ae68-11eb-9461-4ed7afb694d9.png)
Another party has accepted your offer (Swap Id here rather than amount?) , and has locked the necessary funds.  You can follow the progress of your trad on the Swap page.

Could we put the swap id in this message, so they know what to look for when they head to the swap page?

**Comment by bayk** [comment]
@jbyrer ,  For 'Another party has accepted your offer '  we can't put swap ID instead of "Selling 1 MWC for XXXXX" because offer doesn't have ID.
I will check if I can add swap ID. That data comes from different source, swap ID might not be known at that moment.

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/117692420-db15ec80-b171-11eb-8043-87308dd1a367.png)

In order to improve swap security, please specify a transaction fee large enough to ensure your transaction will be mined within 30 minute.

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/117692732-292af000-b172-11eb-9c48-2bbc05d22be7.png)

the help button here doesn't function.

**Comment by jbyrer** [comment]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/10661009/117731227-9b1b2d80-b1a2-11eb-8544-7aa9669c071f.png">
My apologies, after using this screen to actually make swaps, I realize that the wording "If you receive this message, do NOT ...."
is confusing and could cause the users to think that THIS message is the message indicating they should not deposit coins. 

The wording should probably be something like:

"If you are notified that you offer has been dropped, do NOT deposit any coins into the lock account. "

idk if this needs to make it into this release, but it might be a good idea.
Thanks,
Jim

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/117993499-a67e6e00-b2f4-11eb-87eb-c81ffe48766a.png)

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/117995210-fe69a480-b2f5-11eb-90cc-9cbe201ce79a.png)
Unfortunately someone else locked funds and accepted trade <id> before you. </br>
 Please don't deposit any coins to the lock account.  After the trade expiration time has passed, the trade will be cancelled automatically.</br>
If you have already locked your coins, you will need to wait until your payment is refunded.

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/117996186-cadb4a00-b2f6-11eb-9d1c-643ac85ef0da.png)
this is swap, so I can move it to a different bug if we decide.

Status: Wait....  I we do not receive a response, a refund will be posted in <number> minutes.

**Comment by bayk** [comment]
> ![image](https://user-images.githubusercontent.com/10661009/117995210-fe69a480-b2f5-11eb-90cc-9cbe201ce79a.png)
> Unfortunately someone else locked funds and accepted trade before you.
> 
> Please don't deposit any coins to the lock account. After the trade expiration time has passed, the trade will be cancelled automatically.
> 
> If you have already locked your coins, you will need to wait until your payment is refunded.

@jbyrer , I need to add a phrase about trade ID.  There are bunch of trades,  user need to know what trade is affected. 

That will be:
"Unfortunately someone else locked funds and accepted trade before you. Your trade " + swap.swapId + " will not go forward."

**Comment by bayk** [comment]
> ![image](https://user-images.githubusercontent.com/10661009/117996186-cadb4a00-b2f6-11eb-9d1c-643ac85ef0da.png)
> this is swap, so I can move it to a different bug if we decide.
> 
> Status: Wait.... I we do not receive a response, a refund will be posted in minutes.

@jbyrer   yes, let's release that that later.  I will do the fix now, but it will not be included into the build.

**Comment by jbyrer** [comment]
![image](https://user-images.githubusercontent.com/10661009/118048404-1874a880-b331-11eb-9e71-bdea78983bf2.png)

**Comment by bayk** [comment]
At this moment all issues are fixed.
Release will include all changes except this one  https://github.com/mwcproject/mwc-qt-wallet/issues/856#issuecomment-839837304

**Comment by MrCryptoT** [comment]
@bayk Some minor Details I found in 1.2.5

Some Toolstips seem copy pasted from the Swap page, For example in the Picture it should probably say "what offers do you want to see". (true for all 3 in this row)
![image](https://user-images.githubusercontent.com/8693733/119137721-6c724200-ba41-11eb-8221-850f078bcafb.png)

The same is true for the "Tab" tooltips above, see here: (true for all 3 in this row)
![image](https://user-images.githubusercontent.com/8693733/119138154-e1de1280-ba41-11eb-966a-aa77f2e8955d.png)

Also, for some reason the Tooltip of my "Details" button of a specific offer itself is cutoff below (but that may just be weird one off), see here: 
![image](https://user-images.githubusercontent.com/8693733/119138368-1782fb80-ba42-11eb-90b6-510bad02dca2.png)

**Comment by jbyrer** [comment]
verified
