### ISSUE TITLE
Mobile wallet builds installation on the Android OS version 11 failed 

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#860]
**Description:**
Mobile wallet builds installation on the Android OS version 11 (Samsung Tab S6 Lite)failed with the below error message.

![image](https://user-images.githubusercontent.com/63310656/118510329-7e589a00-b74e-11eb-9491-9c9231bfb6da.png)

**Notes:**
- Build - https://ftp.mwc.mw/nightly_builds/05-17-2021/
-  The same build successfully installed on Android Version 10.

**Comment by bayk** [comment]
Tested on emulator. I don't have physical Androd 11 device.

**Comment by Viv-dev-mwc** [comment]
Installation of Today's build  https://ftp.mwc.mw/nightly_builds/05-18-2021/ on Android version 11 is failed on the physical device.

**Comment by Viv-dev-mwc** [comment]
After uninstalling the existing Mobile build, able to install Today's build.
