### ISSUE TITLE
[QT-Wallet] Unable to create Atomic Swap trade

### ISSUE THREAD

**Issue by Viv-dev-mwc** [mwcproject/mwc-qt-wallet#869]
**Description:**
Unable to create Atomic Swap for MWC with TST coin.
The field "TST address to receive the coins" is in a disabled state and hence unable to proceed to the next step. Please refer to the below screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/124158692-d9a0da80-dab7-11eb-8472-5d19e06fdd19.png)

**Note:**
Tested with MAC OS.

**Comment by terryzhao** [comment]
Fixed.  Hiding the token receiving address in UI.

**Comment by Viv-dev-mwc** [comment]
Feature changed, hence closing this ticket.
