### ISSUE TITLE
Couldn't switch back to default full node.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#87]
Whenever I put the public full node, got error, unable to connect. I was able to connect by using https://mwc713.floonet.mwc.mw:443. Looks like the default port is 13413. Is the default for mainnet 3413?
<img width="836" alt="Screen Shot 2019-09-02 at 8 14 00 AM" src="https://user-images.githubusercontent.com/7232183/64123682-ee947180-cd59-11e9-9b22-79a9759c72d1.png">

**Comment by cgilliard** [comment]
Looked into it more. Looks like it defaults to 13413 on testnet at least. I didn't try mainnet. Since most nodes will run on SSL on port 443, I think we should use standard http defaults (so https -> 443 and http -> 80).

**Comment by bayk** [comment]
Chris, defaults comes from mwc713. I can add verification that port need to be set.
I think better to change default at mwc713 to match what we provide at mwcmqs by default.

**Comment by cgilliard** [comment]
Ok, will look into this.

**Comment by bayk** [comment]
@cgilliard , sorry for misleading, just found that GUI add the default port for custom node if it is not defined by user. 
Please update what do you think is better - keep updating with default value or enforce user to define it?

**Comment by cgilliard** [comment]
It actually works as is, but the default is currently 443 (standard ssl
default), but a better default would be the default node ports which are:
13413 for testnet and 3413 for mainnet.

**Comment by bayk** [comment]
From the mwc713 code, looks like better not to put any defaults at all.
The default port problem does exist for Custom node, because Node must
match the network (main/floo) and this is a real problem is user specify
the node as a custom. Let's discuss it in discord later, I will ping you.

**Comment by jbyrer** [comment]
sounds good, I'm out at games most of the day, but will check discord.

**Comment by cgilliard** [comment]
Ok, sure.

**Comment by bayk** [comment]
Should be fine by now. GUI doesn't apply default port for custom model.
