### ISSUE TITLE
need to handle the case where there are multiple instances of a wallet connected.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#88]
I had two wallets connected and only one receives the messages causing confusion. I think I will either print a warning that there is another instance connected or kick the old user if a new connection appears.

**Comment by bayk** [comment]
Chris, if you kick out one of the wallets, it will reconnect in a moment. The two wallets will keeps kicking each other out.
You can print the appropriate connection error. GUI will display it and close the wallet.

**Comment by cgilliard** [comment]
Yes will do. I will kick out the old connection.

**Comment by cgilliard** [comment]
This is implemented. When a second instance of the wallet connects, the first instance will be disconnected and get a message that looks like this:

wallet713> 
ERROR: new login detected. mwcmqs listener will stop!
mwcmqs listener [xmgehLCvsHXdoAenuUARvQGMPkzJdm5Qb1wTQVi2WnRaSjC1CWgH] stopped

I added ran a build with the latest qt and it works with this, but you can handle this error message now and prompt the user if this occurs.

**Comment by bayk** [comment]
Great, mwc713 will stop listener by itself. So I just need to show the message to the user. I think no more action will be needed.

**Comment by bayk** [comment]
![image](https://user-images.githubusercontent.com/42393608/64399472-6e9e2e00-d01d-11e9-9608-797bf6ede5e4.png)
