### ISSUE TITLE
Failed receiving slate, Transactions with offset string

### ISSUE THREAD

**Issue by spomemw** [mwcproject/mwc-qt-wallet#899]
Due to the replay attack fix, User can't cancel a transaction and receive it again on the same account. 

![20240726_044158 (1)](https://github.com/user-attachments/assets/91c50034-78dd-4272-9ddc-3590d114a563)

**Comment by bayk** [comment]
Steps to reproduce:
- receive a tx, generate response.
- cancel it.
- change your mind, receive it once more and regenerate the response for the same slate.
