### ISSUE TITLE
Some of the modals probably would be better as indicators that appear temporarily

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#90]
For instance, when the recipient receives a transaction or when you complete seed verification. @condensed-io might be able to design something around this.

**Comment by bayk** [comment]
Yes, that will be better. Currently we have status line for notification messages, but it is not efficient for messages that expected something from the used.

**Comment by cgilliard** [comment]
Analogy: like a outlook notification of a new email that appears in the bottom right temporarily.

**Comment by bayk** [comment]
We have events that cover similar functionality. We show them in the status line.
For those one we need show them with better visibility. 
Probably we should consider to show our event messages better way

**Comment by cgilliard** [comment]
Yeah, Sharon is going to research this one and once we get the prototype
working we can use it for many things.

**Comment by scasaletto** [comment]
New feature to show notications in status windows in the lower right hand corner of the Qt Wallet main window has been implemented.
![image](https://user-images.githubusercontent.com/7772099/89456828-13435700-d72a-11ea-8230-3012e63ae218.png)

**Comment by vinayaga07** [comment]
Verified the latest Notification displayed on the QT-wallet, hence closing this ticket.
