### ISSUE TITLE
mwc713 mwc mqs  dicsonnect detection time is long

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#92]
The workflow:
- Start wallet
- turn off internet
- waiting for the connection error message 

For mwc mqs it takes pretty long time to detect disconnection (I think more than a minute). 
Can we detect it faster?

**Comment by cgilliard** [comment]
Will try to improve. Detecting disconnects is not easy because you don't want false positives. The current method is that there is a 120 second socket read timeout so you should see it by then.
