### ISSUE TITLE
for default it shows the long address in qt wallet

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#93]
<img width="911" alt="Screen Shot 2019-09-08 at 5 14 02 PM" src="https://user-images.githubusercontent.com/7232183/64494528-202aa280-d25c-11e9-8d64-aef38fc02e22.png">

Should display: This: mwcmqs://xmhxet7dASTLJffrVbCXoaedzJCfJdBx3AXwaNbeK6vA9JnSVvgf@mqs.mwc.mw

As:

mwcmqs://xmhxet7dASTLJffrVbCXoaedzJCfJdBx3AXwaNbeK6vA9JnSVvgf

**Comment by bayk** [comment]
Chris, I make it to cover the case for non standard MWC MQ domains.  If there are too wallets using different mwc mq domains,  the full name will be required.
I am expecting that users just copy that address and send to the second party.

**Comment by cgilliard** [comment]
Even though we handle other domains, we can still have a default. This is
how grinbox was implemented as well. If you don't specify a domain it uses @
grinbox.com as the domain. In our case it would be @mqs.mwc.mw as the
default domain.

**Comment by bayk** [comment]
Get it. Will update soon
