### ISSUE TITLE
got a message about second party not receiving the transaction, but transaction was already confirmed.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#94]
See screenshot.
<img width="830" alt="Screen Shot 2019-09-08 at 11 48 04 PM" src="https://user-images.githubusercontent.com/7232183/64502303-4cade100-d293-11e9-8c93-2ab23faf95d4.png">

The message popped up about a minute after I had sent and it looks like it had already successfully been finalized.

**Comment by cgilliard** [comment]
Also, I think that message should give you the transaction id or some other way of identifying which transaction you are canceling.

**Comment by bayk** [comment]
We have Transaction Number.  In your case cancellation would fail, mwc713 is checking if it can cancel it.  Will take a look. Probably finalize message was missed

**Comment by cgilliard** [comment]
The Finalize message ended up in the log.

**Comment by bayk** [comment]
@cgilliard,  I can't reproduce it.  It works for me. I am sending from one wallet to another and there is no issues.
Did you do something special?

**Comment by cgilliard** [comment]
I don't remember. I will keep my eye out for it and let you know if I can get it to happen again.

**Comment by bayk** [comment]
Code looks good, the only reason - the slate message wasn't parsed.
But in any impact is not high. In worst case user can get a false alarm. Transaction will not be cancelled if it is finalized.
