### ISSUE TITLE
Windows, Airdrop claims

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#98]
https respond return error 'TLS initialization failed'

**Comment by cgilliard** [comment]
Are you using the nightly builds? You need open ssl which is included.

**Comment by bayk** [comment]
Thank you for letting me know. I am running from IDE, I will try add this
dll, it should help.

**Comment by cgilliard** [comment]
Here's the dlls you need in the directory that mwc-qt-wallet.exe and mwc713.exe are in: https://github.com/mwcproject/mwcbuildpipeline/tree/master/nsis/payload/x64
